// ── CALISTHENICS + RUNNING + HYDRATION + DIET DATA ─────────────
// Loaded after data.js — extends window.APP_DATA with all new content
(function() {
  var D = window.APP_DATA;
  if (!D) { console.error('[FitFlow] data.js must load before data-cali.js'); return; }

  // ── CALISTHENICS MODULE (Levels 1/2/3) ───────────────────────────
  D.modules.calisthenics = {
      name: "Calisthenics",
      emoji: "🤸‍♂️",
      color: "grad-cali",
      levels: {
        1: { name:"Beginner",     desc:"Weeks 1–8 · Foundation strength", days: {
          Monday:    [
            { name:"Incline Push-Ups",    sets:3, reps:"10–15 reps",  desc:"Hands elevated on chair. Body straight. Lower chest toward surface, push up. Easier than floor push-ups — build to 15 reps before progressing.", image:"", demo:"https://www.youtube.com/results?search_query=incline+push+ups+beginners" },
            { name:"Negative Push-Ups",   sets:3, reps:"5 slow reps", desc:"Lower yourself SLOWLY (5 sec) from push-up top position. Builds pushing strength even if you can't push up yet. From knees is fine.", image:"", demo:"https://www.youtube.com/results?search_query=negative+push+ups+beginners" },
            { name:"Pike Push-Up Hold",   sets:3, reps:"30 sec",      desc:"Downward dog position, lower head toward floor and hold. Shoulder press prep. Keep elbows pointing back, not flared.", image:"", demo:"https://www.youtube.com/results?search_query=pike+push+up+shoulder" },
            { name:"Plank Hold",          sets:3, reps:"20–30 sec",   desc:"Forearms on floor, body straight. Squeeze glutes and core. Build to 60 sec before Level 2.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+beginners" },
            { name:"Hollow Body Hold",    sets:3, reps:"15 sec",      desc:"Lie on back, lower back pressed flat, raise shoulders and legs slightly. Arms overhead. The foundation of all calisthenics.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+body+hold+calisthenics" },
            { name:"Dead Hang",           sets:3, reps:"15–20 sec",   desc:"Hang from any bar with both hands. Relax completely. Builds grip strength and shoulder health. Prerequisite for pull-ups.", image:"", demo:"https://www.youtube.com/results?search_query=dead+hang+bar+beginners" },
            { name:"Shoulder Tap Plank",  sets:3, reps:"10 taps",     desc:"High plank. Alternate touching opposite shoulder. Keep hips square. Core anti-rotation strength.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+tap+plank+core" },
            { name:"Wrist Conditioning",  sets:1, reps:"2 min",       desc:"Wrist circles, finger extensions, palm stretches. Prevents wrist pain from bodyweight training.", image:"", demo:"https://www.youtube.com/results?search_query=wrist+conditioning+calisthenics" },
          ],
          Tuesday:   [
            { name:"Australian Rows",     sets:3, reps:"8–12 reps",   desc:"Set a bar at hip height. Hang underneath with straight body, pull chest to bar. The horizontal pull-up. Back development without a pull-up bar.", image:"", demo:"https://www.youtube.com/results?search_query=australian+row+bodyweight+beginners" },
            { name:"Negative Pull-Ups",   sets:3, reps:"3–5 reps",    desc:"Jump to top of pull-up position. Lower SLOWLY (5 sec) to full hang. Builds pulling strength before you can do a full pull-up.", image:"", demo:"https://www.youtube.com/results?search_query=negative+pull+ups+beginners" },
            { name:"Dead Hang",           sets:3, reps:"20–30 sec",   desc:"Hang from bar, relax shoulders. Build grip and shoulder health. Progress from 15 to 60 seconds over 8 weeks.", image:"", demo:"https://www.youtube.com/results?search_query=dead+hang+progression" },
            { name:"Scapular Pulls",      sets:3, reps:"10 reps",     desc:"In dead hang, depress and retract shoulder blades without bending elbows. Activates lats. Foundation for real pull-up strength.", image:"", demo:"https://www.youtube.com/results?search_query=scapular+pull+ups+bar" },
            { name:"Superman Hold",       sets:3, reps:"30 sec",      desc:"Lie face down, lift arms and legs simultaneously. Builds lower back and posterior chain.", image:"", demo:"https://www.youtube.com/results?search_query=superman+hold+exercise" },
            { name:"Band-Assisted Pull-Up",sets:3,reps:"5–8 reps",   desc:"Loop band around bar, place knee/foot in it. Full range pull-ups with assistance. Builds the pattern.", image:"", demo:"https://www.youtube.com/results?search_query=band+assisted+pull+up+beginners" },
            { name:"Plank to Down Dog",   sets:3, reps:"10 reps",     desc:"From high plank, press hips up to downward dog, return. Builds shoulder mobility and core connection.", image:"", demo:"https://www.youtube.com/results?search_query=plank+to+downward+dog+exercise" },
            { name:"Dead Bug",            sets:2, reps:"5 each side", desc:"On back, lower opposite arm and leg while pressing lower back to floor. Best core stability exercise.", image:"", demo:"https://www.youtube.com/results?search_query=dead+bug+exercise+core" },
          ],
          Wednesday: [
            { name:"Assisted Squat",      sets:3, reps:"15 reps",     desc:"Hold a door frame for balance. Squat as deep as possible. Heels flat, knees track over toes. Builds squat pattern.", image:"", demo:"https://www.youtube.com/results?search_query=assisted+squat+beginners" },
            { name:"Box Squat",           sets:3, reps:"12 reps",     desc:"Sit back onto a chair-height box, pause briefly, stand up. Teaches squat mechanics. Lower box height progressively.", image:"", demo:"https://www.youtube.com/results?search_query=box+squat+beginners" },
            { name:"Glute Bridge",        sets:3, reps:"15 reps",     desc:"On back, knees bent, feet flat. Drive hips to ceiling, squeeze glutes hard at top. Hold 1 second.", image:"", demo:"https://www.youtube.com/results?search_query=glute+bridge+exercise+form" },
            { name:"Reverse Lunges",      sets:3, reps:"10 each leg", desc:"Step backward into lunge, back knee toward floor. Push off front foot to return. Less knee stress than forward lunges.", image:"", demo:"https://www.youtube.com/results?search_query=reverse+lunge+beginners" },
            { name:"Calf Raises",         sets:3, reps:"20 reps",     desc:"Standing on flat floor. Rise onto tiptoes, hold 1 second, lower slowly. Progress to single-leg.", image:"", demo:"https://www.youtube.com/results?search_query=calf+raises+bodyweight" },
            { name:"Hollow Body Hold",    sets:3, reps:"20 sec",      desc:"Lie on back, press lower back flat. Fundamental for all advanced calisthenics. Build to 60 sec.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+body+hold+calisthenics" },
            { name:"Wall Sit",            sets:3, reps:"30 sec",      desc:"Back flat on wall, thighs parallel to floor, knees at 90°. Develops quad endurance.", image:"", demo:"https://www.youtube.com/results?search_query=wall+sit+exercise" },
            { name:"Hip Flexibility",     sets:2, reps:"60 sec each", desc:"Hip flexor lunge stretch each side. Essential for squat depth and pistol squat progression.", image:"", demo:"https://www.youtube.com/results?search_query=hip+flexor+lunge+stretch" },
          ],
          Thursday:  [
            { name:"Dead Bug",            sets:3, reps:"10 each side",desc:"On back, arms up, knees bent 90°. Lower opposite arm and leg simultaneously. Best core stability exercise.", image:"", demo:"https://www.youtube.com/results?search_query=dead+bug+exercise" },
            { name:"Plank Hold",          sets:3, reps:"30 sec",      desc:"Forearms on floor, body straight. Breathe normally. Build to 60 sec minimum before progressing.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+core" },
            { name:"Side Plank",          sets:3, reps:"20 sec each", desc:"On forearm, stack feet or stagger. Body forms a straight line. Builds lateral core stability.", image:"", demo:"https://www.youtube.com/results?search_query=side+plank+beginners" },
            { name:"Bird Dog",            sets:3, reps:"10 each side",desc:"On all fours, extend opposite arm and leg. Keep back flat. Builds core stability.", image:"", demo:"https://www.youtube.com/results?search_query=bird+dog+exercise+core" },
            { name:"Mountain Climbers",   sets:3, reps:"30 sec",      desc:"High plank, drive alternating knees toward chest. Keep hips level. Cardio + core.", image:"", demo:"https://www.youtube.com/results?search_query=mountain+climbers+exercise" },
            { name:"V-Up Prep",           sets:3, reps:"8 reps",      desc:"Lie on back, arms overhead. Simultaneously lift upper body and legs. Modify by bending knees.", image:"", demo:"https://www.youtube.com/results?search_query=v+up+exercise+core" },
            { name:"Hollow Body",         sets:3, reps:"15 sec",      desc:"Perfect hollow position: arms by ears, legs lifted, lower back flat.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+body+hold" },
            { name:"Deep Breathing",      sets:1, reps:"3 min",       desc:"Box breathing: inhale 4 sec, hold 4 sec, exhale 4 sec, hold 4 sec. Active recovery.", image:"", demo:"https://www.youtube.com/results?search_query=box+breathing+technique" },
          ],
          Friday:    [
            { name:"Incline Push-Ups",    sets:4, reps:"12 reps",     desc:"Lower surface than Monday — more load. Progressive angle reduction.", image:"", demo:"https://www.youtube.com/results?search_query=incline+push+ups+progression" },
            { name:"Australian Rows",     sets:4, reps:"10 reps",     desc:"Bodyweight rows. Focus on scapular retraction. Lower body angle for more difficulty.", image:"", demo:"https://www.youtube.com/results?search_query=australian+row+technique" },
            { name:"Box Squat",           sets:4, reps:"12 reps",     desc:"Try going slightly lower than Wednesday. Progressive depth.", image:"", demo:"https://www.youtube.com/results?search_query=box+squat+progression" },
            { name:"Plank to Push-Up",    sets:3, reps:"8 reps",      desc:"From forearm plank, press up to high plank one arm at a time, return. Builds shoulder stability.", image:"", demo:"https://www.youtube.com/results?search_query=plank+to+push+up" },
            { name:"Pike Push-Ups",       sets:3, reps:"8 reps",      desc:"Downward dog, lower head toward floor by bending elbows. Vertical pressing for handstands.", image:"", demo:"https://www.youtube.com/results?search_query=pike+push+ups+beginners" },
            { name:"Single-Leg Glute Bridge",sets:3,reps:"10 each",  desc:"Standard bridge, extend one leg — hold 3 sec. Prep for pistol squat path.", image:"", demo:"https://www.youtube.com/results?search_query=single+leg+glute+bridge" },
            { name:"Dead Hang",           sets:3, reps:"25 sec",      desc:"Hang from bar. Build to 60 seconds over 8 weeks.", image:"", demo:"https://www.youtube.com/results?search_query=dead+hang+progression" },
            { name:"Full Stretch",        sets:1, reps:"5 min",       desc:"Chest, back, legs, shoulders. Wrist mobility essential after pushing work.", image:"", demo:"" },
          ],
          Saturday:  [
            { name:"Wall Handstand Hold", sets:5, reps:"15 sec",      desc:"Kick up with heels to wall. Get comfortable being inverted. Build hold time. Skill day — quality over speed.", image:"", demo:"https://www.youtube.com/results?search_query=handstand+against+wall+beginners" },
            { name:"L-Sit Prep",          sets:5, reps:"5 sec",       desc:"Hands on floor beside hips, press down and try to lift. Or tuck sit on two books. Builds pressing strength.", image:"", demo:"https://www.youtube.com/results?search_query=l+sit+beginners+floor" },
            { name:"Hollow Body Rock",    sets:3, reps:"10 reps",     desc:"Rock between hollow and arch positions. The fundamental gymnastics body awareness drill.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+arch+rock+gymnastics" },
            { name:"Shoulder Circles",    sets:2, reps:"10 each dir", desc:"Large shoulder circles forward and backward. Maintains shoulder health for push and pull work.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+circles+mobility" },
            { name:"Pike Stretch",        sets:3, reps:"60 sec",      desc:"Standing or seated, reach for toes. Hamstring flexibility essential for L-Sit and front lever.", image:"", demo:"https://www.youtube.com/results?search_query=pike+stretch+flexibility" },
            { name:"Hip Flexor Stretch",  sets:2, reps:"60 sec each", desc:"Low lunge. Press hips forward. Essential for squats, pistols, and handstand balance.", image:"", demo:"https://www.youtube.com/results?search_query=hip+flexor+stretch+lunge" },
            { name:"Max Rep Test",        sets:1, reps:"Monthly",     desc:"Test your current max: Push-Ups, Australian Rows, Squats. Record and compare monthly.", image:"", demo:"https://www.youtube.com/results?search_query=max+rep+test+calisthenics" },
            { name:"Rest and Reflect",    sets:1, reps:"",            desc:"Full body stretch. Celebrate your progress this week!", image:"", demo:"" },
          ],
        }},
        2: { name:"Intermediate", desc:"Weeks 9–20 · Master moves, begin skills", days: {
          Monday:    [
            { name:"Push-Ups",            sets:4, reps:"15–20 reps",  desc:"Full range bodyweight push-ups. When you hit 20 perfect reps consistently, progress to archer or diamond.", image:"", demo:"https://www.youtube.com/results?search_query=push+ups+proper+form" },
            { name:"Archer Push-Ups",     sets:3, reps:"8 each side", desc:"Wide hands. Shift weight to one arm while the other extends. Best progression toward one-arm push-up.", image:"", demo:"https://www.youtube.com/results?search_query=archer+push+ups+tutorial" },
            { name:"Diamond Push-Ups",    sets:3, reps:"10 reps",     desc:"Hands form diamond under chest. Intense tricep and inner chest. Keep elbows close throughout.", image:"", demo:"https://www.youtube.com/results?search_query=diamond+push+ups+form" },
            { name:"Pike Push-Ups",       sets:4, reps:"10 reps",     desc:"Downward dog, lower head toward floor. Building HSPU strength. Elevate feet on box for more vertical loading.", image:"", demo:"https://www.youtube.com/results?search_query=pike+push+ups+shoulder+press" },
            { name:"Pseudo Planche Lean", sets:3, reps:"15 sec",      desc:"High plank, hands turned out, lean body forward over hands. Arms straight. Builds planche foundation.", image:"", demo:"https://www.youtube.com/results?search_query=pseudo+planche+lean+calisthenics" },
            { name:"Plank Hold",          sets:3, reps:"60 sec",      desc:"Full forearm plank 60 seconds minimum. Add shoulder taps and hip dips for variety.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+60+seconds" },
            { name:"Hollow Body + Arch Rock", sets:3, reps:"10 reps", desc:"Rock between hollow and arch positions. Essential gymnastics body awareness drill.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+arch+rock+gymnastics" },
            { name:"Wrist Conditioning",  sets:2, reps:"3 min",       desc:"Finger push-ups, wrist push-ups, wrist circles. Protects your training longevity.", image:"", demo:"https://www.youtube.com/results?search_query=wrist+conditioning+calisthenics" },
          ],
          Tuesday:   [
            { name:"Pull-Ups",            sets:4, reps:"5–8 reps",   desc:"Full range pull-ups: dead hang to chin over bar. Work toward 10 clean reps before progressing.", image:"", demo:"https://www.youtube.com/results?search_query=pull+ups+proper+form" },
            { name:"Chest-to-Bar Pull-Ups",sets:3,reps:"5 reps",     desc:"Pull until chest touches bar. Builds explosive power needed for muscle-ups.", image:"", demo:"https://www.youtube.com/results?search_query=chest+to+bar+pull+ups" },
            { name:"L-Sit Pull-Ups",      sets:3, reps:"5 reps",     desc:"Hold L-sit position while performing pull-ups. Combines core and back strength.", image:"", demo:"https://www.youtube.com/results?search_query=l+sit+pull+ups+calisthenics" },
            { name:"Australian Row Elevated",sets:3,reps:"12 reps",  desc:"Feet elevated — more horizontal, increases load significantly.", image:"", demo:"https://www.youtube.com/results?search_query=feet+elevated+row+calisthenics" },
            { name:"Tuck Front Lever",    sets:3, reps:"5 sec",       desc:"Hang from bar, tuck knees, pull body horizontal. Keep arms straight. First step toward front lever.", image:"", demo:"https://www.youtube.com/results?search_query=tuck+front+lever+progression" },
            { name:"Active Dead Hang",    sets:3, reps:"30 sec",      desc:"Hang from bar, actively depress and retract scapulae. Not fully passive — maintain tension for shoulder health.", image:"", demo:"https://www.youtube.com/results?search_query=active+dead+hang+shoulder" },
            { name:"Commando Pull-Ups",   sets:3, reps:"8 reps",      desc:"Neutral grip, alternate bringing head to each side of bar. Builds unilateral pulling strength.", image:"", demo:"https://www.youtube.com/results?search_query=commando+pull+ups" },
            { name:"Lat/Bicep Stretch",   sets:1, reps:"2 min",       desc:"Lat stretch, bicep wall stretch, thoracic extension, child's pose.", image:"", demo:"" },
          ],
          Wednesday: [
            { name:"Air Squat",           sets:4, reps:"20 reps",     desc:"Full depth bodyweight squat. Heels flat, knees out. Aim for thighs below parallel.", image:"", demo:"https://www.youtube.com/results?search_query=air+squat+proper+form" },
            { name:"Bulgarian Split Squat",sets:3,reps:"10 each leg", desc:"Rear foot elevated on chair. Sink front leg until back knee nearly touches floor. Best pistol squat prep.", image:"", demo:"https://www.youtube.com/results?search_query=bulgarian+split+squat+calisthenics" },
            { name:"Single-Leg Glute Bridge",sets:3,reps:"12 each",  desc:"One leg extended, drive through heel. High glute and hamstring activation.", image:"", demo:"https://www.youtube.com/results?search_query=single+leg+glute+bridge" },
            { name:"Shrimp Squat Prep",   sets:3, reps:"8 each leg",  desc:"Stand on one leg, hold opposite ankle behind you. Squat down. Builds single-leg strength.", image:"", demo:"https://www.youtube.com/results?search_query=shrimp+squat+progression" },
            { name:"Nordic Curl Prep",    sets:3, reps:"5 reps",       desc:"Kneel, fix feet, lower body forward slowly (3-5 sec). Most effective hamstring builder without equipment.", image:"", demo:"https://www.youtube.com/results?search_query=nordic+curl+beginners" },
            { name:"Lunge to Balance",    sets:3, reps:"10 each",      desc:"Forward lunge, drive front knee up to balance on back leg. Builds single-leg stability.", image:"", demo:"https://www.youtube.com/results?search_query=lunge+to+balance+single+leg" },
            { name:"Single-Leg Calf Raise",sets:3,reps:"15 each",     desc:"Single-leg on step edge. Full range of motion.", image:"", demo:"https://www.youtube.com/results?search_query=single+leg+calf+raise+step" },
            { name:"Hip Flexor Stretch",  sets:2, reps:"60 sec each", desc:"Hip flexor, hamstring, quad, calf stretches.", image:"", demo:"" },
          ],
          Thursday:  [
            { name:"L-Sit Hold",          sets:5, reps:"5–10 sec",    desc:"Hands on parallel bars/floor/books. Extend legs horizontal. Build from 5 sec to 30 sec over weeks.", image:"", demo:"https://www.youtube.com/results?search_query=l+sit+progression+calisthenics" },
            { name:"Tuck L-Sit",          sets:5, reps:"10 sec",       desc:"Tuck knees to chest while supported on hands. Step between full L-Sit and floor support.", image:"", demo:"https://www.youtube.com/results?search_query=tuck+l+sit+calisthenics" },
            { name:"Dragon Flag Prep",    sets:3, reps:"5 reps",       desc:"On a bench, lower straight body slowly. Start with tucked version. One of the most challenging core exercises.", image:"", demo:"https://www.youtube.com/results?search_query=dragon+flag+beginners" },
            { name:"Hollow Body 30 sec",  sets:4, reps:"30 sec",       desc:"Perfect hollow body for 30 sec. Arms by ears, legs lifted, lower back flat.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+body+hold+30+seconds" },
            { name:"V-Ups",              sets:3, reps:"10 reps",       desc:"Arms overhead, simultaneously raise torso and legs. Intense hip flexor and core exercise.", image:"", demo:"https://www.youtube.com/results?search_query=v+ups+exercise+core" },
            { name:"Side Plank Hip Dip",  sets:3, reps:"10 each side", desc:"Side plank, lower hip to floor and raise back up. Dynamic core stability.", image:"", demo:"https://www.youtube.com/results?search_query=side+plank+hip+dip" },
            { name:"Windshield Wipers",   sets:3, reps:"8 reps",       desc:"Hang from bar, raise legs to 90°, rotate side to side. Advanced rotational core.", image:"", demo:"https://www.youtube.com/results?search_query=windshield+wipers+bar+core" },
            { name:"Recovery Stretching", sets:1, reps:"3 min",        desc:"Spinal twist, child's pose, deep breathing.", image:"", demo:"" },
          ],
          Friday:    [
            { name:"Push-Up Pyramid",     sets:5, reps:"1-2-3-4-5",   desc:"1 push-up, rest 10 sec, 2 push-ups, rest 20 sec, up to 5 then back down. Builds volume without fatigue.", image:"", demo:"https://www.youtube.com/results?search_query=push+up+pyramid" },
            { name:"Pull-Up Pyramid",     sets:5, reps:"1-2-3-4-5",   desc:"Same as push-up pyramid for pull-ups. The GTG method for rapid pull-up gains.", image:"", demo:"https://www.youtube.com/results?search_query=pull+up+pyramid" },
            { name:"Air Squats",          sets:4, reps:"20 reps",      desc:"Deep air squats, full range, controlled.", image:"", demo:"https://www.youtube.com/results?search_query=air+squat+calisthenics" },
            { name:"Dips",               sets:4, reps:"10 reps",       desc:"On parallel bars or two chairs. Lean slightly forward for chest, upright for triceps.", image:"", demo:"https://www.youtube.com/results?search_query=dips+parallel+bars+form" },
            { name:"Burpee with Push-Up", sets:3, reps:"10 reps",      desc:"Full burpee with a push-up in the plank position. Most complete conditioning exercise.", image:"", demo:"https://www.youtube.com/results?search_query=burpee+with+push+up" },
            { name:"Jump Squats",         sets:3, reps:"15 reps",      desc:"Explosive squats. Full depth, jump as high as possible. Develops power.", image:"", demo:"https://www.youtube.com/results?search_query=jump+squats+power" },
            { name:"Plank Circuit",       sets:3, reps:"45 sec each",  desc:"Forearm plank → side plank left → side plank right. Rest 15 sec between.", image:"", demo:"https://www.youtube.com/results?search_query=plank+variations+circuit" },
            { name:"Full Cool-Down",      sets:1, reps:"5 min",        desc:"Full body stretch and foam rolling.", image:"", demo:"" },
          ],
          Saturday:  [
            { name:"Handstand Progression",sets:5,reps:"20–30 sec",   desc:"Progress: wall handstand → chest-to-wall → back-to-wall → controlled entry. Work balance drills.", image:"", demo:"https://www.youtube.com/results?search_query=handstand+progression+wall" },
            { name:"Muscle-Up Prep",      sets:5, reps:"5 reps",       desc:"Explosive chest-to-bar pull-ups. Train at maximum effort. The power for muscle-up transition.", image:"", demo:"https://www.youtube.com/results?search_query=muscle+up+preparation+explosive" },
            { name:"Front Lever Holds",   sets:4, reps:"5 sec",        desc:"Tuck front lever. Keep arms straight, pull body to horizontal. Progress from two-legged tuck.", image:"", demo:"https://www.youtube.com/results?search_query=tuck+front+lever+holds" },
            { name:"Thoracic Extension",  sets:3, reps:"60 sec",       desc:"Foam roller perpendicular to spine. Opens thoracic for handstands and overhead pressing.", image:"", demo:"https://www.youtube.com/results?search_query=thoracic+extension+foam+roller" },
            { name:"Hamstring Stretch",   sets:3, reps:"45 sec each",  desc:"Slow, controlled hamstring stretches. Essential for L-Sit, front lever, hip extension.", image:"", demo:"https://www.youtube.com/results?search_query=hamstring+stretch+flexibility" },
            { name:"Wrist Conditioning",  sets:2, reps:"3 min",        desc:"Finger push-ups, rice bucket work. Prevents injuries at increased training load.", image:"", demo:"https://www.youtube.com/results?search_query=wrist+finger+conditioning" },
            { name:"Max Rep Test",        sets:1, reps:"Monthly",      desc:"Test max pull-ups, push-ups, dips. Compare to last month.", image:"", demo:"https://www.youtube.com/results?search_query=calisthenics+strength+test" },
            { name:"Rest and Reflect",    sets:1, reps:"",             desc:"Plan next week's skill work priorities.", image:"", demo:"" },
          ],
        }},
        3: { name:"Advanced", desc:"Weeks 21+ · Elite skills and performance", days: {
          Monday:    [
            { name:"One-Arm Push-Up Progression",sets:4,reps:"5 each side",desc:"Archer → one-arm with wide leg stance → full one-arm. The pinnacle of push strength.", image:"", demo:"https://www.youtube.com/results?search_query=one+arm+push+up+progression" },
            { name:"Handstand Push-Ups",  sets:4, reps:"5 reps",      desc:"Wall-assisted full range HSPU. Head to floor and back up. Incredible shoulder and tricep strength.", image:"", demo:"https://www.youtube.com/results?search_query=handstand+push+ups+wall" },
            { name:"Planche Tuck Hold",   sets:5, reps:"5–10 sec",    desc:"From handstand lean, tuck knees to chest and balance on arms. Most advanced pushing skill.", image:"", demo:"https://www.youtube.com/results?search_query=tuck+planche+hold+calisthenics" },
            { name:"Pseudo Planche Push-Ups",sets:4,reps:"10 reps",   desc:"Hands turned out, extreme forward lean. Develops planche pressing strength.", image:"", demo:"https://www.youtube.com/results?search_query=pseudo+planche+push+ups+advanced" },
            { name:"Ring Push-Ups",       sets:4, reps:"12 reps",     desc:"Gymnastic rings at low height. Full range push-ups on unstable surface. Extreme stabiliser strength.", image:"", demo:"https://www.youtube.com/results?search_query=ring+push+ups+gymnastics" },
            { name:"Planche Lean Elevated",sets:4,reps:"15 sec",      desc:"Feet elevated on box, full planche lean. Develops the pulling strength needed to hold a planche.", image:"", demo:"https://www.youtube.com/results?search_query=planche+lean+elevated" },
            { name:"Hollow Body Advanced",sets:4, reps:"45 sec",      desc:"Perfect hollow body 45 sec. Arms by ears, legs extended fully. No back arching allowed.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+body+hold+advanced" },
            { name:"Shoulder Mobility",   sets:1, reps:"5 min",       desc:"Full shoulder mobility routine, chest and wrist stretches.", image:"", demo:"" },
          ],
          Tuesday:   [
            { name:"Muscle-Up",           sets:5, reps:"3–5 reps",    desc:"From dead hang, explosive pull and transition over the bar. Power + technique. The most well-known calisthenics skill.", image:"", demo:"https://www.youtube.com/results?search_query=muscle+up+tutorial+form" },
            { name:"Chest-to-Bar Pull-Ups",sets:4,reps:"8 reps",      desc:"Explosive chest-to-bar. Maintains power for muscle-up consistency.", image:"", demo:"https://www.youtube.com/results?search_query=chest+to+bar+pull+ups" },
            { name:"Front Lever Progression",sets:5,reps:"5–8 sec",  desc:"Straddle or one-leg front lever. Progress toward full by extending one leg at a time.", image:"", demo:"https://www.youtube.com/results?search_query=front+lever+progression+advanced" },
            { name:"Weighted Pull-Ups",   sets:4, reps:"6 reps",      desc:"Add weight via belt or vest. Builds absolute strength needed for one-arm pull-up prep.", image:"", demo:"https://www.youtube.com/results?search_query=weighted+pull+ups+technique" },
            { name:"Back Lever Hold",     sets:4, reps:"5 sec",       desc:"Hang facing down, keep body horizontal with arms straight behind. Intermediate skill.", image:"", demo:"https://www.youtube.com/results?search_query=back+lever+hold+calisthenics" },
            { name:"One-Arm Dead Hang",   sets:3, reps:"10 sec each", desc:"Single-arm hang with assistance from other hand on wrist. Builds toward one-arm pull-up.", image:"", demo:"https://www.youtube.com/results?search_query=one+arm+dead+hang" },
            { name:"Ring Rows",           sets:3, reps:"12 reps",     desc:"Gymnastic ring rows. Extreme difficulty for horizontal pulling due to instability.", image:"", demo:"https://www.youtube.com/results?search_query=gymnastic+ring+rows" },
            { name:"Lat/Shoulder Stretch",sets:1, reps:"3 min",       desc:"Lat, bicep, shoulder stretches. Thoracic extension.", image:"", demo:"" },
          ],
          Wednesday: [
            { name:"Pistol Squat",        sets:5, reps:"5 each leg",  desc:"Single-leg squat to full depth, other leg extended forward. The pinnacle of lower body calisthenics.", image:"", demo:"https://www.youtube.com/results?search_query=pistol+squat+tutorial" },
            { name:"Shrimp Squat",        sets:4, reps:"8 each leg",  desc:"Standing single-leg squat, holding back foot. Knee touches floor at bottom.", image:"", demo:"https://www.youtube.com/results?search_query=shrimp+squat+advanced" },
            { name:"Nordic Curl",         sets:3, reps:"5 reps",       desc:"Kneel, lower body forward as slowly as possible. Most effective hamstring exercise without equipment.", image:"", demo:"https://www.youtube.com/results?search_query=nordic+curl+advanced" },
            { name:"Jump Squat to Box",   sets:4, reps:"10 reps",      desc:"Explosive jump squat onto raised surface. Builds power and coordination.", image:"", demo:"https://www.youtube.com/results?search_query=box+jump+squat" },
            { name:"Single-Leg Calf Raise",sets:4,reps:"20 each",     desc:"On a step, full range single-leg calf raise. Add weight progressively.", image:"", demo:"https://www.youtube.com/results?search_query=single+leg+calf+raise+advanced" },
            { name:"Sissy Squat",         sets:3, reps:"10 reps",      desc:"Stand on toes, lean back, bend knees only. Advanced quad isolation.", image:"", demo:"https://www.youtube.com/results?search_query=sissy+squat+quad" },
            { name:"Lunge Matrix",        sets:3, reps:"8 each dir",   desc:"Forward, lateral, reverse, rotational lunge. Multi-directional leg strength.", image:"", demo:"https://www.youtube.com/results?search_query=lunge+matrix+exercise" },
            { name:"Leg Stretches",       sets:1, reps:"3 min",        desc:"Hamstring, hip flexor, glute, piriformis stretches.", image:"", demo:"" },
          ],
          Thursday:  [
            { name:"L-Sit Hold",          sets:5, reps:"10–30 sec",   desc:"Full L-sit with extended legs on parallettes. Build from 10 to 30 sec holds.", image:"", demo:"https://www.youtube.com/results?search_query=l+sit+full+30+seconds" },
            { name:"Dragon Flag",         sets:4, reps:"5 reps",       desc:"Full dragon flag with straight body. Lower to within an inch of bench, return. Bruce Lee's signature.", image:"", demo:"https://www.youtube.com/results?search_query=dragon+flag+full+tutorial" },
            { name:"Straddle L-Sit",      sets:4, reps:"10 sec",       desc:"L-sit with legs straddled wide. More hip flexor strength and mobility. Precursor to straddle planche.", image:"", demo:"https://www.youtube.com/results?search_query=straddle+l+sit+calisthenics" },
            { name:"Hanging L-Sit",       sets:3, reps:"5 sec",        desc:"L-sit while hanging from bar. Combines core and grip strength.", image:"", demo:"https://www.youtube.com/results?search_query=hanging+l+sit+bar" },
            { name:"Windshield Wipers",   sets:3, reps:"10 reps",      desc:"Hang, legs extended horizontal, rotate full range. Rotational core power.", image:"", demo:"https://www.youtube.com/results?search_query=windshield+wipers+bar+advanced" },
            { name:"Ab Wheel Rollout",    sets:3, reps:"10 reps",      desc:"From standing, roll out to full extension, return using core. Extreme anti-extension strength.", image:"", demo:"https://www.youtube.com/results?search_query=ab+wheel+rollout+standing" },
            { name:"V-Sit Progress",      sets:4, reps:"5 sec",        desc:"L-sit progressing toward V-sit (legs angled above horizontal). Extreme compression strength.", image:"", demo:"https://www.youtube.com/results?search_query=v+sit+calisthenics" },
            { name:"Compression Breathing",sets:1,reps:"3 min",        desc:"Recovery stretches and compression breathing.", image:"", demo:"" },
          ],
          Friday:    [
            { name:"Calisthenics Complex", sets:4, reps:"1 round",    desc:"1 muscle-up → 3 pull-ups → 5 push-ups → 7 squats → 9 dips. Rest 2 min. Total body strength endurance.", image:"", demo:"https://www.youtube.com/results?search_query=calisthenics+complex+workout" },
            { name:"Ring Dips",           sets:4, reps:"8 reps",       desc:"Gymnastic ring dips. Full range, control instability. Harder than bar dips.", image:"", demo:"https://www.youtube.com/results?search_query=ring+dips+gymnastics" },
            { name:"Ring Pull-Ups",       sets:4, reps:"8 reps",       desc:"Pull-ups on gymnastic rings. Free rotation demands more stabiliser activation.", image:"", demo:"https://www.youtube.com/results?search_query=ring+pull+ups+gymnastics" },
            { name:"Pistol Squat Volume", sets:3, reps:"5 each leg",   desc:"Quality pistol squats. Control up and down. Volume for the most demanding lower body skill.", image:"", demo:"https://www.youtube.com/results?search_query=pistol+squat+volume" },
            { name:"HSPU Negatives",      sets:3, reps:"5 reps",       desc:"From full lockout handstand, lower slowly (5 sec). Builds eccentric strength for harder HSPU.", image:"", demo:"https://www.youtube.com/results?search_query=handstand+push+up+negatives" },
            { name:"Planche Lean on Rings",sets:4,reps:"10 sec",       desc:"Rings at waist height, extreme forward lean. Transition to ring planche training.", image:"", demo:"https://www.youtube.com/results?search_query=planche+lean+rings" },
            { name:"Freestanding Handstand",sets:10,reps:"30 sec attempts",desc:"10 attempts at freestanding handstand. Skill practice — quality over quantity. Work on balance adjustments.", image:"", demo:"https://www.youtube.com/results?search_query=freestanding+handstand+balance" },
            { name:"Full Mobility",       sets:1, reps:"10 min",       desc:"Shoulder circles, hip flexors, thoracic extension.", image:"", demo:"" },
          ],
          Saturday:  [
            { name:"Handstand Session",   sets:1, reps:"15 min",       desc:"Wall → chest-to-wall → back-to-wall → freestanding. The foundation of elite calisthenics.", image:"", demo:"https://www.youtube.com/results?search_query=handstand+skill+session" },
            { name:"Front Lever Session", sets:1, reps:"10 min",       desc:"Tuck → advanced tuck → straddle → one-leg → full. Hold each for max time.", image:"", demo:"https://www.youtube.com/results?search_query=front+lever+skill+session" },
            { name:"Planche Session",     sets:1, reps:"10 min",       desc:"Lean → tuck → advanced tuck → straddle. Needs months of consistent work.", image:"", demo:"https://www.youtube.com/results?search_query=planche+skill+session" },
            { name:"Muscle-Up Refinement",sets:5, reps:"3 reps",       desc:"Focus on technique: false grip, explosive pull, smooth transition. Quality only.", image:"", demo:"https://www.youtube.com/results?search_query=muscle+up+technique" },
            { name:"Full Flexibility",    sets:1, reps:"20 min",       desc:"Pancake stretch, splits progress, shoulder flexibility, thoracic extension.", image:"", demo:"https://www.youtube.com/results?search_query=calisthenics+flexibility+full+body" },
            { name:"Wrist and Finger Work",sets:2,reps:"5 min",        desc:"Advanced wrist conditioning. Protects your training for years.", image:"", demo:"https://www.youtube.com/results?search_query=advanced+wrist+conditioning+gymnastics" },
            { name:"Max Rep Test",        sets:1, reps:"Monthly",      desc:"Test muscle-ups, HSPU, pistol squats, L-sit time. Document everything.", image:"", demo:"https://www.youtube.com/results?search_query=calisthenics+advanced+test" },
            { name:"Rest and Plan",       sets:1, reps:"",             desc:"Celebrate progress. Plan next week's focus skills.", image:"", demo:"" },
          ],
        }},
      }
    };

  // ── RUNNING PLANS + SKILL TREE + CHALLENGE + HYDRATION + DIET ────

  // ── CALISTHENICS WARMUP & COOLDOWN ───────────────────────────────
  D.warmups.calisthenics = [
    { name:"Calisthenics Warm-Up", sets:1, reps:"5 min", desc:"Jumping jacks 30 sec → arm circles 30 sec each → hip circles 20 reps → wrist prep 30 sec. Activates all joints before bodyweight training.", image:"", demo:"https://www.youtube.com/results?search_query=calisthenics+warm+up+routine", tag:"warmup" },
  ];
  D.cooldowns.calisthenics = [
    { name:"Calisthenics Cool-Down", sets:1, reps:"5 min", desc:"Wrist shake 30 sec → chest stretch 45 sec → lat stretch 30 sec each → quad stretch 30 sec each → hamstring stretch 45 sec each → child's pose 90 sec.", image:"", demo:"https://www.youtube.com/results?search_query=calisthenics+cool+down+stretching", tag:"cooldown" },
  ];

  // ── RUNNING WARMUP & COOLDOWN ─────────────────────────────────────
  D.warmups.running = [
    { name:"Pre-Run Warm-Up", sets:1, reps:"5 min", desc:"Brisk walk 2 min → slow high knees 30 sec → ankle circles 10 each → hip flexor lunge 30 sec each → leg swings 10 each.", image:"", demo:"https://www.youtube.com/results?search_query=running+warm+up+routine", tag:"warmup" },
  ];
  D.cooldowns.running = [
    { name:"Post-Run Cool-Down", sets:1, reps:"5 min", desc:"Easy walk 3 min → standing calf stretch 45 sec each → quad stretch 30 sec each → seated hamstring stretch 60 sec each.", image:"", demo:"https://www.youtube.com/results?search_query=post+run+cool+down+stretches", tag:"cooldown" },
  ];

  // ── FULL RUNNING PLANS (replacing minimal deployed versions) ─────
  D.running = {
    plans: {
      "5K":  { color:"#43a05a", emoji:"🏃",   weeks:6,  desc:"Beginner-friendly. Build from 2km to 5km in 6 weeks.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:2,dur:20,desc:"Very easy pace. Hold a conversation. Just get moving."},
        {week:1,day:2,type:"Run/Walk",dist:2,dur:25,desc:"Run 2 min, walk 1 min. Repeat 6 times."},
        {week:1,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Rest or light cross-training."},
        {week:1,day:4,type:"Easy Run",dist:2,dur:20,desc:"Same as Day 1. Easy pace. Build the habit."},
        {week:1,day:5,type:"Rest",dist:0,dur:0,desc:"Full rest day."},
        {week:1,day:6,type:"Long Run",dist:3,dur:30,desc:"Your longest run this week. Slow and steady."},
        {week:1,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy 30-minute walk."},
        {week:2,day:1,type:"Easy Run",dist:2.5,dur:25,desc:"Slightly longer. Keep it conversational."},
        {week:2,day:2,type:"Run/Walk",dist:2.5,dur:28,desc:"Run 3 min, walk 1 min. Repeat 6 times."},
        {week:2,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Light cross-training or full rest."},
        {week:2,day:4,type:"Easy Run",dist:2.5,dur:25,desc:"Easy 2.5km. Focus on relaxed arms."},
        {week:2,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day."},
        {week:2,day:6,type:"Long Run",dist:3.5,dur:35,desc:"3.5km continuous if possible. Walk breaks fine."},
        {week:2,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Gentle walk."},
        {week:3,day:1,type:"Easy Run",dist:3,dur:28,desc:"3km easy."},
        {week:3,day:2,type:"Run/Walk Intervals",dist:3,dur:30,desc:"Run 4 min, walk 1 min. Repeat 5 times."},
        {week:3,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Cross-training or rest."},
        {week:3,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Try to run whole thing without walking."},
        {week:3,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest."},
        {week:3,day:6,type:"Long Run",dist:4,dur:40,desc:"Your first 4km! Take it slow."},
        {week:3,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk."},
        {week:4,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km."},
        {week:4,day:2,type:"Intervals",dist:3,dur:30,desc:"6 x 1 min fast, 2 min easy jog."},
        {week:4,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Rest or cross-training."},
        {week:4,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km recovery run after intervals."},
        {week:4,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day."},
        {week:4,day:6,type:"Long Run",dist:4.5,dur:45,desc:"4.5km. Almost at your goal distance!"},
        {week:4,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"30-minute walk."},
        {week:5,day:1,type:"Easy Run",dist:3.5,dur:33,desc:"Easy 3.5km."},
        {week:5,day:2,type:"Intervals",dist:3,dur:30,desc:"8 x 1 min fast, 90 sec easy."},
        {week:5,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Light cross-training or rest."},
        {week:5,day:4,type:"Easy Run",dist:3.5,dur:33,desc:"Easy 3.5km."},
        {week:5,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day."},
        {week:5,day:6,type:"Long Run",dist:5,dur:50,desc:"YOUR FIRST 5K! Run the full distance!"},
        {week:5,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk. Celebrate!"},
        {week:6,day:1,type:"Easy Run",dist:3,dur:28,desc:"Short easy run to keep legs fresh."},
        {week:6,day:2,type:"Run/Walk",dist:2,dur:20,desc:"Very easy 20 mins."},
        {week:6,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or full rest."},
        {week:6,day:4,type:"Easy Run",dist:2,dur:18,desc:"15-20 min shakeout."},
        {week:6,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Sleep early."},
        {week:6,day:6,type:"RACE DAY! 🏆",dist:5,dur:0,desc:"THIS IS IT! Start easy, finish strong!"},
        {week:6,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Post-race recovery. You are a 5K runner!"},
      ]},
      "10K": { color:"#1e88e5", emoji:"🏃‍♂️", weeks:8, desc:"For runners who can run 5K. Double the distance in 8 weeks.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:4,dur:38,desc:"Comfortable 4km base run."},
        {week:1,day:2,type:"Speed Workout",dist:4,dur:40,desc:"6 x 400m at 5K pace with 200m jog recovery."},
        {week:1,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or strength training."},
        {week:1,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min comfortably hard, 10 min easy."},
        {week:1,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day."},
        {week:1,day:6,type:"Long Run",dist:6,dur:58,desc:"First long run. Easy steady pace."},
        {week:1,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Very easy 2km."},
        {week:2,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km."},
        {week:2,day:2,type:"Speed Workout",dist:4.5,dur:45,desc:"8 x 400m at 5K pace."},
        {week:2,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest."},
        {week:2,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy."},
        {week:2,day:5,type:"Rest",dist:0,dur:0,desc:"Rest."},
        {week:2,day:6,type:"Long Run",dist:7,dur:67,desc:"7km long run."},
        {week:2,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy 2km."},
        {week:3,day:1,type:"Easy Run",dist:5,dur:47,desc:"5km easy."},
        {week:3,day:2,type:"Speed Workout",dist:5,dur:50,desc:"10 x 400m at 5K pace."},
        {week:3,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength."},
        {week:3,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 25 min tempo, 5 min cool-down."},
        {week:3,day:5,type:"Rest",dist:0,dur:0,desc:"Full rest."},
        {week:3,day:6,type:"Long Run",dist:8,dur:76,desc:"8km. A big milestone!"},
        {week:3,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy recovery."},
        {week:4,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Cutback week."},
        {week:4,day:2,type:"Speed Workout",dist:4,dur:40,desc:"6 x 400m. Cutback volume."},
        {week:4,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or mobility."},
        {week:4,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min tempo, 10 min easy."},
        {week:4,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Cutback week."},
        {week:4,day:6,type:"Long Run",dist:7,dur:67,desc:"7km cutback long run."},
        {week:4,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy jog."},
        {week:5,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Back to building!"},
        {week:5,day:2,type:"Speed Workout",dist:5,dur:50,desc:"5 x 800m at 5K pace."},
        {week:5,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Core and glutes."},
        {week:5,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 30 min tempo, 5 min easy."},
        {week:5,day:5,type:"Rest",dist:0,dur:0,desc:"Rest."},
        {week:5,day:6,type:"Long Run",dist:9,dur:86,desc:"9km! Nearly at race distance."},
        {week:5,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy 2km."},
        {week:6,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Peak training week!"},
        {week:6,day:2,type:"Speed Workout",dist:5,dur:52,desc:"6 x 800m at 5K pace."},
        {week:6,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or light strength."},
        {week:6,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 30 min tempo, 10 min easy."},
        {week:6,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Peak week done."},
        {week:6,day:6,type:"Long Run",dist:10,dur:95,desc:"FIRST 10K! Race day just 2 weeks away!"},
        {week:6,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy jog. You just ran 10K!"},
        {week:7,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper week."},
        {week:7,day:2,type:"Speed Workout",dist:3,dur:30,desc:"4 x 400m at race pace."},
        {week:7,day:3,type:"Rest/Strength",dist:0,dur:20,desc:"Light stretching."},
        {week:7,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min tempo, 10 min easy."},
        {week:7,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Trust your training."},
        {week:7,day:6,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Last longer run."},
        {week:7,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Short easy jog."},
        {week:8,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Race week."},
        {week:8,day:2,type:"Strides",dist:2,dur:20,desc:"Easy 2km with 4 x 20-sec strides."},
        {week:8,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light or rest."},
        {week:8,day:4,type:"Easy Run",dist:2,dur:18,desc:"Easy shakeout."},
        {week:8,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Sleep early."},
        {week:8,day:6,type:"RACE DAY! 🏆",dist:10,dur:0,desc:"10K RACE DAY! Start easy, finish strong!"},
        {week:8,day:7,type:"Recovery Jog",dist:1,dur:10,desc:"Easy walk. You are a 10K runner!"},
      ]},
      "HM":  { color:"#fb8c00", emoji:"🏃‍♀️", weeks:12, desc:"Half Marathon 21.1km. For runners with a solid 10K base.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km base run."},
        {week:1,day:2,type:"Speed Intervals",dist:5,dur:50,desc:"8 x 400m at 5K pace."},
        {week:1,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training."},
        {week:1,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 25 min tempo, 10 min easy."},
        {week:1,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy recovery run."},
        {week:1,day:6,type:"Long Run",dist:10,dur:95,desc:"10km long run base."},
        {week:1,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk."},
        {week:2,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:2,day:2,type:"Speed Intervals",dist:6,dur:58,desc:"10 x 400m at 5K pace."},
        {week:2,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength."},
        {week:2,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 30 min tempo, 10 min easy."},
        {week:2,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:2,day:6,type:"Long Run",dist:12,dur:114,desc:"12km long run."},
        {week:2,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest."},
        {week:3,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km."},
        {week:3,day:2,type:"Speed Intervals",dist:6,dur:60,desc:"6 x 800m at 10K pace."},
        {week:3,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Core work."},
        {week:3,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 35 min tempo."},
        {week:3,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:3,day:6,type:"Long Run",dist:14,dur:133,desc:"14km. Bring water."},
        {week:3,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Eat well."},
        {week:4,day:1,type:"Easy Run",dist:5,dur:47,desc:"Cutback week."},
        {week:4,day:2,type:"Speed Intervals",dist:4,dur:40,desc:"6 x 400m. Reduced volume."},
        {week:4,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Mobility focus."},
        {week:4,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo."},
        {week:4,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km."},
        {week:4,day:6,type:"Long Run",dist:10,dur:95,desc:"10km cutback."},
        {week:4,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest."},
        {week:5,day:1,type:"Easy Run",dist:6,dur:56,desc:"Back to building!"},
        {week:5,day:2,type:"Speed Intervals",dist:7,dur:68,desc:"8 x 800m at 10K pace."},
        {week:5,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Hip and glute work."},
        {week:5,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 40 min tempo."},
        {week:5,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:5,day:6,type:"Long Run",dist:16,dur:152,desc:"16km! Well into HM territory."},
        {week:5,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest properly."},
        {week:6,day:1,type:"Easy Run",dist:6,dur:56,desc:"Halfway through!"},
        {week:6,day:2,type:"Speed Intervals",dist:7,dur:70,desc:"10 x 800m at 10K pace."},
        {week:6,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Maintain muscle balance."},
        {week:6,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 40 min tempo."},
        {week:6,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy recovery."},
        {week:6,day:6,type:"Long Run",dist:18,dur:171,desc:"18km. Amazing!"},
        {week:6,day:7,type:"Recovery",dist:0,dur:30,desc:"18km demands serious recovery."},
        {week:7,day:1,type:"Easy Run",dist:5,dur:47,desc:"Second cutback week."},
        {week:7,day:2,type:"Speed Intervals",dist:4,dur:40,desc:"6 x 400m. Short and sharp."},
        {week:7,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength."},
        {week:7,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo."},
        {week:7,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km."},
        {week:7,day:6,type:"Long Run",dist:12,dur:114,desc:"12km cutback."},
        {week:7,day:7,type:"Recovery",dist:0,dur:30,desc:"Fitness consolidating."},
        {week:8,day:1,type:"Easy Run",dist:6,dur:56,desc:"Final big block!"},
        {week:8,day:2,type:"Speed Intervals",dist:8,dur:78,desc:"10 x 800m at HM goal pace."},
        {week:8,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Last heavy session."},
        {week:8,day:4,type:"Tempo Run",dist:9,dur:85,desc:"45 min at HM pace."},
        {week:8,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:8,day:6,type:"Long Run",dist:19,dur:180,desc:"19km peak long run!"},
        {week:8,day:7,type:"Recovery",dist:0,dur:30,desc:"19km extraordinary — recover fully."},
        {week:9,day:1,type:"Easy Run",dist:6,dur:56,desc:"Maintaining fitness."},
        {week:9,day:2,type:"Speed Intervals",dist:6,dur:60,desc:"8 x 800m at 10K pace."},
        {week:9,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Core and mobility."},
        {week:9,day:4,type:"Tempo Run",dist:8,dur:76,desc:"35 min tempo."},
        {week:9,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:9,day:6,type:"Long Run",dist:16,dur:152,desc:"16km. Practice race nutrition."},
        {week:9,day:7,type:"Recovery",dist:0,dur:30,desc:"Three weeks to race day!"},
        {week:10,day:1,type:"Easy Run",dist:5,dur:47,desc:"Volume easing."},
        {week:10,day:2,type:"Speed Intervals",dist:5,dur:50,desc:"6 x 800m at HM pace."},
        {week:10,day:3,type:"Rest/Strength",dist:0,dur:20,desc:"Light strength."},
        {week:10,day:4,type:"Tempo Run",dist:7,dur:66,desc:"30 min at HM pace."},
        {week:10,day:5,type:"Easy Run",dist:4,dur:38,desc:"Taper beginning."},
        {week:10,day:6,type:"Long Run",dist:14,dur:133,desc:"Last substantial long run."},
        {week:10,day:7,type:"Recovery",dist:0,dur:30,desc:"Fitness locked in!"},
        {week:11,day:1,type:"Easy Run",dist:4,dur:38,desc:"Taper week."},
        {week:11,day:2,type:"Speed Intervals",dist:4,dur:38,desc:"4 x 800m at race pace."},
        {week:11,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light."},
        {week:11,day:4,type:"Tempo Run",dist:5,dur:47,desc:"20 min at HM pace."},
        {week:11,day:5,type:"Rest",dist:0,dur:0,desc:"Race week next. You are ready."},
        {week:11,day:6,type:"Easy Run",dist:6,dur:56,desc:"Last medium run."},
        {week:11,day:7,type:"Recovery",dist:0,dur:20,desc:"Read race plan tonight."},
        {week:12,day:1,type:"Easy Run",dist:3,dur:28,desc:"Race week. Keep legs fresh."},
        {week:12,day:2,type:"Strides",dist:2,dur:20,desc:"Easy 2km with 4 x 20-sec strides."},
        {week:12,day:3,type:"Rest/Cross-train",dist:0,dur:15,desc:"Very light."},
        {week:12,day:4,type:"Easy Run",dist:2,dur:18,desc:"Easy shakeout."},
        {week:12,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Sleep by 10pm."},
        {week:12,day:6,type:"RACE DAY! 🏆",dist:21.1,dur:0,desc:"HALF MARATHON! Respect the distance, run your race!"},
        {week:12,day:7,type:"Recovery",dist:0,dur:30,desc:"You ran a half marathon!"},
      ]},
      "FM":  { color:"#e53935", emoji:"🏅", weeks:20, desc:"Full Marathon 42.2km. Serious 20-week training programme.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Marathon training begins."},
        {week:1,day:2,type:"Speed/Hill Training",dist:6,dur:60,desc:"Hill repeats - 8 x 90-sec uphill."},
        {week:1,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy to moderate."},
        {week:1,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength - squats, lunges, core."},
        {week:1,day:5,type:"Tempo Run",dist:8,dur:75,desc:"30 min at marathon pace."},
        {week:1,day:6,type:"Long Run",dist:16,dur:148,desc:"16km long run. Very easy pace."},
        {week:1,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Very easy 3km."},
        {week:2,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km."},
        {week:2,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"10 x 90-sec hill repeats."},
        {week:2,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km moderate."},
        {week:2,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Single-leg and hip strengthening."},
        {week:2,day:5,type:"Tempo Run",dist:9,dur:85,desc:"35 min at marathon pace."},
        {week:2,day:6,type:"Long Run",dist:18,dur:167,desc:"18km. Train your gut with gels!"},
        {week:2,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy recovery."},
        {week:3,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km."},
        {week:3,day:2,type:"Speed/Hill Training",dist:7,dur:70,desc:"8 x 2-min hill repeats."},
        {week:3,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km medium effort."},
        {week:3,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Core endurance."},
        {week:3,day:5,type:"Tempo Run",dist:10,dur:95,desc:"40 min at marathon pace."},
        {week:3,day:6,type:"Long Run",dist:20,dur:185,desc:"20km! Major milestone."},
        {week:3,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km."},
        {week:4,day:1,type:"Easy Run",dist:6,dur:56,desc:"Cutback week."},
        {week:4,day:2,type:"Speed/Hill Training",dist:5,dur:50,desc:"6 x 90-sec hills."},
        {week:4,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy."},
        {week:4,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Mobility focus."},
        {week:4,day:5,type:"Tempo Run",dist:8,dur:75,desc:"25 min at marathon pace."},
        {week:4,day:6,type:"Long Run",dist:14,dur:130,desc:"14km cutback long run."},
        {week:4,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km."},
        {week:5,day:1,type:"Easy Run",dist:7,dur:66,desc:"Back to building!"},
        {week:5,day:2,type:"Speed/Hill Training",dist:8,dur:78,desc:"10 x 2-min hill repeats."},
        {week:5,day:3,type:"Medium Run",dist:11,dur:105,desc:"11km moderate."},
        {week:5,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Don't skip strength."},
        {week:5,day:5,type:"Tempo Run",dist:11,dur:104,desc:"45 min marathon pace."},
        {week:5,day:6,type:"Long Run",dist:22,dur:204,desc:"22km. Practice race nutrition."},
        {week:5,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy recovery."},
        {week:6,day:1,type:"Easy Run",dist:7,dur:66,desc:"Aerobic base stronger."},
        {week:6,day:2,type:"Speed/Hill Training",dist:8,dur:80,desc:"4 x 2km at 10K pace."},
        {week:6,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km moderate."},
        {week:6,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Posterior chain work."},
        {week:6,day:5,type:"Tempo Run",dist:11,dur:104,desc:"45 min at marathon pace."},
        {week:6,day:6,type:"Long Run",dist:24,dur:222,desc:"24km. Four gels!"},
        {week:6,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km."},
        {week:7,day:1,type:"Easy Run",dist:7,dur:66,desc:"Building toward peak."},
        {week:7,day:2,type:"Speed/Hill Training",dist:9,dur:88,desc:"5 x 2km at 10K pace."},
        {week:7,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km."},
        {week:7,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Halfway to race day!"},
        {week:7,day:5,type:"Tempo Run",dist:12,dur:114,desc:"50 min at marathon pace."},
        {week:7,day:6,type:"Long Run",dist:25,dur:231,desc:"25km. Every step counts!"},
        {week:7,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy recovery."},
        {week:8,day:1,type:"Easy Run",dist:6,dur:56,desc:"Second cutback week."},
        {week:8,day:2,type:"Speed/Hill Training",dist:6,dur:60,desc:"6 x 90-sec hills."},
        {week:8,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km easy."},
        {week:8,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Extra mobility."},
        {week:8,day:5,type:"Tempo Run",dist:8,dur:75,desc:"30 min at marathon pace."},
        {week:8,day:6,type:"Long Run",dist:18,dur:167,desc:"18km cutback."},
        {week:8,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km."},
        {week:9,day:1,type:"Easy Run",dist:8,dur:76,desc:"Fresh from cutback!"},
        {week:9,day:2,type:"Speed/Hill Training",dist:9,dur:90,desc:"6 x 2km at 10K pace."},
        {week:9,day:3,type:"Medium Run",dist:13,dur:124,desc:"13km moderate."},
        {week:9,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Last chance for heavy strength."},
        {week:9,day:5,type:"Tempo Run",dist:13,dur:123,desc:"55 min marathon pace."},
        {week:9,day:6,type:"Long Run",dist:27,dur:250,desc:"27km. You are a long-distance runner!"},
        {week:9,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:10,day:1,type:"Easy Run",dist:8,dur:76,desc:"Deep in peak training."},
        {week:10,day:2,type:"Speed/Hill Training",dist:10,dur:98,desc:"3 x 5km at goal pace."},
        {week:10,day:3,type:"Medium Run",dist:13,dur:124,desc:"13km moderate."},
        {week:10,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Visualize the finish line."},
        {week:10,day:5,type:"Tempo Run",dist:13,dur:123,desc:"55 min at marathon goal pace."},
        {week:10,day:6,type:"Long Run",dist:29,dur:268,desc:"29km. Peak long run!"},
        {week:10,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km."},
        {week:11,day:1,type:"Easy Run",dist:8,dur:76,desc:"Approaching final build."},
        {week:11,day:2,type:"Speed/Hill Training",dist:9,dur:90,desc:"6 x 2km at 10K pace."},
        {week:11,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km."},
        {week:11,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Prevents late-plan injuries."},
        {week:11,day:5,type:"Tempo Run",dist:12,dur:114,desc:"50 min marathon pace."},
        {week:11,day:6,type:"Long Run",dist:30,dur:278,desc:"30km — LONGEST RUN EVER!"},
        {week:11,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. Feel phenomenally proud."},
        {week:12,day:1,type:"Easy Run",dist:7,dur:66,desc:"Third cutback!"},
        {week:12,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"8 x 90-sec hills."},
        {week:12,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km easy."},
        {week:12,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Visualize success."},
        {week:12,day:5,type:"Tempo Run",dist:9,dur:85,desc:"35 min marathon pace."},
        {week:12,day:6,type:"Long Run",dist:20,dur:185,desc:"20km cutback."},
        {week:12,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Eight weeks to race day."},
        {week:13,day:1,type:"Easy Run",dist:8,dur:76,desc:"Final peak phase."},
        {week:13,day:2,type:"Speed/Hill Training",dist:10,dur:98,desc:"4 x 5km at marathon goal pace."},
        {week:13,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km moderate."},
        {week:13,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Consistency brought you here."},
        {week:13,day:5,type:"Tempo Run",dist:13,dur:123,desc:"55 min at marathon goal pace."},
        {week:13,day:6,type:"Long Run",dist:32,dur:296,desc:"32km. TRUE PEAK LONG RUN. YOU LEGEND!"},
        {week:13,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. Marathon is within reach!"},
        {week:14,day:1,type:"Easy Run",dist:8,dur:76,desc:"Gradual volume reduction."},
        {week:14,day:2,type:"Speed/Hill Training",dist:9,dur:88,desc:"6 x 2km at 10K pace."},
        {week:14,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km."},
        {week:14,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Entering pre-taper phase."},
        {week:14,day:5,type:"Tempo Run",dist:11,dur:104,desc:"45 min marathon pace."},
        {week:14,day:6,type:"Long Run",dist:28,dur:259,desc:"28km. Last very long run."},
        {week:14,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Hardest training is behind you."},
        {week:15,day:1,type:"Easy Run",dist:7,dur:66,desc:"Taper begins!"},
        {week:15,day:2,type:"Speed/Hill Training",dist:8,dur:78,desc:"5 x 2km at 10K pace."},
        {week:15,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km."},
        {week:15,day:4,type:"Rest/Strength",dist:0,dur:20,desc:"Light strength only."},
        {week:15,day:5,type:"Tempo Run",dist:10,dur:95,desc:"40 min at marathon pace."},
        {week:15,day:6,type:"Long Run",dist:22,dur:204,desc:"22km. Reduced from peak."},
        {week:15,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Five weeks out."},
        {week:16,day:1,type:"Easy Run",dist:6,dur:56,desc:"Taper well underway."},
        {week:16,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"4 x 2km at marathon pace."},
        {week:16,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km moderate."},
        {week:16,day:4,type:"Rest/Strength",dist:0,dur:20,desc:"Maintenance only."},
        {week:16,day:5,type:"Tempo Run",dist:8,dur:75,desc:"30 min marathon pace."},
        {week:16,day:6,type:"Long Run",dist:18,dur:167,desc:"18km taper run."},
        {week:16,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Four weeks out."},
        {week:17,day:1,type:"Easy Run",dist:6,dur:56,desc:"Deep taper."},
        {week:17,day:2,type:"Speed/Hill Training",dist:5,dur:50,desc:"6 x 800m at 10K pace."},
        {week:17,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy."},
        {week:17,day:4,type:"Rest/Strength",dist:0,dur:15,desc:"Finalize race logistics."},
        {week:17,day:5,type:"Tempo Run",dist:6,dur:57,desc:"20 min marathon pace."},
        {week:17,day:6,type:"Long Run",dist:14,dur:130,desc:"14km easy. Last double-digit."},
        {week:17,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Three weeks out. You are ready!"},
        {week:18,day:1,type:"Easy Run",dist:5,dur:47,desc:"Very easy only."},
        {week:18,day:2,type:"Speed/Hill Training",dist:4,dur:40,desc:"4 x 800m. Short and sharp."},
        {week:18,day:3,type:"Medium Run",dist:6,dur:56,desc:"6km easy."},
        {week:18,day:4,type:"Rest/Strength",dist:0,dur:15,desc:"Pack race bag."},
        {week:18,day:5,type:"Tempo Run",dist:5,dur:47,desc:"15 min marathon pace."},
        {week:18,day:6,type:"Long Run",dist:10,dur:95,desc:"10km easy. Legs feeling ready!"},
        {week:18,day:7,type:"Recovery Run",dist:2,dur:18,desc:"Two weeks to marathon. Peak fitness!"},
        {week:19,day:1,type:"Easy Run",dist:4,dur:38,desc:"Pre-race week. No hard efforts."},
        {week:19,day:2,type:"Strides",dist:3,dur:28,desc:"Easy 3km with 4 x 20-sec strides."},
        {week:19,day:3,type:"Rest/Cross-train",dist:0,dur:15,desc:"Sort race logistics."},
        {week:19,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy shakeout."},
        {week:19,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Carb-load. Sleep well."},
        {week:19,day:6,type:"Easy Run",dist:2,dur:18,desc:"10-15 min shakeout."},
        {week:19,day:7,type:"Rest",dist:0,dur:0,desc:"Complete rest. Race tomorrow! Bed by 9:30pm."},
        {week:20,day:1,type:"RACE DAY! 🏆",dist:42.2,dur:0,desc:"MARATHON RACE DAY! Start slow, stay patient. YOU ARE A MARATHONER!"},
        {week:20,day:2,type:"Recovery Walk",dist:0,dur:30,desc:"Very gentle walk only."},
        {week:20,day:3,type:"Rest",dist:0,dur:0,desc:"Complete rest. Eat whatever you want."},
        {week:20,day:4,type:"Rest",dist:0,dur:0,desc:"Rest. Soreness peaks day 3 - normal."},
        {week:20,day:5,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk if legs allow."},
        {week:20,day:6,type:"Easy Walk/Jog",dist:2,dur:20,desc:"Very easy 20-min walk or jog."},
        {week:20,day:7,type:"Recovery",dist:0,dur:30,desc:"You completed a marathon!"},
      ]},
    }
  };

  // ── SKILL TREE + 21-DAY CHALLENGE + HYDRATION + DIET ─────────────
  var ext = {
  calisthenicsSkills: {
    handstand:  { name:"Handstand",   emoji:"🤸",  desc:"Freestanding 30-second hold",  steps:[
      { id:1, name:"Wall Handstand Hold",        desc:"Kick up, heels to wall. Hold 15-30 sec. Get comfortable inverted.",           req:"None" },
      { id:2, name:"Chest-to-Wall Handstand",    desc:"Face wall, walk feet up, chest-to-wall. Better body alignment.",              req:"None" },
      { id:3, name:"Back-to-Wall Handstand",     desc:"Kick up away from wall. Learn to control balance without falling.",           req:"None" },
      { id:4, name:"Freestanding 3-5 Seconds",   desc:"Away from wall. Short balance attempts. Finger press to adjust.",             req:"None" },
      { id:5, name:"Freestanding 30 Seconds",    desc:"Consistent 30-second holds. Perfect line, pointed toes. UNLOCKED! 🎉",       req:"None" },
    ]},
    muscleUp:   { name:"Muscle-Up",   emoji:"💪",  desc:"Clean bar muscle-up from dead hang", steps:[
      { id:1, name:"10 Clean Pull-Ups",           desc:"10 full range pull-ups. This is the prerequisite — build this first.",        req:"Pull-up bar" },
      { id:2, name:"Chest-to-Bar Pull-Ups",       desc:"Pull until chest touches bar. Builds explosive power for the transition.",   req:"Pull-up bar" },
      { id:3, name:"High Pull-Up + Hold",         desc:"Explosive pull, hold at top 2 sec. Feel where the transition happens.",      req:"Pull-up bar" },
      { id:4, name:"Negative Muscle-Up",          desc:"Jump to top, slowly lower through transition. Learn the movement pattern.",  req:"Pull-up bar" },
      { id:5, name:"Assisted Muscle-Up",          desc:"Use band or jump assist. Get the pattern right at full range.",              req:"Pull-up bar" },
      { id:6, name:"Full Muscle-Up",              desc:"Clean muscle-up from dead hang. Smooth transition. UNLOCKED! 🎉",            req:"Pull-up bar" },
    ]},
    frontLever: { name:"Front Lever", emoji:"📐",  desc:"Full front lever 5-second hold", steps:[
      { id:1, name:"Tuck Front Lever",            desc:"Knees tucked, body horizontal. Hold 5 sec. Build to 15 sec.",                req:"Pull-up bar" },
      { id:2, name:"Advanced Tuck Front Lever",   desc:"Knees at 90 degrees, hips extended. Body more horizontal. Hold 5-10 sec.", req:"Pull-up bar" },
      { id:3, name:"Straddle Front Lever",        desc:"Legs wide straddled, body horizontal. Hold 5 sec. Build to 10 sec.",        req:"Pull-up bar" },
      { id:4, name:"One-Leg Front Lever",         desc:"One leg extended, one tucked. Hold 5 sec. Switch sides.",                   req:"Pull-up bar" },
      { id:5, name:"Full Front Lever",            desc:"Both legs extended, body fully horizontal. 5-sec hold. UNLOCKED! 🎉",       req:"Pull-up bar" },
    ]},
    planche:    { name:"Planche",     emoji:"🏋️", desc:"Full planche 5-second hold", steps:[
      { id:1, name:"Planche Lean",                desc:"High plank, lean body forward over hands. Arms straight. Hold 10-15 sec.",   req:"None" },
      { id:2, name:"Tuck Planche",                desc:"Knees tucked, arms straight, body lifted and tilted forward. Hold 3-5 sec.", req:"None" },
      { id:3, name:"Advanced Tuck Planche",       desc:"Hips extended, back parallel to floor. 5-second hold.",                    req:"Parallel bars ideal" },
      { id:4, name:"Straddle Planche",            desc:"Legs wide, body horizontal, arms straight. 3-second hold.",                req:"Parallel bars ideal" },
      { id:5, name:"Full Planche",                desc:"Legs together, body fully horizontal, arms straight. UNLOCKED! 🎉",        req:"Parallel bars ideal" },
    ]},
    pistolSquat:{ name:"Pistol Squat",emoji:"🦵",  desc:"5 controlled pistol squats each leg", steps:[
      { id:1, name:"Assisted Squat",              desc:"Hold a support. Practice single-leg balance and depth. Build flexibility.",  req:"None" },
      { id:2, name:"Box Pistol Squat",            desc:"Lower onto a box (chair height), stand back up one-legged.",               req:"None" },
      { id:3, name:"Shrimp Squat",                desc:"Stand, hold back foot, squat down. Builds single-leg strength.",           req:"None" },
      { id:4, name:"Negative Pistol Squat",       desc:"Lower slowly to floor on one leg (5 sec), stand with two legs.",           req:"None" },
      { id:5, name:"Full Pistol Squat",           desc:"5 controlled reps each leg. Full depth. UNLOCKED! 🎉",                    req:"None" },
    ]},
    lSit:       { name:"L-Sit",       emoji:"🧘",  desc:"L-Sit hold for 30 seconds", steps:[
      { id:1, name:"Foot-Supported L-Sit",        desc:"Hands on floor, one heel on floor for support. Learn pressing strength.",   req:"None" },
      { id:2, name:"One-Leg L-Sit",               desc:"Extend one leg, other leg bent. Hold 5 sec. Alternate sides.",             req:"None" },
      { id:3, name:"Tuck L-Sit",                  desc:"Both legs tucked but lifted. Hold 5-10 sec.",                             req:"None" },
      { id:4, name:"L-Sit 10 Seconds",            desc:"Both legs fully extended. 10-second hold.",                               req:"Parallel bars ideal" },
      { id:5, name:"L-Sit 30 Seconds",            desc:"Full L-Sit for 30 unbroken seconds. UNLOCKED! 🎉",                       req:"Parallel bars ideal" },
    ]},
  },

  // ── 21-DAY CHALLENGE ─────────────────────────────────────────────
  calisthenicsChallenge: [
    { day:1,  name:"Day 1 — Start Easy",           exercises:[{name:"Push-Ups",sets:3,reps:"5 reps"},{name:"Squats",sets:3,reps:"10 reps"},{name:"Plank",sets:2,reps:"15 sec"}] },
    { day:2,  name:"Day 2 — Add Rows",             exercises:[{name:"Australian Rows",sets:3,reps:"5 reps"},{name:"Glute Bridge",sets:3,reps:"12 reps"},{name:"Dead Bug",sets:2,reps:"5 each"}] },
    { day:3,  name:"Day 3 — Active Rest",          exercises:[{name:"Neck Rolls",sets:1,reps:"1 min"},{name:"Hip Circles",sets:1,reps:"10 each dir"},{name:"Hamstring Stretch",sets:2,reps:"45 sec each"}] },
    { day:4,  name:"Day 4 — Push Focus",           exercises:[{name:"Push-Ups",sets:3,reps:"8 reps"},{name:"Tricep Dips",sets:3,reps:"8 reps"},{name:"Plank",sets:3,reps:"20 sec"}] },
    { day:5,  name:"Day 5 — Pull Focus",           exercises:[{name:"Australian Rows",sets:3,reps:"8 reps"},{name:"Dead Hang",sets:3,reps:"15 sec"},{name:"Superman Hold",sets:2,reps:"20 sec"}] },
    { day:6,  name:"Day 6 — Leg Focus",            exercises:[{name:"Squats",sets:4,reps:"12 reps"},{name:"Reverse Lunges",sets:3,reps:"8 each"},{name:"Calf Raises",sets:3,reps:"15 reps"}] },
    { day:7,  name:"Day 7 — Rest and Recover",     exercises:[{name:"Full body stretch",sets:1,reps:"10 min"}] },
    { day:8,  name:"Day 8 — Push and Core",        exercises:[{name:"Push-Ups",sets:3,reps:"10 reps"},{name:"Hollow Body Hold",sets:3,reps:"15 sec"},{name:"Mountain Climbers",sets:2,reps:"20 sec"}] },
    { day:9,  name:"Day 9 — Pull and Legs",        exercises:[{name:"Australian Rows",sets:3,reps:"10 reps"},{name:"Box Squat",sets:3,reps:"10 reps"},{name:"Glute Bridge",sets:3,reps:"15 reps"}] },
    { day:10, name:"Day 10 — Active Rest",         exercises:[{name:"Hip Flexor Stretch",sets:2,reps:"60 sec each"},{name:"Thoracic Rotation",sets:2,reps:"10 each"},{name:"Wrist Circles",sets:1,reps:"2 min"}] },
    { day:11, name:"Day 11 — First Circuit",       exercises:[{name:"Push-Ups",sets:3,reps:"8 reps"},{name:"Squats",sets:3,reps:"15 reps"},{name:"Australian Rows",sets:3,reps:"8 reps"},{name:"Plank",sets:3,reps:"25 sec"}] },
    { day:12, name:"Day 12 — Push Volume",         exercises:[{name:"Incline Push-Ups",sets:4,reps:"12 reps"},{name:"Pike Push-Ups",sets:3,reps:"6 reps"},{name:"Shoulder Tap Plank",sets:3,reps:"10 taps"}] },
    { day:13, name:"Day 13 — Pull Volume",         exercises:[{name:"Australian Rows",sets:4,reps:"10 reps"},{name:"Dead Hang",sets:3,reps:"20 sec"},{name:"Scapular Pulls",sets:3,reps:"8 reps"}] },
    { day:14, name:"Day 14 — Rest and Reflect",    exercises:[{name:"Full body stretch",sets:1,reps:"15 min"},{name:"Breathing",sets:1,reps:"5 min"}] },
    { day:15, name:"Day 15 — Skill Introduction",  exercises:[{name:"Wall Handstand",sets:5,reps:"3 attempts"},{name:"L-Sit Prep",sets:5,reps:"5 sec holds"},{name:"Hollow Body",sets:3,reps:"20 sec"}] },
    { day:16, name:"Day 16 — Strength Test",       exercises:[{name:"Max Push-Ups",sets:1,reps:"max"},{name:"Max Squats",sets:1,reps:"max"},{name:"Max Hang",sets:1,reps:"max seconds"}] },
    { day:17, name:"Day 17 — Active Recovery",     exercises:[{name:"Butterfly Stretch",sets:2,reps:"60 sec"},{name:"Pigeon Pose",sets:2,reps:"60 sec each"},{name:"Cat-Cow",sets:1,reps:"10 rounds"}] },
    { day:18, name:"Day 18 — Full Workout A",      exercises:[{name:"Push-Ups",sets:4,reps:"10 reps"},{name:"Australian Rows",sets:4,reps:"10 reps"},{name:"Squats",sets:4,reps:"15 reps"},{name:"Plank",sets:3,reps:"30 sec"}] },
    { day:19, name:"Day 19 — Full Workout B",      exercises:[{name:"Pike Push-Ups",sets:3,reps:"8 reps"},{name:"Dead Hang",sets:3,reps:"25 sec"},{name:"Reverse Lunges",sets:3,reps:"10 each"},{name:"Hollow Body",sets:3,reps:"20 sec"}] },
    { day:20, name:"Day 20 — Active Rest",         exercises:[{name:"Hip mobility",sets:2,reps:"60 sec each"},{name:"Shoulder mobility",sets:2,reps:"30 sec each"},{name:"Wrist prep",sets:1,reps:"2 min"}] },
    { day:21, name:"Day 21 — FINISH STRONG! 🏆",   exercises:[{name:"Push-Ups",sets:5,reps:"max reps"},{name:"Australian Rows",sets:5,reps:"max reps"},{name:"Squats",sets:5,reps:"max reps"},{name:"Plank",sets:3,reps:"max time"},{name:"You did it!",sets:1,reps:""}] },
  ],


  hydration: {
    // One plan per module — scientifically tailored to activity type
    default: {
      title: "Daily Hydration Plan",
      targets: { training: 3.0, rest: 2.5 },
      schedule: [
        { time:"7:00 AM",        amount:500, label:"Wake-up glass" },
        { time:"9:00 AM",        amount:400, label:"Mid-morning" },
        { time:"12:00 PM",       amount:500, label:"Before lunch" },
        { time:"3:00 PM",        amount:400, label:"Afternoon" },
        { time:"Pre-Workout",    amount:400, label:"30 min before" },
        { time:"During Workout", amount:500, label:"Sip every 15 min" },
        { time:"Post-Workout",   amount:500, label:"Within 30 min" },
        { time:"8:00 PM",        amount:300, label:"Evening" },
      ],
      tips: [
        "Urine colour should be pale yellow — dark means you need more water.",
        "Add a pinch of Himalayan pink salt on heavy training days to replace electrolytes.",
        "Drink 200–300ml extra per 30 min in hot or humid weather.",
      ]
    },

    cardio: {
      title: "Home Cardio Hydration Plan",
      targets: { training: 3.5, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (7 AM)",     amount:500, label:"Start metabolism, flush overnight waste" },
        { time:"Pre-Workout (30 min)", amount:400, label:"Hydrate before intense cardio" },
        { time:"During Cardio",      amount:600, label:"150ml every 15 min — cardio causes heavy sweat" },
        { time:"Post-Workout (30 min)", amount:500, label:"Replace sweat losses immediately" },
        { time:"Mid-Morning",        amount:400, label:"Sustained hydration between sessions" },
        { time:"Before Lunch",       amount:300, label:"Aids digestion and nutrient absorption" },
        { time:"Afternoon (3 PM)",   amount:400, label:"Prevents afternoon energy dip" },
        { time:"Evening (7 PM)",     amount:300, label:"Light — avoid excess before sleep" },
      ],
      tips: [
        "Cardio causes 0.5–1.5L sweat/hour — drink before you feel thirsty.",
        "Add coconut water or electrolyte tabs after sessions longer than 45 minutes.",
        "Cold water (15°C) absorbs 30% faster than room temperature during exercise.",
        "Weigh yourself before and after — drink 1.5L per kg lost during session.",
        "Avoid sugary sports drinks for sessions under 60 min — plain water is sufficient.",
      ]
    },

    gym: {
      title: "Gym Workout Hydration Plan",
      targets: { training: 4.0, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (7 AM)",      amount:500, label:"Rehydrate after 7–8 hrs without water" },
        { time:"Pre-Workout (60 min)", amount:500, label:"Top up glycogen and joints for lifting" },
        { time:"Pre-Workout (15 min)", amount:250, label:"Final top-up before first set" },
        { time:"During Lifting",      amount:750, label:"200ml between every 2–3 sets" },
        { time:"Post-Workout (30 min)", amount:600, label:"Critical — begin recovery immediately" },
        { time:"With Protein Meal",   amount:400, label:"Aids protein synthesis and digestion" },
        { time:"Afternoon",           amount:500, label:"Joints and muscle repair require hydration" },
        { time:"Evening",             amount:400, label:"Casein protein digestion needs extra water" },
      ],
      tips: [
        "Heavy lifting causes micro-tears — muscles repair faster when fully hydrated.",
        "Dehydration of just 2% body weight reduces strength by up to 10%.",
        "Creatine users need an extra 500ml daily — creatine draws water into muscles.",
        "Sip water between sets, not during reps — avoid bloating mid-lift.",
        "Post-workout: aim for 150% of fluid lost (e.g. lost 500ml → drink 750ml).",
        "Joint health: cartilage is 80% water — consistent hydration prevents knee/shoulder pain.",
      ]
    },

    yoga: {
      title: "Yoga Practice Hydration Plan",
      targets: { training: 2.5, rest: 2.0 },
      schedule: [
        { time:"Wake-Up (6:30 AM)",   amount:500, label:"Warm water with lemon — cleanses and alkalises" },
        { time:"30 Min Before Yoga",  amount:200, label:"Small sip only — avoid heavy stomach during poses" },
        { time:"During Practice",     amount:200, label:"Tiny sips only if very thirsty — don't interrupt flow" },
        { time:"Post-Practice",       amount:400, label:"Rehydrate mindfully after deep stretches" },
        { time:"Mid-Morning",         amount:400, label:"Room temperature water preferred in yoga lifestyle" },
        { time:"Before Lunch",        amount:300, label:"30 min before meals for optimal digestion" },
        { time:"Afternoon",           amount:350, label:"Herbal teas count — tulsi, ginger, chamomile" },
        { time:"Evening",             amount:250, label:"Light — calming the body before rest" },
      ],
      tips: [
        "Yoga tradition prefers room-temperature or warm water — cold water can disrupt digestive fire (agni).",
        "Avoid drinking large amounts 30 min before or during practice — it compresses the core.",
        "Coconut water is the ideal post-yoga drink — natural electrolytes and calming properties.",
        "Hot yoga (Bikram) requires 1L extra — you lose significantly more through sweat.",
        "Herbal teas (tulsi, ginger, peppermint) count toward daily intake and support digestion.",
        "Eating water-rich foods (cucumber, watermelon, oranges) aligns with yogic diet principles.",
      ]
    },

    stretching: {
      title: "Stretching & Recovery Hydration Plan",
      targets: { training: 2.5, rest: 2.0 },
      schedule: [
        { time:"Wake-Up",             amount:500, label:"Warm water — hydrates overnight-stiff muscles" },
        { time:"Before Stretching",   amount:300, label:"Warm muscles stretch better when hydrated" },
        { time:"During Stretching",   amount:200, label:"Small sips — stretching is low intensity" },
        { time:"Post-Stretching",     amount:300, label:"Flush released toxins from fascia" },
        { time:"Mid-Morning",         amount:400, label:"Collagen synthesis requires hydration" },
        { time:"Lunch Time",          amount:400, label:"Support joint lubrication throughout day" },
        { time:"Afternoon",           amount:300, label:"Consistent low-level hydration is key" },
        { time:"Evening",             amount:200, label:"Light — this is a recovery/rest day" },
      ],
      tips: [
        "Fascia (connective tissue) is 70% water — dehydration makes it stiff and less elastic.",
        "Warm water before stretching loosens muscle fibres faster than cold water.",
        "Collagen (joint and muscle repair) synthesis requires adequate vitamin C and hydration.",
        "Bone broth counts toward intake and provides collagen directly.",
        "Avoid alcohol on stretching/rest days — it dehydrates and slows muscle repair by 24hrs.",
        "Magnesium-rich water (or supplement) on rest days reduces muscle soreness significantly.",
      ]
    },

    calisthenics: {
      title: "Calisthenics Hydration Plan",
      targets: { training: 3.0, rest: 2.5 },
      schedule: [
        { time:"Wake-Up",              amount:500, label:"Rehydrate after overnight fast" },
        { time:"Before Training",      amount:400, label:"30 min before — top up joints and muscles" },
        { time:"During Training",      amount:400, label:"Sip between sets — not during reps" },
        { time:"Post-Training",        amount:500, label:"Critical window — begin recovery immediately" },
        { time:"Mid-Morning",          amount:300, label:"Sustained hydration for muscle repair" },
        { time:"Lunch",                amount:400, label:"Supports protein synthesis" },
        { time:"Afternoon",            amount:300, label:"Joint lubrication and continued recovery" },
        { time:"Evening",              amount:300, label:"Light — support overnight repair" },
      ],
      tips: [
        "Bodyweight training causes less sweat than cardio but hydration is still critical for joint health.",
        "Wrist and shoulder joints need consistent hydration — cartilage is 80% water.",
        "Sip between sets, not during reps — avoid bloating when in plank or handstand positions.",
        "After skill work (handstand, L-sit), extra hydration supports the nervous system recovery.",
        "Protein synthesis for muscle repair requires adequate water — aim for 3L on training days.",
      ]
    },

    running: {
      title: "Running & Walking Hydration Plan",
      targets: { training: 4.5, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (6 AM)",       amount:500, label:"Start the day hydrated before early runs" },
        { time:"2 Hours Before Run",   amount:500, label:"Pre-load hydration — kidneys process excess" },
        { time:"15 Min Before Run",    amount:200, label:"Final top-up without bloating" },
        { time:"During Run (<45 min)", amount:400, label:"150–200ml every 20 min — small frequent sips" },
        { time:"During Run (>45 min)", amount:700, label:"Sports drink or water + salt every 20–30 min" },
        { time:"Post-Run (30 min)",    amount:600, label:"Most critical window — begin recovery immediately" },
        { time:"Post-Run (2 hrs)",     amount:500, label:"Continue sipping — 1.5L per kg lost" },
        { time:"Evening",              amount:400, label:"Support overnight muscle and joint recovery" },
      ],
      tips: [
        "Running loses 500ml–1.5L per hour depending on heat, humidity and pace.",
        "The thirst signal lags 20 min behind actual need — drink on a schedule, not when thirsty.",
        "For runs over 60 min, add electrolytes (sodium, potassium) — water alone causes hyponatremia.",
        "Hot weather running: pre-cool with 500ml ice-cold water 10 min before — reduces core temp.",
        "Weigh before and after every long run. Drink 1.5L for every 1kg lost.",
        "Marathon training: increase daily intake by 1L on days with runs over 16km.",
        "Signs of dehydration while running: dark urine, headache, cramping, nausea, confusion — stop immediately.",
      ]
    },
  },

    diet: {
    modules: {
      cardio:     { title:"Cardio Day Diet Plan",   meals:[
        { time:"Pre-Workout",  name:"Energy Boost",     items:"Banana + black coffee or green tea", cal:150, notes:"30-45 min before session" },
        { time:"Post-Workout", name:"Recovery Meal",    items:"2 boiled eggs + 1 slice whole wheat toast", cal:220, notes:"Within 30 min after" },
        { time:"Breakfast",    name:"Carb-Forward Meal",items:"Oats porridge with fruit and nuts", cal:380, notes:"Replenish glycogen" },
        { time:"Lunch",        name:"Balanced Meal",    items:"Brown rice + grilled chicken 150g + vegetables", cal:560, notes:"Protein + complex carbs" },
        { time:"Snack",        name:"Afternoon Fuel",   items:"Greek yogurt + handful of almonds", cal:220, notes:"Sustained energy" },
        { time:"Dinner",       name:"Light Recovery",   items:"Lentil soup + 2 chapati + salad", cal:480, notes:"Early, light dinner" },
      ]},
      gym:        { title:"Gym Day Diet Plan",      meals:[
        { time:"Pre-Workout",  name:"Power Fuel",        items:"Banana + 2 boiled eggs + optional coffee", cal:280, notes:"60 min before lifting" },
        { time:"Intra-Workout",name:"Hydration",         items:"Water + optional BCAA drink", cal:50, notes:"Sip during session" },
        { time:"Post-Workout", name:"Anabolic Window",   items:"Whey protein shake or 200g Greek yogurt + fruit", cal:280, notes:"Within 30 min — critical!" },
        { time:"Lunch",        name:"Muscle Building",   items:"Brown rice 200g + grilled chicken 180g + vegetables", cal:620, notes:"2-3 hrs post-workout" },
        { time:"Snack",        name:"Protein Boost",     items:"Cottage cheese or paneer 100g + fruit", cal:200, notes:"Afternoon" },
        { time:"Dinner",       name:"Casein Meal",       items:"Dal + 2 chapati + salad + glass of milk", cal:520, notes:"Slow-digesting protein overnight" },
      ]},
      yoga:       { title:"Yoga Day Diet Plan",     meals:[
        { time:"Pre-Yoga",  name:"Light Energy",       items:"Small banana or 4-5 dates + herbal tea", cal:120, notes:"30-60 min before. Avoid heavy food." },
        { time:"Post-Yoga", name:"Nourishment",        items:"Smoothie: banana + spinach + almond milk + honey", cal:240, notes:"Replenish mindfully" },
        { time:"Breakfast", name:"Sattvic Breakfast",  items:"Poha or upma + coconut chutney + herbal tea", cal:360, notes:"Light, digestible" },
        { time:"Lunch",     name:"Balanced Thali",     items:"Dal + rice + sabzi + curd + salad", cal:580, notes:"Largest meal of day" },
        { time:"Snack",     name:"Light Snack",        items:"Fresh fruit + handful walnuts", cal:180, notes:"Afternoon, light" },
        { time:"Dinner",    name:"Early Light Dinner", items:"Khichdi or vegetable soup + bread", cal:420, notes:"By 7pm ideally" },
      ]},
      stretching: { title:"Rest/Stretch Day Diet Plan", meals:[
        { time:"Morning",  name:"Anti-Inflammatory",items:"Turmeric milk or golden latte + fruit", cal:200, notes:"Anti-inflammatory start" },
        { time:"Breakfast",name:"Protein + Fibre",   items:"2 eggs any style + whole grain toast + avocado", cal:420, notes:"Sustained energy" },
        { time:"Lunch",    name:"Omega-Rich Meal",   items:"Grilled fish or tofu + quinoa + roasted vegetables", cal:540, notes:"Recovery nutrition" },
        { time:"Snack",    name:"Collagen Boost",    items:"Bone broth or gelatin-rich foods", cal:120, notes:"Supports joint health" },
        { time:"Dinner",   name:"Recovery Dinner",   items:"Chicken/lentil soup + whole grain bread", cal:460, notes:"Easy to digest" },
      ]},
      running: { title:"Running Day Diet Plan", meals:[
        { time:"Pre-Run (2-3 hrs)", name:"Main Pre-Run Meal", items:"Oats with banana + honey OR 2 slices toast + peanut butter + banana", cal:380, notes:"Easy to digest carbs — avoid fibre and fat close to run" },
        { time:"Pre-Run (30 min)", name:"Quick Energy Top-Up", items:"1 banana OR 4–5 dates OR half energy bar", cal:120, notes:"Quick-release glucose — nothing heavy" },
        { time:"During Run (>60 min)", name:"Intra-Run Fuel", items:"Energy gel OR banana chunk OR 3–4 dates every 45 min", cal:100, notes:"Per serving — only needed for runs over 60 min" },
        { time:"Post-Run (30 min)", name:"Recovery Window", items:"Chocolate milk OR whey shake + banana OR Greek yogurt + mango", cal:320, notes:"CRITICAL: 3:1 carb:protein ratio — this window is gold" },
        { time:"Post-Run Meal (1-2 hrs)", name:"Full Recovery Meal", items:"White rice + grilled chicken/fish + roasted vegetables", cal:620, notes:"White rice preferred post-run — faster glycogen replenishment than brown" },
        { time:"Evening Snack", name:"Overnight Recovery", items:"Cottage cheese (paneer) OR casein protein + warm milk", cal:220, notes:"Slow-digesting protein repairs muscles during sleep" },
      ]},
      calisthenics: { title:"Calisthenics Day Diet Plan", meals:[
        { time:"Pre-Training",    name:"Light Energy",       items:"Banana + 2 boiled eggs OR oats + honey", cal:280, notes:"45-60 min before. Easy to digest — avoid heavy food before skill work." },
        { time:"Post-Training",   name:"Recovery Window",    items:"Whey protein shake + banana OR Greek yogurt + mango", cal:280, notes:"Within 30 min — critical for muscle protein synthesis" },
        { time:"Breakfast",       name:"Muscle Building",    items:"Oats + 3 eggs + fruit OR whole grain toast + peanut butter + banana", cal:480, notes:"Carbs + protein combo for strength gains" },
        { time:"Lunch",           name:"Protein-Rich Meal",  items:"Brown rice + grilled chicken 180g + vegetables + curd", cal:580, notes:"Largest protein meal of the day" },
        { time:"Snack",           name:"Afternoon Fuel",     items:"Cottage cheese (paneer) + fruit OR handful nuts + dark chocolate", cal:220, notes:"Casein-rich snack keeps muscles fed" },
        { time:"Dinner",          name:"Recovery Dinner",    items:"Dal + chapati + sabzi + salad + glass of milk", cal:520, notes:"Slow-digesting protein for overnight muscle repair" },
      ]},
    }
  }
};
  Object.keys(ext).forEach(function(k) { D[k] = ext[k]; });

  // ── FREEZE BACKUP ─────────────────────────────────────────────────
  window.APP_DATA_DEFAULT = JSON.parse(JSON.stringify(D));
  console.log('[FitFlow] data-cali.js loaded. Modules:', Object.keys(D.modules));
  console.log('[FitFlow] Running plans:', Object.keys(D.running.plans));
})();
