// ── DEFAULT DATA ─────────────────────────────────────────────────
window.APP_DATA = {

  quotes: [
    { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
    { text: "Success is usually the culmination of controlling failure.", author: "Sylvester Stallone" },
    { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
    { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
    { text: "Fitness is not about being better than someone else. It's about being better than you used to be.", author: "Unknown" },
    { text: "Push yourself because no one else is going to do it for you.", author: "Unknown" },
    { text: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Unknown" },
    { text: "Don't wish for it. Work for it.", author: "Unknown" },
    { text: "The difference between try and triumph is a little umph.", author: "Marvin Phillips" },
    { text: "Sweat is just fat crying.", author: "Unknown" },
    { text: "No matter how slow you go, you are still lapping everybody on the couch.", author: "Unknown" },
    { text: "Be stronger than your strongest excuse.", author: "Unknown" },
  ],

  // ── WARMUP (shared structure, used by cardio, gym, yoga, running) ─
  warmups: {
    cardio: [
      { name:"Dynamic Warm-Up", sets:1, reps:"5 min", desc:"March in place 1 min → arm circles 1 min → hip circles 1 min → leg swings 1 min → neck rolls 1 min. Raise heart rate gradually before the workout.", image:"", demo:"https://www.youtube.com/results?search_query=cardio+warm+up+routine+5+minutes", tag:"warmup" },
    ],
    gym: [
      { name:"Gym Warm-Up", sets:1, reps:"5 min", desc:"5 min light cardio (treadmill/bike) → dynamic chest opener 10 reps → world's greatest stretch 5 each side → glute bridges 15 reps. Prepares muscles and joints for heavy lifting.", image:"", demo:"https://www.youtube.com/results?search_query=gym+warm+up+before+workout", tag:"warmup" },
    ],
    yoga: [
      { name:"Yoga Warm-Up", sets:1, reps:"5 min", desc:"Seated breathing 2 min → neck & shoulder rolls 1 min → cat-cow 8 rounds → child's pose 1 min. Calms the mind and prepares the spine for practice.", image:"", demo:"https://www.youtube.com/results?search_query=yoga+warm+up+routine", tag:"warmup" },
    ],
    running: [
      { name:"Pre-Run Warm-Up", sets:1, reps:"5 min", desc:"Brisk walk 2 min → slow high knees 30 sec → ankle circles 10 each → hip flexor lunge 30 sec each → leg swings 10 each. Essential before every run to prevent injury.", image:"", demo:"https://www.youtube.com/results?search_query=running+warm+up+routine", tag:"warmup" },
    ],
  },

    cooldowns: {
    cardio: [
      { name:"Cool-Down & Stretch", sets:1, reps:"5 min", desc:"Slow walk 2 min → standing quad stretch 30 sec each → standing hamstring stretch 30 sec each → hip flexor stretch 30 sec each → chest opener 45 sec. Essential for recovery and flexibility.", image:"", demo:"https://www.youtube.com/results?search_query=cardio+cool+down+stretch+routine", tag:"cooldown" },
    ],
    gym: [
      { name:"Post-Workout Cool-Down", sets:1, reps:"5 min", desc:"5 min easy walk → doorway chest stretch 45 sec → lat stretch 30 sec each → seated hamstring stretch 45 sec each → child's pose 2 min. Flush lactic acid and restore muscle length.", image:"", demo:"https://www.youtube.com/results?search_query=gym+cool+down+stretching+routine", tag:"cooldown" },
    ],
    yoga: [
      { name:"Yoga Cool-Down", sets:1, reps:"5 min", desc:"Supine twist 60 sec each → legs up the wall 3 min → happy baby 90 sec → Savasana 5 min. Never skip Savasana — the body needs time to absorb the practice.", image:"", demo:"https://www.youtube.com/results?search_query=yoga+cool+down+savasana", tag:"cooldown" },
    ],
    running: [
      { name:"Post-Run Cool-Down", sets:1, reps:"5 min", desc:"Easy walk 3 min → standing calf stretch 45 sec each → quad stretch 30 sec each → IT band stretch 45 sec each → seated hamstring & glute stretch 60 sec each. Critical for runner recovery.", image:"", demo:"https://www.youtube.com/results?search_query=post+run+cool+down+stretches", tag:"cooldown" },
    ],
  },

    modules: {
    cardio: {
      name: "Home Cardio",
      emoji: "🏠",
      color: "grad-cardio",
      days: {
      days: {
        Monday: [
          { name:"Warm-Up: Jumping Jacks", sets:1, reps:"2 min", desc:"Stand upright, jump feet apart while raising arms overhead. Increases heart rate and warms joints. Month 1: 60 sec. Month 2: 90 sec. Month 3: 2 min.", image:"", demo:"https://www.youtube.com/results?search_query=jumping+jacks+warm+up+exercise" },
          { name:"Warm-Up: Arm Circles", sets:1, reps:"30 sec each", desc:"Full arm circles forward then backward. Loosens shoulder joints before chest work. Month 1: small circles. Month 2-3: full large circles.", image:"", demo:"https://www.youtube.com/results?search_query=arm+circles+shoulder+warm+up" },
          { name:"Push-Ups", sets:4, reps:"Max reps", desc:"Hands shoulder-width, body straight. Lower chest to floor, push up fully. Month 1: 4x8. Month 2: 4x12. Month 3: 4x max reps.", image:"", demo:"https://www.youtube.com/results?search_query=push+ups+proper+form+tutorial" },
          { name:"Incline Push-Ups", sets:3, reps:"12 reps", desc:"Hands elevated on chair. Targets upper chest. Month 1: 3x8 high incline. Month 2: 3x12 medium. Month 3: 3x15 low incline.", image:"", demo:"https://www.youtube.com/results?search_query=incline+push+ups+upper+chest" },
          { name:"Decline Push-Ups", sets:3, reps:"10 reps", desc:"Feet elevated on chair, hands on floor. Targets lower chest. Month 1: 3x6. Month 2: 3x10. Month 3: 3x12 slow tempo.", image:"", demo:"https://www.youtube.com/results?search_query=decline+push+ups+lower+chest" },
          { name:"Bench Dips", sets:3, reps:"12 reps", desc:"Hands on chair behind you, legs extended. Lower until elbows 90 degrees, press back up. Month 1: 3x10 bent knees. Month 2: 3x12 straight legs. Month 3: 3x15.", image:"", demo:"https://www.youtube.com/results?search_query=bench+dips+triceps+exercise" },
          { name:"Diamond Push-Ups", sets:3, reps:"10 reps", desc:"Hands form a diamond under chest. Squeezes inner chest and triceps. Month 1: 3x6 from knees. Month 2: 3x10 full. Month 3: 3x12 with pause at bottom.", image:"", demo:"https://www.youtube.com/results?search_query=diamond+push+ups+triceps+chest" },
          { name:"Plank Hold", sets:3, reps:"45 sec", desc:"Forearms on floor, body straight. Squeeze glutes and core. Month 1: 3x30 sec. Month 2: 3x45 sec. Month 3: 3x60 sec.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+core+exercise+form" },
          { name:"Cool-Down: Chest Stretch", sets:1, reps:"60 sec each side", desc:"Doorway chest stretch. Place forearm on wall at 90 degrees, rotate body away. Releases chest and anterior shoulder.", image:"", demo:"https://www.youtube.com/results?search_query=chest+stretch+cool+down+after+workout" },
        ],
        Tuesday: [
          { name:"Warm-Up: Light Cardio", sets:1, reps:"3 min", desc:"March in place, arm swings, torso rotations. Gets blood flowing to back and bicep muscles before pulling work.", image:"", demo:"https://www.youtube.com/results?search_query=light+cardio+warm+up+at+home" },
          { name:"Pull-Ups or Assisted Pull-Ups", sets:3, reps:"Max reps", desc:"Grip bar shoulder-width, pull chin above bar from full hang. Month 1: 3x3-5 band assisted. Month 2: 3x5-8. Month 3: 3x max unassisted.", image:"", demo:"https://www.youtube.com/results?search_query=pull+ups+proper+form+beginners" },
          { name:"Resistance Band Rows", sets:3, reps:"12 reps", desc:"Anchor band at chest height. Pull handles to lower chest, squeeze shoulder blades. Month 1: light band. Month 2: medium band. Month 3: heavy band.", image:"", demo:"https://www.youtube.com/results?search_query=resistance+band+row+back+exercise" },
          { name:"Superman Hold", sets:3, reps:"30 sec", desc:"Lie face down, arms extended forward. Lift arms, chest and legs off floor simultaneously. Month 1: 3x20 sec. Month 2: 3x30 sec. Month 3: 3x45 sec.", image:"", demo:"https://www.youtube.com/results?search_query=superman+hold+back+exercise+form" },
          { name:"Towel Curls", sets:3, reps:"12 reps", desc:"Loop towel under foot, hold both ends. Curl foot toward you providing resistance. Month 1: 3x10 light. Month 2: 3x12. Month 3: 3x15 slow tempo.", image:"", demo:"https://www.youtube.com/results?search_query=towel+bicep+curls+home+workout" },
          { name:"Reverse Snow Angels", sets:3, reps:"10 reps", desc:"Lie face down, arms at sides. Sweep arms up overhead and back. Builds lower trap and rhomboid. Month 1: 3x8. Month 2: 3x10. Month 3: 3x12 with pause overhead.", image:"", demo:"https://www.youtube.com/results?search_query=reverse+snow+angels+back+exercise" },
          { name:"Chin-Ups", sets:3, reps:"Max reps", desc:"Underhand grip. Pull until chin clears bar. Recruits more bicep than pull-ups. Month 1: 3x3-5 band assisted. Month 2: 3x5-8. Month 3: 3x max.", image:"", demo:"https://www.youtube.com/results?search_query=chin+ups+form+biceps+back" },
          { name:"Cool-Down: Back Stretch", sets:1, reps:"2 min", desc:"Child's pose 60 sec, seated spinal twist 30 sec each side. Full back release after pulling session.", image:"", demo:"https://www.youtube.com/results?search_query=back+stretch+cool+down+after+workout" },
        ],
        Wednesday: [
          { name:"Warm-Up: High Knees", sets:1, reps:"45 sec", desc:"Run in place driving knees to waist height. Activates hip flexors before leg work.", image:"", demo:"https://www.youtube.com/results?search_query=high+knees+warm+up+exercise" },
          { name:"Warm-Up: Leg Swings", sets:1, reps:"10 each leg", desc:"Hold wall, swing leg forward and back then side to side. Opens hip flexors and hamstrings.", image:"", demo:"https://www.youtube.com/results?search_query=leg+swings+warm+up+hip+flexor" },
          { name:"Squats", sets:4, reps:"15 reps", desc:"Feet shoulder-width, toes slightly out. Squat until thighs parallel. Drive through heels. Month 1: 4x12 bodyweight. Month 2: 4x15. Month 3: 4x20 or add weight.", image:"", demo:"https://www.youtube.com/results?search_query=bodyweight+squat+proper+form+tutorial" },
          { name:"Lunges", sets:3, reps:"12 each leg", desc:"Step forward, back knee nearly touching floor. Push off front foot to return. Month 1: 3x10 stationary. Month 2: 3x12 walking. Month 3: 3x15 each leg.", image:"", demo:"https://www.youtube.com/results?search_query=lunges+proper+form+home+workout" },
          { name:"Step-Ups", sets:3, reps:"12 each leg", desc:"Step onto chair with one foot, drive up, step down. Excellent quad and glute builder. Month 1: 3x10 low step. Month 2: 3x12 higher step. Month 3: 3x15 each leg.", image:"", demo:"https://www.youtube.com/results?search_query=step+ups+exercise+quads+glutes" },
          { name:"Glute Bridge", sets:3, reps:"15 reps", desc:"Lie on back, knees bent. Drive hips to ceiling, squeeze glutes at top. Month 1: 3x12 two legs. Month 2: 3x15. Month 3: 3x15 single leg each side.", image:"", demo:"https://www.youtube.com/results?search_query=glute+bridge+exercise+form" },
          { name:"Wall Sit", sets:3, reps:"45 sec", desc:"Back flat on wall, thighs parallel to floor, knees at 90 degrees. Hold position. Month 1: 3x30 sec. Month 2: 3x45 sec. Month 3: 3x60 sec.", image:"", demo:"https://www.youtube.com/results?search_query=wall+sit+exercise+quads" },
          { name:"Calf Raises", sets:4, reps:"20 reps", desc:"Stand on step edge or flat floor. Rise onto toes, hold 1 sec, lower slowly. Month 1: 4x15. Month 2: 4x20. Month 3: 4x25 single leg.", image:"", demo:"https://www.youtube.com/results?search_query=calf+raises+exercise+form+home" },
          { name:"Cool-Down: Leg Stretches", sets:1, reps:"2 min", desc:"Quad stretch 30 sec each, hamstring stretch 30 sec each, hip flexor lunge stretch 30 sec each side.", image:"", demo:"https://www.youtube.com/results?search_query=leg+stretches+cool+down+after+workout" },
        ],
        Thursday: [
          { name:"Warm-Up: Arm Rotations", sets:1, reps:"30 sec each direction", desc:"Full arm circles forward and backward. Warms shoulder joint capsule before shoulder work.", image:"", demo:"https://www.youtube.com/results?search_query=arm+rotations+shoulder+warm+up" },
          { name:"Pike Push-Ups", sets:3, reps:"10 reps", desc:"Start in downward dog position. Bend elbows and lower head toward floor, push back up. Best bodyweight shoulder press. Month 1: 3x8. Month 2: 3x10. Month 3: 3x12 slow tempo.", image:"", demo:"https://www.youtube.com/results?search_query=pike+push+ups+shoulders+form" },
          { name:"Wall Push-Ups", sets:3, reps:"12 reps", desc:"Stand arm length from wall. Angle targets anterior deltoid. Month 1: 3x12. Month 2: 3x15. Month 3: increase angle toward floor.", image:"", demo:"https://www.youtube.com/results?search_query=wall+push+ups+shoulder+exercise" },
          { name:"Resistance Band Lateral Raises", sets:3, reps:"12 reps", desc:"Stand on band, raise arms to shoulder height with slight elbow bend. Targets medial deltoid. Month 1: light band 3x10. Month 2: 3x12. Month 3: heavier band 3x15.", image:"", demo:"https://www.youtube.com/results?search_query=resistance+band+lateral+raise+shoulders" },
          { name:"Handstand Hold Against Wall", sets:3, reps:"30 sec", desc:"Kick up to handstand with heels against wall. Builds shoulder stability. Month 1: 3x15 sec pike hold. Month 2: 3x20 sec partial. Month 3: 3x30 sec full hold.", image:"", demo:"https://www.youtube.com/results?search_query=handstand+against+wall+beginners+tutorial" },
          { name:"Shoulder Taps", sets:3, reps:"20 taps", desc:"High plank. Alternate tapping opposite shoulder keeping hips square. Month 1: 3x14 taps. Month 2: 3x20. Month 3: 3x28.", image:"", demo:"https://www.youtube.com/results?search_query=plank+shoulder+taps+exercise" },
          { name:"Front Raises with Band", sets:3, reps:"12 reps", desc:"Stand on band. Raise straight arms to shoulder height. Targets anterior deltoid. Month 1: light band 3x10. Month 2: 3x12. Month 3: 3x15 heavier band.", image:"", demo:"https://www.youtube.com/results?search_query=resistance+band+front+raise+shoulder" },
          { name:"Cool-Down: Shoulder Stretch", sets:1, reps:"2 min", desc:"Cross-body shoulder stretch 30 sec each arm. Overhead tricep stretch 30 sec each. Doorway chest opener 60 sec.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+stretch+cool+down+after+workout" },
        ],
        Friday: [
          { name:"Warm-Up: Light Cardio", sets:1, reps:"3 min", desc:"March in place, jumping jacks, torso twists. Full body warm-up before arms and core session.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+warm+up+cardio+home" },
          { name:"Close-Grip Push-Ups", sets:3, reps:"12 reps", desc:"Hands directly under shoulders. Emphasises triceps over chest. Month 1: 3x8 from knees. Month 2: 3x12 full. Month 3: 3x15 with 2-sec pause.", image:"", demo:"https://www.youtube.com/results?search_query=close+grip+push+ups+triceps" },
          { name:"Chair Dips", sets:3, reps:"12 reps", desc:"Hands on chair behind you. Lower until elbows 90 degrees, press up. Month 1: 3x10 bent knees. Month 2: 3x12 straight legs. Month 3: 3x15.", image:"", demo:"https://www.youtube.com/results?search_query=chair+dips+triceps+home+exercise" },
          { name:"Resistance Band Curls", sets:3, reps:"12 reps", desc:"Stand on band, curl hands toward shoulders. Month 1: light band 3x10. Month 2: 3x12. Month 3: heavy band 3x15.", image:"", demo:"https://www.youtube.com/results?search_query=resistance+band+bicep+curls+exercise" },
          { name:"Plank", sets:3, reps:"60 sec", desc:"Forearms on floor, body straight. Do not let lower back sag. Month 1: 3x30 sec. Month 2: 3x60 sec. Month 3: 3x90 sec.", image:"", demo:"https://www.youtube.com/results?search_query=plank+exercise+proper+form+core" },
          { name:"Russian Twists", sets:3, reps:"20 reps", desc:"Sit with knees bent, lean back slightly. Rotate torso side to side. Month 1: 3x16 feet on floor. Month 2: 3x20 feet lifted. Month 3: 3x24 with weight.", image:"", demo:"https://www.youtube.com/results?search_query=russian+twists+core+obliques+exercise" },
          { name:"Leg Raises", sets:3, reps:"12 reps", desc:"Lie on back. Raise straight legs to 90 degrees, lower slowly without touching floor. Month 1: 3x10 bent knees. Month 2: 3x12 straight. Month 3: 3x15.", image:"", demo:"https://www.youtube.com/results?search_query=leg+raises+lower+abs+exercise+form" },
          { name:"Cool-Down: Stretch Arms and Core", sets:1, reps:"2 min", desc:"Overhead tricep stretch 30 sec each arm. Bicep wall stretch 30 sec each. Lying spinal twist 30 sec each side.", image:"", demo:"https://www.youtube.com/results?search_query=arms+core+stretch+cool+down" },
        ],
        Saturday: [
          { name:"Warm-Up: Jump Rope or Shadow Skip", sets:1, reps:"3 min", desc:"Jump rope or mimic the motion. Full body activation before weekly full-body session.", image:"", demo:"https://www.youtube.com/results?search_query=jump+rope+warm+up+full+body" },
          { name:"Burpees", sets:3, reps:"10 reps", desc:"Stand, squat, jump feet back, push-up, jump feet forward, explosive jump overhead. Month 1: 3x6 no push-up. Month 2: 3x10 full. Month 3: 3x15 fast pace.", image:"", demo:"https://www.youtube.com/results?search_query=burpees+proper+form+full+body+exercise" },
          { name:"Squats", sets:3, reps:"15 reps", desc:"Full depth bodyweight squats. Drive knees out, chest up. Month 1: 3x12. Month 2: 3x15. Month 3: 3x20 jump squats.", image:"", demo:"https://www.youtube.com/results?search_query=bodyweight+squats+exercise+form" },
          { name:"Push-Ups", sets:3, reps:"12 reps", desc:"Standard push-ups. Full range of motion. Month 1: 3x10. Month 2: 3x12. Month 3: 3x15 or archer push-ups.", image:"", demo:"https://www.youtube.com/results?search_query=push+ups+exercise+form+chest" },
          { name:"Pull-Ups", sets:3, reps:"Max reps", desc:"Full hang pull to chin over bar. Month 1: 3x3-5 band. Month 2: 3x5-8. Month 3: 3x max.", image:"", demo:"https://www.youtube.com/results?search_query=pull+ups+full+range+of+motion+form" },
          { name:"Mountain Climbers", sets:3, reps:"30 sec", desc:"High plank, drive alternating knees toward chest rapidly. Month 1: 3x20 sec slow. Month 2: 3x30 sec. Month 3: 3x45 sec fast.", image:"", demo:"https://www.youtube.com/results?search_query=mountain+climbers+exercise+core+cardio" },
          { name:"Plank", sets:3, reps:"60 sec", desc:"Full plank hold to finish the week strong. Month 1: 3x30 sec. Month 2: 3x60 sec. Month 3: 3x90 sec.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+challenge+core" },
          { name:"Cool-Down: Full Body Stretch", sets:1, reps:"5 min", desc:"Quad stretch, hamstring fold, chest opener, spinal twist, child's pose, shoulder cross-body. Complete weekly recovery stretch.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+cool+down+stretch+after+workout" },
        ],
      }
      }
    },

    gym: {
      name: "Gym Workouts",
      emoji: "🏋️",
      color: "grad-gym",
      days: {
      days: {
        Monday: [
          { name:"Warm-Up: Treadmill + Mobility", sets:1, reps:"5-8 min", desc:"5 min light treadmill jog then chest mobility - arm circles, band pull-aparts, shoulder rolls. Prepares chest and shoulder joints for heavy pressing.", image:"", demo:"https://www.youtube.com/results?search_query=chest+day+warm+up+gym+mobility" },
          { name:"Bench Press", sets:4, reps:"10 reps", desc:"Grip bar 1.5x shoulder-width. Lower to mid-chest with control, press explosively. Month 1: 4x10 light-moderate. Month 2: 4x10 increase weight each set. Month 3: 4x8 heavier.", image:"", demo:"https://www.youtube.com/results?search_query=bench+press+proper+form+tutorial+barbell" },
          { name:"Incline Dumbbell Press", sets:3, reps:"10 reps", desc:"Bench at 30-45 degrees. Press dumbbells from chest upward. Targets upper chest. Month 1: 3x10 light. Month 2: 3x10 moderate. Month 3: 3x8 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=incline+dumbbell+press+upper+chest+form" },
          { name:"Chest Fly", sets:3, reps:"12 reps", desc:"Dumbbells above chest, slight elbow bend. Lower in arc until stretch, bring back squeezing chest. Month 1: 3x12 light. Month 2: 3x12 moderate. Month 3: 3x10 heavier with full stretch.", image:"", demo:"https://www.youtube.com/results?search_query=dumbbell+chest+fly+exercise+form" },
          { name:"Cable Crossover", sets:3, reps:"12 reps", desc:"High cable pulleys. Pull handles down and across in arc, hands meeting below chest. Month 1: 3x12 light. Month 2: 3x12. Month 3: 3x15 with 2-sec squeeze.", image:"", demo:"https://www.youtube.com/results?search_query=cable+crossover+chest+exercise+form" },
          { name:"Push-Ups to Failure", sets:3, reps:"Max reps", desc:"Standard push-ups after cable work as finisher. Month 1: 3x10. Month 2: 3x max. Month 3: 3x max with rest-pause.", image:"", demo:"https://www.youtube.com/results?search_query=push+ups+to+failure+chest+workout" },
          { name:"Decline Press", sets:3, reps:"10 reps", desc:"Decline bench 15-30 degrees. Targets lower chest. Month 1: 3x10 moderate. Month 2: 3x10 heavier. Month 3: 3x8 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=decline+bench+press+lower+chest+form" },
          { name:"Cool-Down: Chest Stretch", sets:1, reps:"2 min", desc:"Doorway chest stretch 45 sec. Cross-body shoulder stretch 30 sec each. Pec minor stretch on foam roller 30 sec.", image:"", demo:"https://www.youtube.com/results?search_query=chest+stretch+after+chest+day+gym" },
        ],
        Tuesday: [
          { name:"Warm-Up: Rowing Machine", sets:1, reps:"5 min", desc:"Light rowing to warm up lats, rhomboids and biceps. Perfect back day activation.", image:"", demo:"https://www.youtube.com/results?search_query=rowing+machine+warm+up+back+day" },
          { name:"Lat Pulldown", sets:3, reps:"10 reps", desc:"Wide overhand grip. Pull bar to upper chest, lean slightly back, squeeze lats. Month 1: 3x10 moderate. Month 2: 3x10 heavier. Month 3: 3x8 heavy + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=lat+pulldown+proper+form+wide+grip" },
          { name:"Barbell Row", sets:3, reps:"10 reps", desc:"Hip-width stance, hinge 45 degrees. Pull bar to lower chest, squeeze shoulder blades. Month 1: 3x10 light. Month 2: 3x10 moderate. Month 3: 3x8 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+bent+over+row+form+tutorial" },
          { name:"Seated Cable Row", sets:3, reps:"12 reps", desc:"Neutral grip. Pull to navel keeping chest tall. Full stretch front, full squeeze back. Month 1: 3x12 light. Month 2: 3x12 moderate. Month 3: 3x10 heavier with 1-sec hold.", image:"", demo:"https://www.youtube.com/results?search_query=seated+cable+row+form+back+exercise" },
          { name:"Deadlift", sets:3, reps:"8 reps", desc:"Feet hip-width, bar over laces. Push floor away keeping bar close. Lock out hips and knees. Month 1: 3x8 technique focus. Month 2: 3x8 moderate. Month 3: 3x6 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=deadlift+proper+form+tutorial+beginners" },
          { name:"Face Pull", sets:3, reps:"12 reps", desc:"Cable at head height with rope. Pull to face, elbows high and wide. Rear delt and rotator cuff. Month 1: 3x15 light. Month 2: 3x12. Month 3: 3x15 with 1-sec hold.", image:"", demo:"https://www.youtube.com/results?search_query=face+pull+exercise+form+rear+delt" },
          { name:"Pull-Ups to Failure", sets:3, reps:"Max reps", desc:"Full hang to chin over bar. Month 1: 3x5 band assisted. Month 2: 3x max unassisted. Month 3: 3x max weighted.", image:"", demo:"https://www.youtube.com/results?search_query=pull+ups+max+reps+back+finisher" },
          { name:"Cool-Down: Back Stretch", sets:1, reps:"2 min", desc:"Child's pose 60 sec. Cat-cow 10 reps. Seated twist 30 sec each side. Thoracic foam rolling 60 sec.", image:"", demo:"https://www.youtube.com/results?search_query=back+stretch+cool+down+after+back+day+gym" },
        ],
        Wednesday: [
          { name:"Warm-Up: Stationary Bike", sets:1, reps:"5 min", desc:"Light cycling to pump blood into legs and lubricate knee and hip joints. Add bodyweight squats after.", image:"", demo:"https://www.youtube.com/results?search_query=leg+day+warm+up+stationary+bike+gym" },
          { name:"Barbell Squat", sets:4, reps:"10 reps", desc:"Bar on traps, feet shoulder-width. Squat until thighs parallel, drive through heels. Month 1: 4x10 technique focus. Month 2: 4x10 heavier. Month 3: 4x8 heavy with belt.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+squat+proper+form+tutorial+gym" },
          { name:"Leg Press", sets:3, reps:"12 reps", desc:"Feet shoulder-width on platform. Lower sled until 90 degree knee angle, do not lock out. Month 1: 3x12 moderate. Month 2: 3x12 heavier. Month 3: 3x15 + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=leg+press+machine+proper+form+tutorial" },
          { name:"Lunges", sets:3, reps:"12 each leg", desc:"Walking or stationary with dumbbells. Knee over ankle, back knee nearly touches floor. Month 1: 3x10 bodyweight. Month 2: 3x12 light DBs. Month 3: 3x12 heavy DBs.", image:"", demo:"https://www.youtube.com/results?search_query=dumbbell+lunges+form+gym+leg+exercise" },
          { name:"Leg Curl", sets:3, reps:"12 reps", desc:"Lying or seated machine. Curl heel toward glute through full range. Month 1: 3x12 moderate. Month 2: 3x12 heavier. Month 3: 3x10 heavy + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=leg+curl+machine+hamstring+form" },
          { name:"Leg Extension", sets:3, reps:"12 reps", desc:"Machine. Extend legs to full lockout, squeeze quads at top. Month 1: 3x12 moderate. Month 2: 3x12. Month 3: 3x15 + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=leg+extension+machine+quad+form+tutorial" },
          { name:"Calf Raises", sets:4, reps:"15 reps", desc:"Standing calf raise machine or step edge. Rise to tiptoes, hold 1 sec, lower slowly. Month 1: 4x15. Month 2: 4x15 heavier. Month 3: 4x20 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=standing+calf+raise+machine+form" },
          { name:"Cool-Down: Leg Stretch", sets:1, reps:"3 min", desc:"Quad stretch 30 sec each. Hamstring seated 30 sec each. Hip flexor lunge 30 sec each. Calf wall stretch 30 sec each.", image:"", demo:"https://www.youtube.com/results?search_query=leg+day+cool+down+stretches+gym" },
        ],
        Thursday: [
          { name:"Warm-Up: Shoulder Mobility", sets:1, reps:"5 min", desc:"Band pull-aparts 3x15, wall slides 2x10, arm circles 30 sec each direction. Critical before heavy overhead pressing.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+day+warm+up+mobility+exercises" },
          { name:"Overhead Press", sets:3, reps:"10 reps", desc:"Barbell from front rack. Press to lockout overhead, core braced. Month 1: 3x10 light-moderate. Month 2: 3x10 heavier. Month 3: 3x8 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+overhead+press+form+tutorial" },
          { name:"Lateral Raise", sets:3, reps:"12 reps", desc:"DB lateral raises to shoulder height, slight elbow bend, thumbs slightly down. Builds shoulder width. Month 1: 3x12 light strict form. Month 2: 3x12 moderate. Month 3: 3x15 + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=dumbbell+lateral+raise+shoulder+form" },
          { name:"Front Raise", sets:3, reps:"12 reps", desc:"Alternate or bilateral DB front raises to shoulder height. Targets anterior deltoid. Month 1: 3x12 light. Month 2: 3x12. Month 3: 3x12 cable for constant tension.", image:"", demo:"https://www.youtube.com/results?search_query=dumbbell+front+raise+anterior+deltoid+form" },
          { name:"Rear Delt Fly", sets:3, reps:"12 reps", desc:"Bent over 45 degrees, raise DBs to sides, pinkies up. Month 1: 3x12 light. Month 2: 3x12 moderate. Month 3: 3x15 cable rear fly.", image:"", demo:"https://www.youtube.com/results?search_query=rear+delt+fly+dumbbell+bent+over+form" },
          { name:"Arnold Press", sets:3, reps:"10 reps", desc:"Start DBs at chin level palms facing you. Press overhead rotating palms forward. Works all 3 deltoid heads. Month 1: 3x10 light. Month 2: 3x10 moderate. Month 3: 3x10 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=arnold+press+form+tutorial+all+deltoid+heads" },
          { name:"Shrugs", sets:3, reps:"12 reps", desc:"Heavy barbell or dumbbells. Shrug shoulders straight up, hold 1 sec. Builds upper traps. Month 1: 3x12 moderate. Month 2: 3x12 heavy. Month 3: 3x15 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+shrugs+upper+trap+exercise+form" },
          { name:"Cool-Down: Shoulder Stretch", sets:1, reps:"2 min", desc:"Cross-body stretch 30 sec each. Overhead tricep stretch 30 sec each. Doorway pec stretch 60 sec. Neck rolls 30 sec.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+cool+down+stretch+after+shoulder+day" },
        ],
        Friday: [
          { name:"Warm-Up: Light Curls", sets:1, reps:"2 min", desc:"Very light barbell curls and band tricep pushdowns. Warms elbow joint and gets blood into biceps and triceps.", image:"", demo:"https://www.youtube.com/results?search_query=arm+day+warm+up+light+curls+tricep" },
          { name:"Barbell Curl", sets:3, reps:"10 reps", desc:"EZ or straight bar. Full range - arms straight at bottom, squeeze hard at top. Month 1: 3x10 moderate. Month 2: 3x10 heavier. Month 3: 3x8 heavy + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+curl+biceps+proper+form+tutorial" },
          { name:"Hammer Curl", sets:3, reps:"10 reps", desc:"Neutral grip (thumbs up). Curl without supinating. Targets brachialis for thick arm. Month 1: 3x10. Month 2: 3x10 heavier. Month 3: 3x12 cross-body variation.", image:"", demo:"https://www.youtube.com/results?search_query=hammer+curl+proper+form+brachialis" },
          { name:"Tricep Pushdown", sets:3, reps:"12 reps", desc:"Cable at shoulder height, rope or bar. Push to full lockout. Month 1: 3x12 moderate. Month 2: 3x12. Month 3: 3x15 + drop set.", image:"", demo:"https://www.youtube.com/results?search_query=tricep+pushdown+cable+rope+form+tutorial" },
          { name:"Skull Crushers", sets:3, reps:"10 reps", desc:"EZ bar lying on bench. Lower toward forehead with fixed elbows, extend back up. Month 1: 3x10 light. Month 2: 3x10 moderate. Month 3: 3x8 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=skull+crushers+ez+bar+triceps+form" },
          { name:"Concentration Curl", sets:3, reps:"10 reps", desc:"Seated, elbow on inner thigh. Curl dumbbell with full squeeze at top. Month 1: 3x10 light. Month 2: 3x10 moderate. Month 3: 3x12 with 2-sec squeeze.", image:"", demo:"https://www.youtube.com/results?search_query=concentration+curl+peak+bicep+exercise" },
          { name:"Dips to Failure", sets:3, reps:"Max reps", desc:"Parallel bars. Full depth, elbows at 90 degrees. Month 1: 3x8 band assisted. Month 2: 3x max bodyweight. Month 3: 3x max weighted.", image:"", demo:"https://www.youtube.com/results?search_query=parallel+bar+dips+triceps+form+tutorial" },
          { name:"Cool-Down: Arm Stretch", sets:1, reps:"2 min", desc:"Overhead tricep stretch 30 sec each. Bicep wall stretch 30 sec each. Wrist flexor and extensor stretch 30 sec each.", image:"", demo:"https://www.youtube.com/results?search_query=arm+day+cool+down+stretches+bicep+tricep" },
        ],
        Saturday: [
          { name:"Warm-Up: Cardio", sets:1, reps:"5 min", desc:"5 min rowing, treadmill or bike. Full body activation before the weekly full-body compound session.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+gym+warm+up+cardio" },
          { name:"Deadlift", sets:3, reps:"8 reps", desc:"Full deadlift. Hip hinge, bar close to body, lock out fully. Month 1: 3x8 moderate. Month 2: 3x8 heavier. Month 3: 3x6 heavy.", image:"", demo:"https://www.youtube.com/results?search_query=deadlift+form+full+body+workout" },
          { name:"Bench Press", sets:3, reps:"10 reps", desc:"Full bench press at moderate weight. Month 1: 3x10 light. Month 2: 3x10 moderate. Month 3: 3x10 moderate-heavy.", image:"", demo:"https://www.youtube.com/results?search_query=bench+press+full+body+workout" },
          { name:"Lat Pulldown", sets:3, reps:"10 reps", desc:"Wide grip, squeeze lats fully at bottom. Month 1: 3x10 moderate. Month 2: 3x10. Month 3: 3x10 heavier.", image:"", demo:"https://www.youtube.com/results?search_query=lat+pulldown+full+body+workout" },
          { name:"Barbell Squat", sets:3, reps:"10 reps", desc:"Full barbell squat at moderate weight. Month 1: 3x10 light-moderate. Month 2: 3x10 moderate. Month 3: 3x10 moderate-heavy.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+squat+full+body+day" },
          { name:"Plank", sets:3, reps:"60 sec", desc:"Core finisher. Forearms down, body straight. Month 1: 3x30 sec. Month 2: 3x60 sec. Month 3: 3x90 sec.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+gym+core+exercise" },
          { name:"Crunches", sets:3, reps:"15 reps", desc:"Lying on back, knees bent. Curl shoulders toward knees, squeeze abs. Month 1: 3x15. Month 2: 3x20. Month 3: 3x25 or weighted.", image:"", demo:"https://www.youtube.com/results?search_query=crunches+ab+exercise+proper+form" },
          { name:"Cool-Down: Full Stretch", sets:1, reps:"5 min", desc:"Quad stretch, hamstring, chest opener, lat side stretch, hip flexor, spinal twist. Complete weekly stretch.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+cool+down+stretch+gym+after+workout" },
        ],
      }
      }
    },

    yoga: {
      name: "Yoga",
      emoji: "🧘",
      color: "grad-yoga",
      days: {
        Monday: [
          { name:"Sun Salutation A", sets:3, reps:"5 rounds", desc:"Mountain → Forward Fold → Halfway Lift → Plank → Cobra → Downdog.", image:"", demo:"https://www.youtube.com/results?search_query=sun+salutation+A+yoga" },
          { name:"Warrior I", sets:3, reps:"45 sec each", desc:"Front knee bent 90°, back leg straight, arms reach overhead.", image:"", demo:"https://www.youtube.com/results?search_query=warrior+1+yoga+pose" },
          { name:"Warrior II", sets:3, reps:"45 sec each", desc:"Wide stance, front knee over ankle, arms parallel to floor.", image:"", demo:"https://www.youtube.com/results?search_query=warrior+2+yoga+pose" },
          { name:"Tree Pose", sets:3, reps:"30 sec each", desc:"Balance on one leg, foot on inner thigh. Hands at heart or overhead.", image:"", demo:"https://www.youtube.com/results?search_query=tree+pose+yoga" },
          { name:"Child's Pose", sets:3, reps:"60 sec", desc:"Kneel, extend arms forward, rest forehead on mat.", image:"", demo:"https://www.youtube.com/results?search_query=child's+pose+yoga" },
          { name:"Savasana", sets:1, reps:"3 min", desc:"Complete relaxation on back. Allow body to absorb the practice.", image:"", demo:"https://www.youtube.com/results?search_query=savasana+yoga" },
        ],
        Tuesday: [
          { name:"Cat-Cow", sets:3, reps:"10 rounds", desc:"Alternate arching and rounding spine with breath.", image:"", demo:"https://www.youtube.com/results?search_query=cat+cow+yoga" },
          { name:"Downward Dog", sets:3, reps:"60 sec", desc:"Inverted V shape. Press hands and feet into mat.", image:"", demo:"https://www.youtube.com/results?search_query=downward+dog+yoga" },
          { name:"Pigeon Pose", sets:3, reps:"60 sec each", desc:"Deep hip opener. Front shin parallel to mat, back leg extended.", image:"", demo:"https://www.youtube.com/results?search_query=pigeon+pose+yoga" },
          { name:"Seated Forward Fold", sets:3, reps:"60 sec", desc:"Legs extended, hinge forward from hips.", image:"", demo:"https://www.youtube.com/results?search_query=seated+forward+fold+yoga" },
          { name:"Supine Twist", sets:3, reps:"45 sec each", desc:"Lie on back, knee across body, arms wide.", image:"", demo:"https://www.youtube.com/results?search_query=supine+spinal+twist+yoga" },
          { name:"Legs Up The Wall", sets:1, reps:"3 min", desc:"Passive inversion. Legs vertical against wall.", image:"", demo:"https://www.youtube.com/results?search_query=legs+up+wall+yoga" },
        ],
        Wednesday: [
          { name:"Triangle Pose", sets:3, reps:"45 sec each", desc:"Wide stance, extend over front leg, hand to shin or floor.", image:"", demo:"https://www.youtube.com/results?search_query=triangle+pose+yoga" },
          { name:"Boat Pose", sets:3, reps:"30 sec", desc:"Balance on sit bones, legs and torso form a V.", image:"", demo:"https://www.youtube.com/results?search_query=boat+pose+yoga" },
          { name:"Camel Pose", sets:3, reps:"30 sec", desc:"Kneeling back bend. Hands on heels. Opens chest.", image:"", demo:"https://www.youtube.com/results?search_query=camel+pose+yoga" },
          { name:"Extended Side Angle", sets:3, reps:"45 sec each", desc:"Front arm rests on thigh or floor, back arm stretches overhead.", image:"", demo:"https://www.youtube.com/results?search_query=extended+side+angle+yoga" },
          { name:"Bridge Pose", sets:3, reps:"45 sec", desc:"Lie on back, feet flat, lift hips. Squeeze glutes.", image:"", demo:"https://www.youtube.com/results?search_query=bridge+pose+yoga" },
          { name:"Happy Baby", sets:1, reps:"2 min", desc:"Lie on back, hold outer feet. Rock gently side to side.", image:"", demo:"https://www.youtube.com/results?search_query=happy+baby+pose+yoga" },
        ],
        Thursday: [
          { name:"Chair Pose", sets:3, reps:"45 sec", desc:"Feet together, sit back as if on invisible chair.", image:"", demo:"https://www.youtube.com/results?search_query=chair+pose+yoga" },
          { name:"Eagle Pose", sets:3, reps:"30 sec each", desc:"One leg wrapped around other, arms intertwined.", image:"", demo:"https://www.youtube.com/results?search_query=eagle+pose+yoga" },
          { name:"Half Moon Pose", sets:3, reps:"30 sec each", desc:"Balance on one leg and hand. Other arm and leg extend.", image:"", demo:"https://www.youtube.com/results?search_query=half+moon+pose+yoga" },
          { name:"Wide-Leg Forward Fold", sets:3, reps:"60 sec", desc:"Feet wide, fold forward, head toward floor.", image:"", demo:"https://www.youtube.com/results?search_query=wide+legged+forward+fold+yoga" },
          { name:"Fish Pose", sets:3, reps:"30 sec", desc:"On back, arch thoracic spine, crown of head on mat.", image:"", demo:"https://www.youtube.com/results?search_query=fish+pose+yoga" },
          { name:"Corpse Pose Extended", sets:1, reps:"4 min", desc:"Extended Savasana with body scan meditation.", image:"", demo:"https://www.youtube.com/results?search_query=savasana+body+scan+yoga" },
        ],
        Friday: [
          { name:"Crow Pose Prep", sets:3, reps:"5 attempts", desc:"Squat, place knees on upper arms, lean forward and find balance.", image:"", demo:"https://www.youtube.com/results?search_query=crow+pose+yoga+beginners" },
          { name:"Plank to Chaturanga", sets:3, reps:"10 reps", desc:"High plank, lower with elbows hugging body.", image:"", demo:"https://www.youtube.com/results?search_query=chaturanga+yoga+form" },
          { name:"Cobra Pose", sets:3, reps:"30 sec", desc:"Lie prone, place hands under shoulders. Press up, elbows soft.", image:"", demo:"https://www.youtube.com/results?search_query=cobra+pose+yoga" },
          { name:"Lizard Pose", sets:3, reps:"45 sec each", desc:"Low lunge with front foot outside hand. Deep hip flexor stretch.", image:"", demo:"https://www.youtube.com/results?search_query=lizard+pose+yoga" },
          { name:"Headstand Prep", sets:3, reps:"30 sec", desc:"Forearms on mat, crown on mat, hips lift (dolphin pose).", image:"", demo:"https://www.youtube.com/results?search_query=headstand+prep+yoga" },
          { name:"Meditation Sit", sets:1, reps:"5 min", desc:"Comfortable seated position. Focus on breath.", image:"", demo:"https://www.youtube.com/results?search_query=yoga+meditation+breathing" },
        ],
        Saturday: [
          { name:"Full Flow Practice", sets:1, reps:"20 min", desc:"Freestyle: combine all learned poses.", image:"", demo:"https://www.youtube.com/results?search_query=20+minute+yoga+flow+full+body" },
          { name:"Yin Hip Sequence", sets:1, reps:"5 min", desc:"Hold each hip-opening pose for 1 minute: Dragon, Shoelace, Frog.", image:"", demo:"https://www.youtube.com/results?search_query=yin+yoga+hips" },
          { name:"Shoulder Opener", sets:3, reps:"45 sec each", desc:"Thread-the-needle, shoulder-to-floor stretches.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+opener+yoga" },
          { name:"Restorative Child's Pose", sets:1, reps:"3 min", desc:"Supported with blanket under torso.", image:"", demo:"https://www.youtube.com/results?search_query=restorative+yoga+childs+pose" },
          { name:"Seated Meditation", sets:1, reps:"10 min", desc:"Eyes closed, breath awareness, body scan.", image:"", demo:"https://www.youtube.com/results?search_query=10+minute+guided+meditation" },
          { name:"Gratitude Journaling", sets:1, reps:"5 min", desc:"Write 3 things you're grateful for and 1 fitness win this week.", image:"", demo:"" },
        ],
      }
    },

    stretching: {
      name: "Stretching",
      emoji: "🤸",
      color: "grad-stretch",
      days: {
        Monday: [
          { name:"Neck Rolls", sets:3, reps:"5 each dir", desc:"Slowly roll head in full circles. Never force the movement.", image:"", demo:"https://www.youtube.com/results?search_query=neck+rolls+stretch" },
          { name:"Chest Opener Stretch", sets:3, reps:"45 sec", desc:"Clasp hands behind back, open chest, lift chin.", image:"", demo:"https://www.youtube.com/results?search_query=chest+opener+stretch" },
          { name:"Hip Flexor Lunge", sets:3, reps:"45 sec each", desc:"Low lunge, front knee 90°. Push hips forward and down.", image:"", demo:"https://www.youtube.com/results?search_query=hip+flexor+lunge+stretch" },
          { name:"Standing Hamstring Stretch", sets:3, reps:"40 sec each", desc:"Foot on ledge, hinge forward from hips.", image:"", demo:"https://www.youtube.com/results?search_query=standing+hamstring+stretch" },
          { name:"Quad Stretch", sets:3, reps:"30 sec each", desc:"Standing, pull foot to glute.", image:"", demo:"https://www.youtube.com/results?search_query=standing+quad+stretch" },
          { name:"Calf Stretch", sets:3, reps:"30 sec each", desc:"Heel on floor, lean forward.", image:"", demo:"https://www.youtube.com/results?search_query=calf+stretch+wall" },
        ],
        Tuesday: [
          { name:"Doorway Chest Stretch", sets:3, reps:"45 sec", desc:"Hands on doorframe, lean forward.", image:"", demo:"https://www.youtube.com/results?search_query=doorway+chest+stretch" },
          { name:"Thoracic Rotation", sets:3, reps:"10 each", desc:"Seated, rotate upper body left and right.", image:"", demo:"https://www.youtube.com/results?search_query=thoracic+rotation+stretch" },
          { name:"Seated Pigeon", sets:3, reps:"60 sec each", desc:"Ankle on opposite knee (figure 4). Lean forward.", image:"", demo:"https://www.youtube.com/results?search_query=seated+pigeon+pose+stretch" },
          { name:"IT Band Stretch", sets:3, reps:"45 sec each", desc:"Cross one leg behind other, lean sideways.", image:"", demo:"https://www.youtube.com/results?search_query=IT+band+stretch" },
          { name:"Wrist and Forearm Stretch", sets:3, reps:"30 sec each", desc:"Extend arm, bend wrist down and up.", image:"", demo:"https://www.youtube.com/results?search_query=wrist+forearm+stretch" },
          { name:"Ankle Circles", sets:3, reps:"10 each dir", desc:"Slow ankle rotations in both directions.", image:"", demo:"https://www.youtube.com/results?search_query=ankle+circles+mobility" },
        ],
        Wednesday: [
          { name:"Butterfly Stretch", sets:3, reps:"60 sec", desc:"Soles of feet together, lean forward gently.", image:"", demo:"https://www.youtube.com/results?search_query=butterfly+stretch" },
          { name:"Figure 4 Glute Stretch", sets:3, reps:"60 sec each", desc:"Lying on back, figure-4 with legs.", image:"", demo:"https://www.youtube.com/results?search_query=figure+4+glute+stretch" },
          { name:"Child's Pose with Reach", sets:3, reps:"45 sec each", desc:"Child's pose, walk hands to each side.", image:"", demo:"https://www.youtube.com/results?search_query=child's+pose+side+stretch" },
          { name:"Standing Side Stretch", sets:3, reps:"30 sec each", desc:"Arm overhead, reach and lean to opposite side.", image:"", demo:"https://www.youtube.com/results?search_query=standing+side+stretch" },
          { name:"Spinal Twist Seated", sets:3, reps:"45 sec each", desc:"Seated, one leg extended. Cross other foot over. Rotate toward bent knee.", image:"", demo:"https://www.youtube.com/results?search_query=seated+spinal+twist" },
          { name:"90-90 Hip Stretch", sets:3, reps:"60 sec each", desc:"Both legs at 90° angles on floor.", image:"", demo:"https://www.youtube.com/results?search_query=90+90+hip+stretch" },
        ],
        Thursday: [
          { name:"Shoulder Cross-Body Stretch", sets:3, reps:"30 sec each", desc:"Pull arm across chest.", image:"", demo:"https://www.youtube.com/results?search_query=cross+body+shoulder+stretch" },
          { name:"Bicep Wall Stretch", sets:3, reps:"30 sec each", desc:"Hand flat on wall at shoulder height, rotate away.", image:"", demo:"https://www.youtube.com/results?search_query=bicep+wall+stretch" },
          { name:"Lying Hamstring Stretch", sets:3, reps:"45 sec each", desc:"On back, loop band/towel around foot, extend leg.", image:"", demo:"https://www.youtube.com/results?search_query=lying+hamstring+stretch+band" },
          { name:"Frog Stretch", sets:3, reps:"60 sec", desc:"On all fours, knees wide, rock back.", image:"", demo:"https://www.youtube.com/results?search_query=frog+stretch" },
          { name:"Upper Trap Stretch", sets:3, reps:"30 sec each", desc:"Tilt head to one side, hold with hand.", image:"", demo:"https://www.youtube.com/results?search_query=upper+trap+stretch" },
          { name:"Thoracic Extension on Foam Roll", sets:3, reps:"60 sec", desc:"Foam roller perpendicular to spine. Extend over roller at different segments.", image:"", demo:"https://www.youtube.com/results?search_query=thoracic+extension+foam+roller" },
        ],
        Friday: [
          { name:"Full Body Stretch Sequence", sets:1, reps:"15 min", desc:"Guided head-to-toe stretch.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+stretch+sequence" },
          { name:"Couch Stretch", sets:3, reps:"60 sec each", desc:"Rear foot elevated, front foot forward. Deepest hip flexor stretch.", image:"", demo:"https://www.youtube.com/results?search_query=couch+stretch+hip+flexor" },
          { name:"Pancake Stretch", sets:3, reps:"60 sec", desc:"Straddle position, fold forward.", image:"", demo:"https://www.youtube.com/results?search_query=pancake+stretch" },
          { name:"Shoulder Capsule Stretch", sets:3, reps:"30 sec each", desc:"Arm across chest in horizontal position.", image:"", demo:"https://www.youtube.com/results?search_query=posterior+shoulder+capsule+stretch" },
          { name:"Active Lunge Stretch", sets:3, reps:"10 each", desc:"Dynamic lunge with rotation.", image:"", demo:"https://www.youtube.com/results?search_query=lunge+with+twist+stretch" },
          { name:"Box Breathing Cooldown", sets:1, reps:"5 min", desc:"Inhale 4 sec, hold 4 sec, exhale 4 sec, hold 4 sec.", image:"", demo:"https://www.youtube.com/results?search_query=box+breathing+technique" },
        ],
        Saturday: [
          { name:"Yin Style Full Body", sets:1, reps:"20 min", desc:"Hold each stretch 2-3 minutes.", image:"", demo:"https://www.youtube.com/results?search_query=yin+yoga+full+body+20+minutes" },
          { name:"PNF Hamstring", sets:3, reps:"3 cycles each", desc:"Stretch, contract 6 sec, stretch further.", image:"", demo:"https://www.youtube.com/results?search_query=PNF+hamstring+stretch" },
          { name:"Hip Circle Mobility", sets:3, reps:"10 each dir", desc:"Wide stance, rotate hips in large circles.", image:"", demo:"https://www.youtube.com/results?search_query=hip+circle+mobility" },
          { name:"Overhead Tricep Stretch", sets:3, reps:"30 sec each", desc:"Arm overhead, elbow bent. Push elbow back with other hand.", image:"", demo:"https://www.youtube.com/results?search_query=overhead+tricep+stretch" },
          { name:"Anterior Tib Stretch", sets:3, reps:"30 sec each", desc:"Kneel, top of foot on floor. Sit back on heels.", image:"", demo:"https://www.youtube.com/results?search_query=anterior+tibialis+stretch" },
          { name:"Total Body Relax", sets:1, reps:"5 min", desc:"Lie still, progressive muscle relaxation.", image:"", demo:"https://www.youtube.com/results?search_query=progressive+muscle+relaxation" },
        ],
      }
    },
  },

  running: {
    plans: {
      "5K":  { color:"#43a05a", emoji:"🏃", weeks:6, desc:"Beginner-friendly. Build from 2km to 5km in 6 weeks.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:2,dur:20,desc:"Very easy pace. Hold a conversation. Just get moving."},
        {week:1,day:2,type:"Run/Walk",dist:2,dur:25,desc:"Run 2 min, walk 1 min. Repeat 6 times. Focus on breathing."},
        {week:1,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Rest or light cross-training. Let your legs recover."},
        {week:1,day:4,type:"Easy Run",dist:2,dur:20,desc:"Same as Day 1. Easy pace. Build the habit."},
        {week:1,day:5,type:"Rest",dist:0,dur:0,desc:"Full rest day. Sleep well, stay hydrated."},
        {week:1,day:6,type:"Long Run",dist:3,dur:30,desc:"Your longest run this week. Slow and steady."},
        {week:1,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy 30-minute walk. Loosens up muscles."},
        {week:2,day:1,type:"Easy Run",dist:2.5,dur:25,desc:"Slightly longer. Keep it conversational."},
        {week:2,day:2,type:"Run/Walk",dist:2.5,dur:28,desc:"Run 3 min, walk 1 min. Repeat 6 times."},
        {week:2,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Light cross-training or full rest."},
        {week:2,day:4,type:"Easy Run",dist:2.5,dur:25,desc:"Easy 2.5km. Focus on relaxed arms."},
        {week:2,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. Eat well and get 8 hours sleep."},
        {week:2,day:6,type:"Long Run",dist:3.5,dur:35,desc:"3.5km continuous if possible. Walk breaks fine."},
        {week:2,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Gentle walk. 30 minutes at leisure pace."},
        {week:3,day:1,type:"Easy Run",dist:3,dur:28,desc:"3km easy. Notice how much better it feels vs week 1!"},
        {week:3,day:2,type:"Run/Walk Intervals",dist:3,dur:30,desc:"Run 4 min, walk 1 min. Repeat 5 times."},
        {week:3,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Cross-training or rest. Try squats and lunges."},
        {week:3,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Try to run whole thing without walking."},
        {week:3,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Your body is adapting."},
        {week:3,day:6,type:"Long Run",dist:4,dur:40,desc:"Your first 4km! Take it slow. Big milestone!"},
        {week:3,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk. Stretch hip flexors and hamstrings."},
        {week:4,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Getting more natural now."},
        {week:4,day:2,type:"Intervals",dist:3,dur:30,desc:"6 x 1 min fast, 2 min easy jog. First speed work!"},
        {week:4,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Rest or cross-training. Core exercises today."},
        {week:4,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km recovery run after intervals."},
        {week:4,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. 4 weeks in - fantastic commitment!"},
        {week:4,day:6,type:"Long Run",dist:4.5,dur:45,desc:"4.5km. Almost at your goal distance!"},
        {week:4,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"30-minute walk. Hydrate well."},
        {week:5,day:1,type:"Easy Run",dist:3.5,dur:33,desc:"Easy 3.5km. Building for the final push."},
        {week:5,day:2,type:"Intervals",dist:3,dur:30,desc:"8 x 1 min fast, 90 sec easy. Getting fit!"},
        {week:5,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Light cross-training or rest. Yoga perfect today."},
        {week:5,day:4,type:"Easy Run",dist:3.5,dur:33,desc:"Easy 3.5km. Save energy for the long run."},
        {week:5,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. Race is one week away. Believe in training."},
        {week:5,day:6,type:"Long Run",dist:5,dur:50,desc:"YOUR FIRST 5K! Run the full distance. You did it!"},
        {week:5,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk. Celebrate - you ran 5K!"},
        {week:6,day:1,type:"Easy Run",dist:3,dur:28,desc:"Short easy run to keep legs fresh."},
        {week:6,day:2,type:"Run/Walk",dist:2,dur:20,desc:"Very easy 20 mins. Saving energy for race day."},
        {week:6,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or full rest."},
        {week:6,day:4,type:"Easy Run",dist:2,dur:18,desc:"15-20 min shakeout. Just keeping legs moving."},
        {week:6,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Lay out race gear. Sleep early."},
        {week:6,day:6,type:"RACE DAY! 🏆",dist:5,dur:0,desc:"THIS IS IT! Start easy, find rhythm, finish strong!"},
        {week:6,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Post-race recovery. You are a 5K runner!"},
      ]},
      "10K": { color:"#1e88e5", emoji:"🏃‍♂️", weeks:8, desc:"For runners who can run 5K. Double the distance in 8 weeks.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:4,dur:38,desc:"Comfortable 4km base run. Easy conversational pace."},
        {week:1,day:2,type:"Speed Workout",dist:4,dur:40,desc:"6 x 400m at 5K pace with 200m jog recovery."},
        {week:1,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or strength training. Squats, lunges, bridges."},
        {week:1,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min comfortably hard, 10 min easy."},
        {week:1,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. Full recovery. Stretch and foam roll."},
        {week:1,day:6,type:"Long Run",dist:6,dur:58,desc:"First long run. Easy steady pace. Full 6km."},
        {week:1,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Very easy 2km recovery jog."},
        {week:2,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Building aerobic base."},
        {week:2,day:2,type:"Speed Workout",dist:4.5,dur:45,desc:"8 x 400m at 5K pace. One more rep!"},
        {week:2,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest. Single-leg exercises."},
        {week:2,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy."},
        {week:2,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Muscles repair and grow stronger."},
        {week:2,day:6,type:"Long Run",dist:7,dur:67,desc:"7km long run. Slow is fine."},
        {week:2,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy 2km shakeout."},
        {week:3,day:1,type:"Easy Run",dist:5,dur:47,desc:"5km easy. Getting easier each week."},
        {week:3,day:2,type:"Speed Workout",dist:5,dur:50,desc:"10 x 400m at 5K pace. Great workout!"},
        {week:3,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Add calf raises and core work."},
        {week:3,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 25 min tempo, 5 min cool-down."},
        {week:3,day:5,type:"Rest",dist:0,dur:0,desc:"Full rest. Halfway through - great work!"},
        {week:3,day:6,type:"Long Run",dist:8,dur:76,desc:"8km. A big milestone! Very easy pace."},
        {week:3,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy recovery jog."},
        {week:4,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Cutback week."},
        {week:4,day:2,type:"Speed Workout",dist:4,dur:40,desc:"6 x 400m at 5K pace. Cutback volume."},
        {week:4,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or light strength. Mobility focus."},
        {week:4,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min tempo, 10 min easy."},
        {week:4,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Cutback week - trust the process."},
        {week:4,day:6,type:"Long Run",dist:7,dur:67,desc:"7km cutback long run."},
        {week:4,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy jog. Feeling fresh? Good!"},
        {week:5,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Back to building!"},
        {week:5,day:2,type:"Speed Workout",dist:5,dur:50,desc:"5 x 800m at 5K pace. Longer intervals!"},
        {week:5,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest. Core and glutes."},
        {week:5,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 30 min tempo, 5 min easy."},
        {week:5,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Race day is 3 weeks away."},
        {week:5,day:6,type:"Long Run",dist:9,dur:86,desc:"9km! Nearly at race distance."},
        {week:5,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy 2km shakeout."},
        {week:6,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Peak training week!"},
        {week:6,day:2,type:"Speed Workout",dist:5,dur:52,desc:"6 x 800m at 5K pace. Flying!"},
        {week:6,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or light strength."},
        {week:6,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 30 min tempo, 10 min easy."},
        {week:6,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Peak week done. Now we taper."},
        {week:6,day:6,type:"Long Run",dist:10,dur:95,desc:"FIRST 10K! Race day just 2 weeks away!"},
        {week:6,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy jog. You just ran 10K. Incredible!"},
        {week:7,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper week."},
        {week:7,day:2,type:"Speed Workout",dist:3,dur:30,desc:"4 x 400m at race pace. Short and sharp."},
        {week:7,day:3,type:"Rest/Strength",dist:0,dur:20,desc:"Light stretching or rest."},
        {week:7,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min tempo, 10 min easy."},
        {week:7,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Trust your training."},
        {week:7,day:6,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Last longer run before race week."},
        {week:7,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Short easy jog. Almost race day!"},
        {week:8,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Race week - keep it light."},
        {week:8,day:2,type:"Strides",dist:2,dur:20,desc:"Easy 2km with 4 x 20-sec strides at race pace."},
        {week:8,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or rest."},
        {week:8,day:4,type:"Easy Run",dist:2,dur:18,desc:"Easy 15-20 min shakeout."},
        {week:8,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Lay out gear. Sleep early."},
        {week:8,day:6,type:"RACE DAY! 🏆",dist:10,dur:0,desc:"10K RACE DAY! Start easy, build, finish strong!"},
        {week:8,day:7,type:"Recovery Jog",dist:1,dur:10,desc:"Easy jog or walk. You are a 10K runner!"},
      ]},
      "HM":  { color:"#fb8c00", emoji:"🏃‍♀️", weeks:12, desc:"Half Marathon 21.1km. For runners with a solid 10K base.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km base run. Establish HM training pace."},
        {week:1,day:2,type:"Speed Intervals",dist:5,dur:50,desc:"8 x 400m at 5K pace with 200m jog recovery."},
        {week:1,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength - squats, deadlifts, lunges."},
        {week:1,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 25 min tempo, 10 min easy."},
        {week:1,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy recovery run. Conversational pace."},
        {week:1,day:6,type:"Long Run",dist:10,dur:95,desc:"10km long run base. Very easy pace."},
        {week:1,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. Stretch and foam roll."},
        {week:2,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Building aerobic base."},
        {week:2,day:2,type:"Speed Intervals",dist:6,dur:58,desc:"10 x 400m at 5K pace."},
        {week:2,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Single-leg work - step-ups, split squats."},
        {week:2,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 30 min tempo, 10 min easy."},
        {week:2,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Keep easy days easy."},
        {week:2,day:6,type:"Long Run",dist:12,dur:114,desc:"12km long run. Run to feel, not time."},
        {week:2,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. Refuel well."},
        {week:3,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Fitness is coming."},
        {week:3,day:2,type:"Speed Intervals",dist:6,dur:60,desc:"6 x 800m at 10K pace with 400m jog recovery."},
        {week:3,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Core - planks, Russian twists."},
        {week:3,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 35 min tempo, 5 min easy."},
        {week:3,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km recovery run."},
        {week:3,day:6,type:"Long Run",dist:14,dur:133,desc:"14km. Bring water and a gel."},
        {week:3,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Eat carbs and protein. Sleep well."},
        {week:4,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Cutback week."},
        {week:4,day:2,type:"Speed Intervals",dist:4,dur:40,desc:"6 x 400m at 5K pace. Cutback volume."},
        {week:4,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Mobility focus."},
        {week:4,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy."},
        {week:4,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Feeling fresher? Good!"},
        {week:4,day:6,type:"Long Run",dist:10,dur:95,desc:"10km cutback long run."},
        {week:4,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. Keep the faith."},
        {week:5,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Back to building!"},
        {week:5,day:2,type:"Speed Intervals",dist:7,dur:68,desc:"8 x 800m at 10K pace."},
        {week:5,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Hip and glute work."},
        {week:5,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 40 min tempo, 5 min easy."},
        {week:5,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Big long run tomorrow."},
        {week:5,day:6,type:"Long Run",dist:16,dur:152,desc:"16km! Well into HM territory."},
        {week:5,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. 16km is serious - recover properly."},
        {week:6,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Halfway through!"},
        {week:6,day:2,type:"Speed Intervals",dist:7,dur:70,desc:"10 x 800m at 10K pace. Peak session!"},
        {week:6,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Maintain muscle balance."},
        {week:6,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 40 min tempo, 10 min easy."},
        {week:6,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy recovery run."},
        {week:6,day:6,type:"Long Run",dist:18,dur:171,desc:"18km. Amazing! Gels at km 8 and 14."},
        {week:6,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. 18km demands serious recovery."},
        {week:7,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Second cutback week."},
        {week:7,day:2,type:"Speed Intervals",dist:4,dur:40,desc:"6 x 400m. Short and sharp."},
        {week:7,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest."},
        {week:7,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy."},
        {week:7,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Legs feeling springy!"},
        {week:7,day:6,type:"Long Run",dist:12,dur:114,desc:"12km cutback long run."},
        {week:7,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Fitness is consolidating."},
        {week:8,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Final big block!"},
        {week:8,day:2,type:"Speed Intervals",dist:8,dur:78,desc:"10 x 800m at HM goal pace."},
        {week:8,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Last heavy session."},
        {week:8,day:4,type:"Tempo Run",dist:9,dur:85,desc:"10 min easy, 45 min at HM pace, 5 min easy."},
        {week:8,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Huge long run tomorrow."},
        {week:8,day:6,type:"Long Run",dist:19,dur:180,desc:"19km peak long run! Incredible achievement."},
        {week:8,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. 19km extraordinary - recover fully."},
        {week:9,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Maintaining fitness."},
        {week:9,day:2,type:"Speed Intervals",dist:6,dur:60,desc:"8 x 800m at 10K pace."},
        {week:9,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Core and mobility."},
        {week:9,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 35 min tempo, 10 min easy."},
        {week:9,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Home stretch of training!"},
        {week:9,day:6,type:"Long Run",dist:16,dur:152,desc:"16km. Practice race-day nutrition."},
        {week:9,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Three weeks to race day!"},
        {week:10,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Volume easing."},
        {week:10,day:2,type:"Speed Intervals",dist:5,dur:50,desc:"6 x 800m at HM goal pace."},
        {week:10,day:3,type:"Rest/Strength",dist:0,dur:20,desc:"Light strength or rest."},
        {week:10,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 30 min at HM pace, 10 min easy."},
        {week:10,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper beginning."},
        {week:10,day:6,type:"Long Run",dist:14,dur:133,desc:"14km. Last substantial long run."},
        {week:10,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Fitness locked in!"},
        {week:11,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper week. Legs fresh!"},
        {week:11,day:2,type:"Speed Intervals",dist:4,dur:38,desc:"4 x 800m at race pace. Short and sharp."},
        {week:11,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or rest."},
        {week:11,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min at HM pace, 10 min easy."},
        {week:11,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Race week next. You've done everything right."},
        {week:11,day:6,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Last medium run. Confident!"},
        {week:11,day:7,type:"Recovery",dist:0,dur:20,desc:"Easy walk or rest. Read race plan tonight."},
        {week:12,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Race week - keep legs fresh."},
        {week:12,day:2,type:"Strides",dist:2,dur:20,desc:"Easy 2km with 4 x 20-sec strides at race pace."},
        {week:12,day:3,type:"Rest/Cross-train",dist:0,dur:15,desc:"Very light walk or rest."},
        {week:12,day:4,type:"Easy Run",dist:2,dur:18,desc:"10-15 min easy shakeout."},
        {week:12,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Lay out kit. Sleep by 10pm."},
        {week:12,day:6,type:"RACE DAY! 🏆",dist:21.1,dur:0,desc:"HALF MARATHON! Respect the distance, run your race!"},
        {week:12,day:7,type:"Recovery",dist:0,dur:30,desc:"Post-race walk. You ran a half marathon!"},
      ]},
      "FM":  { color:"#e53935", emoji:"🏅", weeks:20, desc:"Full Marathon 42.2km. Serious 20-week training programme.", schedule:[
        {week:1,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Marathon training begins. 20 weeks ahead."},
        {week:1,day:2,type:"Speed/Hill Training",dist:6,dur:60,desc:"Hill repeats - 8 x 90-sec uphill, jog down recovery."},
        {week:1,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy to moderate. Building weekly mileage base."},
        {week:1,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength - squats, deadlifts, lunges, core."},
        {week:1,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 30 min at marathon pace, 10 min easy."},
        {week:1,day:6,type:"Long Run",dist:16,dur:148,desc:"16km long run. Very easy pace. Walk if needed."},
        {week:1,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Very easy 3km recovery jog."},
        {week:2,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Cumulative effect builds slowly."},
        {week:2,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"10 x 90-sec hill repeats. Progressive overload."},
        {week:2,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km moderate. 10% rule keeps you injury-free."},
        {week:2,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Single-leg and hip strengthening."},
        {week:2,day:5,type:"Tempo Run",dist:9,dur:85,desc:"10 min easy, 35 min at marathon pace, 10 min easy."},
        {week:2,day:6,type:"Long Run",dist:18,dur:167,desc:"18km. Gel at 45 and 90 minutes. Train your gut!"},
        {week:2,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy recovery jog. Relaxed breathing."},
        {week:3,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Consistency building aerobic base."},
        {week:3,day:2,type:"Speed/Hill Training",dist:7,dur:70,desc:"8 x 2-min hill repeats at 5K effort."},
        {week:3,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km medium effort. Double digits!"},
        {week:3,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Core endurance - extended planks."},
        {week:3,day:5,type:"Tempo Run",dist:10,dur:95,desc:"10 min easy, 40 min at marathon pace, 5 min easy."},
        {week:3,day:6,type:"Long Run",dist:20,dur:185,desc:"20km! Major milestone. Two gels. Feel proud!"},
        {week:3,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km after the long run."},
        {week:4,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Cutback week."},
        {week:4,day:2,type:"Speed/Hill Training",dist:5,dur:50,desc:"6 x 90-sec hill repeats. Reduced volume."},
        {week:4,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy. Cutback week."},
        {week:4,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Mobility focus."},
        {week:4,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 25 min at marathon pace, 10 min easy."},
        {week:4,day:6,type:"Long Run",dist:14,dur:130,desc:"14km cutback long run. Recovery and adaptation."},
        {week:4,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Notice how fresh you feel!"},
        {week:5,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Back to building!"},
        {week:5,day:2,type:"Speed/Hill Training",dist:8,dur:78,desc:"10 x 2-min hill repeats. Peak hill session!"},
        {week:5,day:3,type:"Medium Run",dist:11,dur:105,desc:"11km moderate run. Mileage stacking up."},
        {week:5,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Don't skip - reduces injury risk."},
        {week:5,day:5,type:"Tempo Run",dist:11,dur:104,desc:"10 min easy, 45 min marathon pace, 5 min easy."},
        {week:5,day:6,type:"Long Run",dist:22,dur:204,desc:"22km. Three gels - practice race nutrition."},
        {week:5,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy recovery. Legs adapting to big mileage."},
        {week:6,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Aerobic base significantly stronger."},
        {week:6,day:2,type:"Speed/Hill Training",dist:8,dur:80,desc:"Marathon intervals - 4 x 2km at 10K pace."},
        {week:6,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km moderate. Serious weekly mileage now."},
        {week:6,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Posterior chain - hamstrings and glutes."},
        {week:6,day:5,type:"Tempo Run",dist:11,dur:104,desc:"10 min easy, 45 min at marathon pace, 10 min easy."},
        {week:6,day:6,type:"Long Run",dist:24,dur:222,desc:"24km. Deep in marathon territory. Four gels!"},
        {week:6,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km. Marathon machine in progress."},
        {week:7,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Building toward peak weeks."},
        {week:7,day:2,type:"Speed/Hill Training",dist:9,dur:88,desc:"5 x 2km at 10K pace. True marathon fitness."},
        {week:7,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km. Aerobic platform for race day."},
        {week:7,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Mental strength too - halfway to race day!"},
        {week:7,day:5,type:"Tempo Run",dist:12,dur:114,desc:"10 min easy, 50 min at marathon pace, 5 min easy."},
        {week:7,day:6,type:"Long Run",dist:25,dur:231,desc:"25km. Every step makes race day more achievable!"},
        {week:7,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy recovery. Nutrition and sleep as important as running."},
        {week:8,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Second cutback week."},
        {week:8,day:2,type:"Speed/Hill Training",dist:6,dur:60,desc:"6 x 90-sec hills. Reduced but quality."},
        {week:8,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km easy to moderate. Consolidating fitness."},
        {week:8,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest. Extra mobility - hips, ankles."},
        {week:8,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 30 min at marathon pace, 10 min easy."},
        {week:8,day:6,type:"Long Run",dist:18,dur:167,desc:"18km cutback. Much more comfortable now!"},
        {week:8,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Champions are made in cutback weeks."},
        {week:9,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Fresh from cutback - build up!"},
        {week:9,day:2,type:"Speed/Hill Training",dist:9,dur:90,desc:"6 x 2km at 10K pace. Building peak fitness."},
        {week:9,day:3,type:"Medium Run",dist:13,dur:124,desc:"13km moderate. Fitness at new level."},
        {week:9,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Last chance for heavy strength."},
        {week:9,day:5,type:"Tempo Run",dist:13,dur:123,desc:"10 min easy, 55 min marathon pace, 5 min easy."},
        {week:9,day:6,type:"Long Run",dist:27,dur:250,desc:"27km. Gel every 45 min. You are a long-distance runner!"},
        {week:9,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. 27km deserves 9 hours sleep."},
        {week:10,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Deep in peak training and thriving."},
        {week:10,day:2,type:"Speed/Hill Training",dist:10,dur:98,desc:"Race-pace intervals - 3 x 5km at goal pace."},
        {week:10,day:3,type:"Medium Run",dist:13,dur:124,desc:"13km moderate. Maintaining peak mileage."},
        {week:10,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength. Visualize crossing the finish line."},
        {week:10,day:5,type:"Tempo Run",dist:13,dur:123,desc:"10 min easy, 55 min at marathon goal pace, 5 min easy."},
        {week:10,day:6,type:"Long Run",dist:29,dur:268,desc:"29km. Peak long run! The hardest run of the plan!"},
        {week:10,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. 29km extraordinary - eat, sleep, elevate."},
        {week:11,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Approaching final build phase."},
        {week:11,day:2,type:"Speed/Hill Training",dist:9,dur:90,desc:"6 x 2km at 10K pace. Keeping legs sharp."},
        {week:11,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km. Volume easing very slightly."},
        {week:11,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Prevents late-plan injuries."},
        {week:11,day:5,type:"Tempo Run",dist:12,dur:114,desc:"10 min easy, 50 min marathon pace, 5 min easy."},
        {week:11,day:6,type:"Long Run",dist:30,dur:278,desc:"30km - LONGEST RUN EVER! Three-quarters of marathon!"},
        {week:11,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. 30km done. Feel phenomenally proud."},
        {week:12,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Third cutback - well earned!"},
        {week:12,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"8 x 90-sec hills. Maintaining leg turnover."},
        {week:12,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km easy. Absorb those 30km legs."},
        {week:12,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or light strength. Visualize success."},
        {week:12,day:5,type:"Tempo Run",dist:9,dur:85,desc:"10 min easy, 35 min marathon pace, 10 min easy."},
        {week:12,day:6,type:"Long Run",dist:20,dur:185,desc:"20km cutback. Much more comfortable after 30km runs!"},
        {week:12,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km. Eight weeks to race day. Trust it."},
        {week:13,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Back to building - final peak phase."},
        {week:13,day:2,type:"Speed/Hill Training",dist:10,dur:98,desc:"4 x 5km at marathon goal pace. Peak training!"},
        {week:13,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km moderate. Consistency brought you here."},
        {week:13,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Injury-free because of this work."},
        {week:13,day:5,type:"Tempo Run",dist:13,dur:123,desc:"10 min easy, 55 min at marathon goal pace, 5 min easy."},
        {week:13,day:6,type:"Long Run",dist:32,dur:296,desc:"32km. TRUE PEAK LONG RUN. YOU LEGEND!"},
        {week:13,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. After 32km - marathon is within reach!"},
        {week:14,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Week 14 - gradual volume reduction."},
        {week:14,day:2,type:"Speed/Hill Training",dist:9,dur:88,desc:"6 x 2km at 10K pace. Peak fitness!"},
        {week:14,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km. Volume holding before taper."},
        {week:14,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength. Entering pre-taper phase."},
        {week:14,day:5,type:"Tempo Run",dist:11,dur:104,desc:"10 min easy, 45 min marathon pace, 10 min easy."},
        {week:14,day:6,type:"Long Run",dist:28,dur:259,desc:"28km. Last very long run. How strong you've become!"},
        {week:14,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. Hardest training is behind you."},
        {week:15,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Taper begins! Enjoy lighter load."},
        {week:15,day:2,type:"Speed/Hill Training",dist:8,dur:78,desc:"5 x 2km at 10K pace. Maintaining sharpness."},
        {week:15,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km. Volume coming down. Legs feeling bouncy!"},
        {week:15,day:4,type:"Rest/Strength",dist:0,dur:20,desc:"Light strength only. Protect legs for race day."},
        {week:15,day:5,type:"Tempo Run",dist:10,dur:95,desc:"10 min easy, 40 min at marathon pace, 10 min easy."},
        {week:15,day:6,type:"Long Run",dist:22,dur:204,desc:"22km. Reduced from peak. Easy pace throughout."},
        {week:15,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km. Five weeks out. Trust it completely."},
        {week:16,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Taper well underway. Feeling restless? Good!"},
        {week:16,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"4 x 2km at marathon pace. Confidence building."},
        {week:16,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km moderate. Mileage reducing nicely."},
        {week:16,day:4,type:"Rest/Strength",dist:0,dur:20,desc:"Very light strength or rest. Maintenance only."},
        {week:16,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 30 min marathon pace, 10 min easy."},
        {week:16,day:6,type:"Long Run",dist:18,dur:167,desc:"18km taper run. Feels easy after 32km - enjoy it!"},
        {week:16,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Four weeks out. Race prep focus."},
        {week:17,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Deep taper. Heavy legs? Normal!"},
        {week:17,day:2,type:"Speed/Hill Training",dist:5,dur:50,desc:"6 x 800m at 10K pace. Keeping spark alive."},
        {week:17,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy. Mileage continues to reduce."},
        {week:17,day:4,type:"Rest/Strength",dist:0,dur:15,desc:"Very light only. Finalize race logistics."},
        {week:17,day:5,type:"Tempo Run",dist:6,dur:57,desc:"10 min easy, 20 min marathon pace, 10 min easy."},
        {week:17,day:6,type:"Long Run",dist:14,dur:130,desc:"14km easy. Last double-digit run."},
        {week:17,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Three weeks out. You are ready!"},
        {week:18,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Race week minus two. Very easy only."},
        {week:18,day:2,type:"Speed/Hill Training",dist:4,dur:40,desc:"4 x 800m at 10K pace. Short and sharp."},
        {week:18,day:3,type:"Medium Run",dist:6,dur:56,desc:"6km easy. Trust the process!"},
        {week:18,day:4,type:"Rest/Strength",dist:0,dur:15,desc:"Rest or short walk. Pack race bag."},
        {week:18,day:5,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 15 min marathon pace, 10 min easy."},
        {week:18,day:6,type:"Long Run",dist:10,dur:95,desc:"10km easy. Legs feeling fresh and ready!"},
        {week:18,day:7,type:"Recovery Run",dist:2,dur:18,desc:"Easy 2km. Two weeks to marathon. Peak fitness!"},
        {week:19,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Pre-race week. No hard efforts."},
        {week:19,day:2,type:"Strides",dist:3,dur:28,desc:"Easy 3km with 4 x 20-sec strides. Last speed work!"},
        {week:19,day:3,type:"Rest/Cross-train",dist:0,dur:15,desc:"Very easy walk or rest. Sort race logistics."},
        {week:19,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km shakeout. Legs feeling amazing?"},
        {week:19,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Travel if needed. Carb-load. Sleep well."},
        {week:19,day:6,type:"Easy Run",dist:2,dur:18,desc:"10-15 min shakeout. Settle race-day nerves."},
        {week:19,day:7,type:"Rest",dist:0,dur:0,desc:"Complete rest. Race tomorrow! Kit laid out. Bed by 9:30pm."},
        {week:20,day:1,type:"RACE DAY! 🏆",dist:42.2,dur:0,desc:"MARATHON RACE DAY! Start slow, stay patient, run your race. YOU ARE A MARATHONER!"},
        {week:20,day:2,type:"Recovery Walk",dist:0,dur:30,desc:"Very gentle walk only. Ice bath if possible."},
        {week:20,day:3,type:"Rest",dist:0,dur:0,desc:"Complete rest. Eat whatever you want. You earned it!"},
        {week:20,day:4,type:"Rest",dist:0,dur:0,desc:"Rest. Soreness peaks day 3 - completely normal."},
        {week:20,day:5,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk if legs allow. Your body is healing."},
        {week:20,day:6,type:"Easy Walk/Jog",dist:2,dur:20,desc:"Very easy 20-min walk or gentle jog. No pressure."},
        {week:20,day:7,type:"Recovery",dist:0,dur:30,desc:"Easy walk and stretch. You completed a marathon!"},
      ]},
    }
  },

    hydration: {
    // One plan per module — scientifically tailored to activity type
    default: {
      title: "Daily Hydration Plan",
      targets: { training: 3.0, rest: 2.5 },
      schedule: [
        { time:"7:00 AM",        amount:500, label:"Wake-up glass" },
        { time:"9:00 AM",        amount:400, label:"Mid-morning" },
        { time:"12:00 PM",       amount:500, label:"Before lunch" },
        { time:"3:00 PM",        amount:400, label:"Afternoon" },
        { time:"Pre-Workout",    amount:400, label:"30 min before" },
        { time:"During Workout", amount:500, label:"Sip every 15 min" },
        { time:"Post-Workout",   amount:500, label:"Within 30 min" },
        { time:"8:00 PM",        amount:300, label:"Evening" },
      ],
      tips: [
        "Urine colour should be pale yellow — dark means you need more water.",
        "Add a pinch of Himalayan pink salt on heavy training days to replace electrolytes.",
        "Drink 200–300ml extra per 30 min in hot or humid weather.",
      ]
    },

    cardio: {
      title: "Home Cardio Hydration Plan",
      targets: { training: 3.5, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (7 AM)",     amount:500, label:"Start metabolism, flush overnight waste" },
        { time:"Pre-Workout (30 min)", amount:400, label:"Hydrate before intense cardio" },
        { time:"During Cardio",      amount:600, label:"150ml every 15 min — cardio causes heavy sweat" },
        { time:"Post-Workout (30 min)", amount:500, label:"Replace sweat losses immediately" },
        { time:"Mid-Morning",        amount:400, label:"Sustained hydration between sessions" },
        { time:"Before Lunch",       amount:300, label:"Aids digestion and nutrient absorption" },
        { time:"Afternoon (3 PM)",   amount:400, label:"Prevents afternoon energy dip" },
        { time:"Evening (7 PM)",     amount:300, label:"Light — avoid excess before sleep" },
      ],
      tips: [
        "Cardio causes 0.5–1.5L sweat/hour — drink before you feel thirsty.",
        "Add coconut water or electrolyte tabs after sessions longer than 45 minutes.",
        "Cold water (15°C) absorbs 30% faster than room temperature during exercise.",
        "Weigh yourself before and after — drink 1.5L per kg lost during session.",
        "Avoid sugary sports drinks for sessions under 60 min — plain water is sufficient.",
      ]
    },

    gym: {
      title: "Gym Workout Hydration Plan",
      targets: { training: 4.0, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (7 AM)",      amount:500, label:"Rehydrate after 7–8 hrs without water" },
        { time:"Pre-Workout (60 min)", amount:500, label:"Top up glycogen and joints for lifting" },
        { time:"Pre-Workout (15 min)", amount:250, label:"Final top-up before first set" },
        { time:"During Lifting",      amount:750, label:"200ml between every 2–3 sets" },
        { time:"Post-Workout (30 min)", amount:600, label:"Critical — begin recovery immediately" },
        { time:"With Protein Meal",   amount:400, label:"Aids protein synthesis and digestion" },
        { time:"Afternoon",           amount:500, label:"Joints and muscle repair require hydration" },
        { time:"Evening",             amount:400, label:"Casein protein digestion needs extra water" },
      ],
      tips: [
        "Heavy lifting causes micro-tears — muscles repair faster when fully hydrated.",
        "Dehydration of just 2% body weight reduces strength by up to 10%.",
        "Creatine users need an extra 500ml daily — creatine draws water into muscles.",
        "Sip water between sets, not during reps — avoid bloating mid-lift.",
        "Post-workout: aim for 150% of fluid lost (e.g. lost 500ml → drink 750ml).",
        "Joint health: cartilage is 80% water — consistent hydration prevents knee/shoulder pain.",
      ]
    },

    yoga: {
      title: "Yoga Practice Hydration Plan",
      targets: { training: 2.5, rest: 2.0 },
      schedule: [
        { time:"Wake-Up (6:30 AM)",   amount:500, label:"Warm water with lemon — cleanses and alkalises" },
        { time:"30 Min Before Yoga",  amount:200, label:"Small sip only — avoid heavy stomach during poses" },
        { time:"During Practice",     amount:200, label:"Tiny sips only if very thirsty — don't interrupt flow" },
        { time:"Post-Practice",       amount:400, label:"Rehydrate mindfully after deep stretches" },
        { time:"Mid-Morning",         amount:400, label:"Room temperature water preferred in yoga lifestyle" },
        { time:"Before Lunch",        amount:300, label:"30 min before meals for optimal digestion" },
        { time:"Afternoon",           amount:350, label:"Herbal teas count — tulsi, ginger, chamomile" },
        { time:"Evening",             amount:250, label:"Light — calming the body before rest" },
      ],
      tips: [
        "Yoga tradition prefers room-temperature or warm water — cold water can disrupt digestive fire (agni).",
        "Avoid drinking large amounts 30 min before or during practice — it compresses the core.",
        "Coconut water is the ideal post-yoga drink — natural electrolytes and calming properties.",
        "Hot yoga (Bikram) requires 1L extra — you lose significantly more through sweat.",
        "Herbal teas (tulsi, ginger, peppermint) count toward daily intake and support digestion.",
        "Eating water-rich foods (cucumber, watermelon, oranges) aligns with yogic diet principles.",
      ]
    },

    stretching: {
      title: "Stretching & Recovery Hydration Plan",
      targets: { training: 2.5, rest: 2.0 },
      schedule: [
        { time:"Wake-Up",             amount:500, label:"Warm water — hydrates overnight-stiff muscles" },
        { time:"Before Stretching",   amount:300, label:"Warm muscles stretch better when hydrated" },
        { time:"During Stretching",   amount:200, label:"Small sips — stretching is low intensity" },
        { time:"Post-Stretching",     amount:300, label:"Flush released toxins from fascia" },
        { time:"Mid-Morning",         amount:400, label:"Collagen synthesis requires hydration" },
        { time:"Lunch Time",          amount:400, label:"Support joint lubrication throughout day" },
        { time:"Afternoon",           amount:300, label:"Consistent low-level hydration is key" },
        { time:"Evening",             amount:200, label:"Light — this is a recovery/rest day" },
      ],
      tips: [
        "Fascia (connective tissue) is 70% water — dehydration makes it stiff and less elastic.",
        "Warm water before stretching loosens muscle fibres faster than cold water.",
        "Collagen (joint and muscle repair) synthesis requires adequate vitamin C and hydration.",
        "Bone broth counts toward intake and provides collagen directly.",
        "Avoid alcohol on stretching/rest days — it dehydrates and slows muscle repair by 24hrs.",
        "Magnesium-rich water (or supplement) on rest days reduces muscle soreness significantly.",
      ]
    },

    running: {
      title: "Running & Walking Hydration Plan",
      targets: { training: 4.5, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (6 AM)",       amount:500, label:"Start the day hydrated before early runs" },
        { time:"2 Hours Before Run",   amount:500, label:"Pre-load hydration — kidneys process excess" },
        { time:"15 Min Before Run",    amount:200, label:"Final top-up without bloating" },
        { time:"During Run (<45 min)", amount:400, label:"150–200ml every 20 min — small frequent sips" },
        { time:"During Run (>45 min)", amount:700, label:"Sports drink or water + salt every 20–30 min" },
        { time:"Post-Run (30 min)",    amount:600, label:"Most critical window — begin recovery immediately" },
        { time:"Post-Run (2 hrs)",     amount:500, label:"Continue sipping — 1.5L per kg lost" },
        { time:"Evening",              amount:400, label:"Support overnight muscle and joint recovery" },
      ],
      tips: [
        "Running loses 500ml–1.5L per hour depending on heat, humidity and pace.",
        "The thirst signal lags 20 min behind actual need — drink on a schedule, not when thirsty.",
        "For runs over 60 min, add electrolytes (sodium, potassium) — water alone causes hyponatremia.",
        "Hot weather running: pre-cool with 500ml ice-cold water 10 min before — reduces core temp.",
        "Weigh before and after every long run. Drink 1.5L for every 1kg lost.",
        "Marathon training: increase daily intake by 1L on days with runs over 16km.",
        "Signs of dehydration while running: dark urine, headache, cramping, nausea, confusion — stop immediately.",
      ]
    },
  },

    diet: {
    modules: {
      cardio:     { title:"Cardio Day Diet Plan",   meals:[
        { time:"Pre-Workout",  name:"Energy Boost",     items:"Banana + black coffee or green tea", cal:150, notes:"30-45 min before session" },
        { time:"Post-Workout", name:"Recovery Meal",    items:"2 boiled eggs + 1 slice whole wheat toast", cal:220, notes:"Within 30 min after" },
        { time:"Breakfast",    name:"Carb-Forward Meal",items:"Oats porridge with fruit and nuts", cal:380, notes:"Replenish glycogen" },
        { time:"Lunch",        name:"Balanced Meal",    items:"Brown rice + grilled chicken 150g + vegetables", cal:560, notes:"Protein + complex carbs" },
        { time:"Snack",        name:"Afternoon Fuel",   items:"Greek yogurt + handful of almonds", cal:220, notes:"Sustained energy" },
        { time:"Dinner",       name:"Light Recovery",   items:"Lentil soup + 2 chapati + salad", cal:480, notes:"Early, light dinner" },
      ]},
      gym:        { title:"Gym Day Diet Plan",      meals:[
        { time:"Pre-Workout",  name:"Power Fuel",        items:"Banana + 2 boiled eggs + optional coffee", cal:280, notes:"60 min before lifting" },
        { time:"Intra-Workout",name:"Hydration",         items:"Water + optional BCAA drink", cal:50, notes:"Sip during session" },
        { time:"Post-Workout", name:"Anabolic Window",   items:"Whey protein shake or 200g Greek yogurt + fruit", cal:280, notes:"Within 30 min — critical!" },
        { time:"Lunch",        name:"Muscle Building",   items:"Brown rice 200g + grilled chicken 180g + vegetables", cal:620, notes:"2-3 hrs post-workout" },
        { time:"Snack",        name:"Protein Boost",     items:"Cottage cheese or paneer 100g + fruit", cal:200, notes:"Afternoon" },
        { time:"Dinner",       name:"Casein Meal",       items:"Dal + 2 chapati + salad + glass of milk", cal:520, notes:"Slow-digesting protein overnight" },
      ]},
      yoga:       { title:"Yoga Day Diet Plan",     meals:[
        { time:"Pre-Yoga",  name:"Light Energy",       items:"Small banana or 4-5 dates + herbal tea", cal:120, notes:"30-60 min before. Avoid heavy food." },
        { time:"Post-Yoga", name:"Nourishment",        items:"Smoothie: banana + spinach + almond milk + honey", cal:240, notes:"Replenish mindfully" },
        { time:"Breakfast", name:"Sattvic Breakfast",  items:"Poha or upma + coconut chutney + herbal tea", cal:360, notes:"Light, digestible" },
        { time:"Lunch",     name:"Balanced Thali",     items:"Dal + rice + sabzi + curd + salad", cal:580, notes:"Largest meal of day" },
        { time:"Snack",     name:"Light Snack",        items:"Fresh fruit + handful walnuts", cal:180, notes:"Afternoon, light" },
        { time:"Dinner",    name:"Early Light Dinner", items:"Khichdi or vegetable soup + bread", cal:420, notes:"By 7pm ideally" },
      ]},
      stretching: { title:"Rest/Stretch Day Diet Plan", meals:[
        { time:"Morning",  name:"Anti-Inflammatory",items:"Turmeric milk or golden latte + fruit", cal:200, notes:"Anti-inflammatory start" },
        { time:"Breakfast",name:"Protein + Fibre",   items:"2 eggs any style + whole grain toast + avocado", cal:420, notes:"Sustained energy" },
        { time:"Lunch",    name:"Omega-Rich Meal",   items:"Grilled fish or tofu + quinoa + roasted vegetables", cal:540, notes:"Recovery nutrition" },
        { time:"Snack",    name:"Collagen Boost",    items:"Bone broth or gelatin-rich foods", cal:120, notes:"Supports joint health" },
        { time:"Dinner",   name:"Recovery Dinner",   items:"Chicken/lentil soup + whole grain bread", cal:460, notes:"Easy to digest" },
      ]},
      running: { title:"Running Day Diet Plan", meals:[
        { time:"Pre-Run (2-3 hrs)", name:"Main Pre-Run Meal", items:"Oats with banana + honey OR 2 slices toast + peanut butter + banana", cal:380, notes:"Easy to digest carbs — avoid fibre and fat close to run" },
        { time:"Pre-Run (30 min)", name:"Quick Energy Top-Up", items:"1 banana OR 4–5 dates OR half energy bar", cal:120, notes:"Quick-release glucose — nothing heavy" },
        { time:"During Run (>60 min)", name:"Intra-Run Fuel", items:"Energy gel OR banana chunk OR 3–4 dates every 45 min", cal:100, notes:"Per serving — only needed for runs over 60 min" },
        { time:"Post-Run (30 min)", name:"Recovery Window", items:"Chocolate milk OR whey shake + banana OR Greek yogurt + mango", cal:320, notes:"CRITICAL: 3:1 carb:protein ratio — this window is gold" },
        { time:"Post-Run Meal (1-2 hrs)", name:"Full Recovery Meal", items:"White rice + grilled chicken/fish + roasted vegetables", cal:620, notes:"White rice preferred post-run — faster glycogen replenishment than brown" },
        { time:"Evening Snack", name:"Overnight Recovery", items:"Cottage cheese (paneer) OR casein protein + warm milk", cal:220, notes:"Slow-digesting protein repairs muscles during sleep" },
      ]},
    }
  }
};

window.DEFAULT_USERS = [
  { id:"u_admin", name:"Admin User",  email:"admin@fitflow.com", password:"admin123", tempPassword:"", isFirstLogin:false, role:"ADMIN", status:"ACTIVE", createdDate:"2025-01-01" },
];
