// ── DEFAULT DATA ─────────────────────────────────────────────────
window.APP_DATA = {

  quotes: [
    { text: "The only bad workout is the one that didn't happen.", author: "Unknown" },
    { text: "Success is usually the culmination of controlling failure.", author: "Sylvester Stallone" },
    { text: "The pain you feel today will be the strength you feel tomorrow.", author: "Arnold Schwarzenegger" },
    { text: "Take care of your body. It's the only place you have to live.", author: "Jim Rohn" },
    { text: "Fitness is not about being better than someone else. It's about being better than you used to be.", author: "Unknown" },
    { text: "Push yourself because no one else is going to do it for you.", author: "Unknown" },
    { text: "Your body can stand almost anything. It's your mind that you have to convince.", author: "Unknown" },
    { text: "Don't wish for it. Work for it.", author: "Unknown" },
    { text: "The difference between try and triumph is a little umph.", author: "Marvin Phillips" },
    { text: "Sweat is just fat crying.", author: "Unknown" },
    { text: "No matter how slow you go, you are still lapping everybody on the couch.", author: "Unknown" },
    { text: "Be stronger than your strongest excuse.", author: "Unknown" },
  ],

  // ── WARMUP (shared structure, used by cardio, gym, yoga, running) ─
  warmups: {
    cardio: [
      { name:"Dynamic Warm-Up", sets:1, reps:"5 min", desc:"March in place 1 min → arm circles 1 min → hip circles 1 min → leg swings 1 min → neck rolls 1 min. Raise heart rate gradually before the workout.", image:"", demo:"https://www.youtube.com/results?search_query=cardio+warm+up+routine+5+minutes", tag:"warmup" },
    ],
    gym: [
      { name:"Gym Warm-Up", sets:1, reps:"5 min", desc:"5 min light cardio (treadmill/bike) → dynamic chest opener 10 reps → world's greatest stretch 5 each side → glute bridges 15 reps. Prepares muscles and joints for heavy lifting.", image:"", demo:"https://www.youtube.com/results?search_query=gym+warm+up+before+workout", tag:"warmup" },
    ],
    yoga: [
      { name:"Yoga Warm-Up", sets:1, reps:"5 min", desc:"Seated breathing 2 min → neck & shoulder rolls 1 min → cat-cow 8 rounds → child's pose 1 min. Calms the mind and prepares the spine for practice.", image:"", demo:"https://www.youtube.com/results?search_query=yoga+warm+up+routine", tag:"warmup" },
    ],
    running: [
      { name:"Pre-Run Warm-Up", sets:1, reps:"5 min", desc:"Brisk walk 2 min → slow high knees 30 sec → ankle circles 10 each → hip flexor lunge 30 sec each → leg swings 10 each. Essential before every run to prevent injury.", image:"", demo:"https://www.youtube.com/results?search_query=running+warm+up+routine", tag:"warmup" },
    ],
  },

    cooldowns: {
    cardio: [
      { name:"Cool-Down & Stretch", sets:1, reps:"5 min", desc:"Slow walk 2 min → standing quad stretch 30 sec each → standing hamstring stretch 30 sec each → hip flexor stretch 30 sec each → chest opener 45 sec. Essential for recovery and flexibility.", image:"", demo:"https://www.youtube.com/results?search_query=cardio+cool+down+stretch+routine", tag:"cooldown" },
    ],
    gym: [
      { name:"Post-Workout Cool-Down", sets:1, reps:"5 min", desc:"5 min easy walk → doorway chest stretch 45 sec → lat stretch 30 sec each → seated hamstring stretch 45 sec each → child's pose 2 min. Flush lactic acid and restore muscle length.", image:"", demo:"https://www.youtube.com/results?search_query=gym+cool+down+stretching+routine", tag:"cooldown" },
    ],
    yoga: [
      { name:"Yoga Cool-Down", sets:1, reps:"5 min", desc:"Supine twist 60 sec each → legs up the wall 3 min → happy baby 90 sec → Savasana 5 min. Never skip Savasana — the body needs time to absorb the practice.", image:"", demo:"https://www.youtube.com/results?search_query=yoga+cool+down+savasana", tag:"cooldown" },
    ],
    running: [
      { name:"Post-Run Cool-Down", sets:1, reps:"5 min", desc:"Easy walk 3 min → standing calf stretch 45 sec each → quad stretch 30 sec each → IT band stretch 45 sec each → seated hamstring & glute stretch 60 sec each. Critical for runner recovery.", image:"", demo:"https://www.youtube.com/results?search_query=post+run+cool+down+stretches", tag:"cooldown" },
    ],
  },

    modules: {
    cardio: {
      name: "Home Cardio",
      emoji: "🏠",
      color: "grad-cardio",
      days: {
        Monday: [
          { name:"Jumping Jacks", sets:3, reps:"45 sec", desc:"Stand upright, jump feet apart while raising arms overhead. Return to start. High-energy full-body warm-up.", image:"", demo:"https://www.youtube.com/results?search_query=jumping+jacks+exercise" },
          { name:"High Knees", sets:3, reps:"40 sec", desc:"Run in place driving knees up to waist height. Pump arms. Great cardio and core activator.", image:"", demo:"https://www.youtube.com/results?search_query=high+knees+exercise" },
          { name:"Burpees", sets:3, reps:"10 reps", desc:"From standing, drop to push-up position, perform push-up, jump feet to hands, explode upward.", image:"", demo:"https://www.youtube.com/results?search_query=burpees+exercise" },
          { name:"Mountain Climbers", sets:3, reps:"40 sec", desc:"In push-up position, alternate driving knees toward chest rapidly. Keep hips level.", image:"", demo:"https://www.youtube.com/results?search_query=mountain+climbers+exercise" },
          { name:"Jump Squats", sets:3, reps:"15 reps", desc:"Perform squat, then explode upward into a jump. Land softly with bent knees.", image:"", demo:"https://www.youtube.com/results?search_query=jump+squats+exercise" },
          { name:"Plank Hold", sets:3, reps:"45 sec", desc:"Forearms on floor, body straight from head to heels. Squeeze glutes and core.", image:"", demo:"https://www.youtube.com/results?search_query=plank+hold+exercise" },
        ],
        Tuesday: [
          { name:"Skipping (Shadow)", sets:3, reps:"60 sec", desc:"Mimic skipping rope motion with arms and alternating foot hops. Light, rhythmic cardio.", image:"", demo:"https://www.youtube.com/results?search_query=shadow+skipping+exercise" },
          { name:"Star Jumps", sets:3, reps:"20 reps", desc:"Jump with arms and legs spread wide (star shape) then return. High-impact, full-body cardio.", image:"", demo:"https://www.youtube.com/results?search_query=star+jumps+exercise" },
          { name:"Push-Ups", sets:3, reps:"12 reps", desc:"Hands shoulder-width, body straight. Lower chest to floor, push up.", image:"", demo:"https://www.youtube.com/results?search_query=pushups+exercise" },
          { name:"Squat Pulses", sets:3, reps:"30 sec", desc:"Hold squat position and pulse up and down 3-4 inches.", image:"", demo:"https://www.youtube.com/results?search_query=squat+pulses+exercise" },
          { name:"Flutter Kicks", sets:3, reps:"40 sec", desc:"Lie on back, lift legs 6 inches, alternate small up-down kicks. Targets lower abs.", image:"", demo:"https://www.youtube.com/results?search_query=flutter+kicks+exercise" },
          { name:"Shadow Boxing", sets:3, reps:"60 sec", desc:"Alternate jabs, crosses, and hooks in the air. Full upper-body cardio.", image:"", demo:"https://www.youtube.com/results?search_query=shadow+boxing+cardio" },
        ],
        Wednesday: [
          { name:"Bear Crawls", sets:3, reps:"30 sec", desc:"On hands and feet (knees off floor), crawl forward and back. Full-body stabiliser.", image:"", demo:"https://www.youtube.com/results?search_query=bear+crawl+exercise" },
          { name:"Lateral Shuffles", sets:3, reps:"40 sec", desc:"Shuffle side to side quickly, staying in athletic stance.", image:"", demo:"https://www.youtube.com/results?search_query=lateral+shuffle+exercise" },
          { name:"Tricep Dips", sets:3, reps:"15 reps", desc:"Use a chair or floor. Hands behind you, lower body by bending elbows to 90°.", image:"", demo:"https://www.youtube.com/results?search_query=tricep+dips+exercise" },
          { name:"Bicycle Crunches", sets:3, reps:"20 reps", desc:"Alternate touching elbow to opposite knee while extending other leg.", image:"", demo:"https://www.youtube.com/results?search_query=bicycle+crunches+exercise" },
          { name:"Reverse Lunges", sets:3, reps:"12 each", desc:"Step backward into a lunge. Knee tracks over ankle.", image:"", demo:"https://www.youtube.com/results?search_query=reverse+lunges+exercise" },
          { name:"Inchworms", sets:3, reps:"10 reps", desc:"Bend at hips, walk hands out to push-up position and back.", image:"", demo:"https://www.youtube.com/results?search_query=inchworm+exercise" },
        ],
        Thursday: [
          { name:"Speed Skaters", sets:3, reps:"40 sec", desc:"Leap side to side mimicking a speed skater. Builds lateral power and cardio.", image:"", demo:"https://www.youtube.com/results?search_query=speed+skater+exercise" },
          { name:"Knee Push-Ups", sets:3, reps:"15 reps", desc:"Modified push-up from knees.", image:"", demo:"https://www.youtube.com/results?search_query=knee+pushups+exercise" },
          { name:"Sumo Squat", sets:3, reps:"15 reps", desc:"Wide stance, toes out. Squat deeply keeping chest up.", image:"", demo:"https://www.youtube.com/results?search_query=sumo+squat+exercise" },
          { name:"Superman Hold", sets:3, reps:"30 sec", desc:"Lie face down, lift arms and legs simultaneously.", image:"", demo:"https://www.youtube.com/results?search_query=superman+hold+exercise" },
          { name:"Box Step-Ups", sets:3, reps:"12 each", desc:"Step up and down on a chair or step.", image:"", demo:"https://www.youtube.com/results?search_query=step+ups+exercise" },
          { name:"Hollow Hold", sets:3, reps:"30 sec", desc:"Lie on back, press lower back to floor, raise legs and shoulders.", image:"", demo:"https://www.youtube.com/results?search_query=hollow+hold+exercise" },
        ],
        Friday: [
          { name:"Tabata Burpees", sets:3, reps:"20 sec on/10 off", desc:"Maximum effort burpees for 20 seconds, rest 10 seconds.", image:"", demo:"https://www.youtube.com/results?search_query=tabata+burpees" },
          { name:"Wall Sit", sets:3, reps:"45 sec", desc:"Back against wall, thighs parallel to floor.", image:"", demo:"https://www.youtube.com/results?search_query=wall+sit+exercise" },
          { name:"Diamond Push-Ups", sets:3, reps:"10 reps", desc:"Hands form a diamond shape under chest. Targets triceps.", image:"", demo:"https://www.youtube.com/results?search_query=diamond+pushups+exercise" },
          { name:"Donkey Kicks", sets:3, reps:"15 each", desc:"On all fours, kick one leg back and up, squeezing glute at top.", image:"", demo:"https://www.youtube.com/results?search_query=donkey+kicks+exercise" },
          { name:"Crab Walks", sets:3, reps:"30 sec", desc:"Seated position, lift hips and walk on hands and feet.", image:"", demo:"https://www.youtube.com/results?search_query=crab+walk+exercise" },
          { name:"Dead Bug", sets:3, reps:"10 each side", desc:"On back, extend opposite arm and leg while keeping lower back pressed down.", image:"", demo:"https://www.youtube.com/results?search_query=dead+bug+exercise" },
        ],
        Saturday: [
          { name:"AMRAP Circuits", sets:3, reps:"5 min", desc:"As Many Rounds As Possible: 5 push-ups + 10 squats + 15 jumping jacks.", image:"", demo:"https://www.youtube.com/results?search_query=AMRAP+workout+cardio" },
          { name:"Long Plank", sets:3, reps:"60 sec", desc:"Extended plank challenge.", image:"", demo:"https://www.youtube.com/results?search_query=long+plank+challenge" },
          { name:"Squat to Press", sets:3, reps:"12 reps", desc:"Hold light weights or water bottles. Squat down, press overhead as you stand.", image:"", demo:"https://www.youtube.com/results?search_query=squat+to+press+exercise" },
          { name:"Plank Shoulder Taps", sets:3, reps:"20 taps", desc:"In high plank, alternate touching opposite shoulder.", image:"", demo:"https://www.youtube.com/results?search_query=plank+shoulder+taps" },
          { name:"Standing Oblique Crunches", sets:3, reps:"15 each", desc:"Standing, bring elbow down to meet rising knee on same side.", image:"", demo:"https://www.youtube.com/results?search_query=standing+oblique+crunches" },
          { name:"Cool Down Walk", sets:1, reps:"5 min", desc:"Walk in place at slow pace. Deep breaths. Gradual heart rate reduction.", image:"", demo:"" },
        ],
      }
    },

    gym: {
      name: "Gym Workouts",
      emoji: "🏋️",
      color: "grad-gym",
      days: {
        Monday: [
          { name:"Barbell Squat", sets:3, reps:"12 reps", desc:"Bar on traps, feet shoulder-width. Squat until thighs parallel to floor.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+squat+form" },
          { name:"Bench Press", sets:3, reps:"10 reps", desc:"Grip bar slightly wider than shoulders. Lower to mid-chest, press up.", image:"", demo:"https://www.youtube.com/results?search_query=bench+press+form" },
          { name:"Bent-Over Row", sets:3, reps:"12 reps", desc:"Hinge at hips, pull bar to lower chest. Squeeze shoulder blades.", image:"", demo:"https://www.youtube.com/results?search_query=bent+over+row+form" },
          { name:"Overhead Press", sets:3, reps:"10 reps", desc:"Press barbell from shoulders to overhead. Lock out elbows.", image:"", demo:"https://www.youtube.com/results?search_query=overhead+press+form" },
          { name:"Romanian Deadlift", sets:3, reps:"12 reps", desc:"Slight knee bend, hinge at hips, lower bar along legs.", image:"", demo:"https://www.youtube.com/results?search_query=romanian+deadlift+form" },
          { name:"Cable Plank", sets:3, reps:"45 sec", desc:"Plank with cable weight. Advanced core anti-extension drill.", image:"", demo:"https://www.youtube.com/results?search_query=plank+exercise+gym" },
        ],
        Tuesday: [
          { name:"Deadlift", sets:3, reps:"8 reps", desc:"Feet hip-width, bar over laces. Push floor away, keep bar close.", image:"", demo:"https://www.youtube.com/results?search_query=deadlift+form+tutorial" },
          { name:"Incline Dumbbell Press", sets:3, reps:"12 reps", desc:"30-45° bench angle. Press dumbbells from chest level upward.", image:"", demo:"https://www.youtube.com/results?search_query=incline+dumbbell+press" },
          { name:"Lat Pulldown", sets:3, reps:"12 reps", desc:"Grip wide. Pull bar to upper chest, lean slightly back.", image:"", demo:"https://www.youtube.com/results?search_query=lat+pulldown+form" },
          { name:"Leg Press", sets:3, reps:"15 reps", desc:"Feet shoulder-width on platform. Lower sled until 90° knee angle.", image:"", demo:"https://www.youtube.com/results?search_query=leg+press+form" },
          { name:"Dumbbell Curl", sets:3, reps:"12 each", desc:"Supinate wrist as you curl. Full range of motion.", image:"", demo:"https://www.youtube.com/results?search_query=dumbbell+bicep+curl+form" },
          { name:"Tricep Pushdown", sets:3, reps:"15 reps", desc:"Cable attachment at shoulder height. Push down to lockout.", image:"", demo:"https://www.youtube.com/results?search_query=tricep+pushdown+cable" },
        ],
        Wednesday: [
          { name:"Hack Squat", sets:3, reps:"12 reps", desc:"Machine squat variant. Feet forward on platform.", image:"", demo:"https://www.youtube.com/results?search_query=hack+squat+machine" },
          { name:"Dumbbell Shoulder Press", sets:3, reps:"12 reps", desc:"Seated or standing. Press dumbbells from ear height to overhead.", image:"", demo:"https://www.youtube.com/results?search_query=dumbbell+shoulder+press" },
          { name:"Seated Cable Row", sets:3, reps:"12 reps", desc:"Pull cable handle to lower abs. Keep chest tall.", image:"", demo:"https://www.youtube.com/results?search_query=seated+cable+row+form" },
          { name:"Leg Curl", sets:3, reps:"12 reps", desc:"Lying or seated. Curl heel toward glute.", image:"", demo:"https://www.youtube.com/results?search_query=leg+curl+machine" },
          { name:"Dumbbell Lateral Raise", sets:3, reps:"15 reps", desc:"Raise arms to shoulder height with slight bend.", image:"", demo:"https://www.youtube.com/results?search_query=lateral+raise+form" },
          { name:"Ab Crunch Machine", sets:3, reps:"20 reps", desc:"Pull handles toward knees while contracting abs.", image:"", demo:"https://www.youtube.com/results?search_query=ab+crunch+machine" },
        ],
        Thursday: [
          { name:"Bulgarian Split Squat", sets:3, reps:"10 each", desc:"Rear foot elevated. Lower front leg until 90°.", image:"", demo:"https://www.youtube.com/results?search_query=bulgarian+split+squat" },
          { name:"Cable Fly", sets:3, reps:"15 reps", desc:"Mid-height cables. Bring handles together in arc motion.", image:"", demo:"https://www.youtube.com/results?search_query=cable+fly+chest+form" },
          { name:"Face Pulls", sets:3, reps:"15 reps", desc:"Cable at head height. Pull to face, elbows high.", image:"", demo:"https://www.youtube.com/results?search_query=face+pulls+form" },
          { name:"Hammer Curl", sets:3, reps:"12 each", desc:"Neutral grip (thumbs up). Curl without supinating.", image:"", demo:"https://www.youtube.com/results?search_query=hammer+curl+form" },
          { name:"Calf Raise", sets:3, reps:"20 reps", desc:"On platform or flat floor. Rise onto toes, hold 1 second.", image:"", demo:"https://www.youtube.com/results?search_query=calf+raise+form" },
          { name:"Hanging Leg Raise", sets:3, reps:"12 reps", desc:"Hang from bar. Raise legs to 90°.", image:"", demo:"https://www.youtube.com/results?search_query=hanging+leg+raise+form" },
        ],
        Friday: [
          { name:"Power Clean", sets:3, reps:"6 reps", desc:"Olympic lift. Pull bar from floor explosively, catch at shoulders.", image:"", demo:"https://www.youtube.com/results?search_query=power+clean+form+tutorial" },
          { name:"Dips", sets:3, reps:"12 reps", desc:"On parallel bars, lower until elbows 90°.", image:"", demo:"https://www.youtube.com/results?search_query=dips+exercise+form" },
          { name:"Pull-Ups", sets:3, reps:"8 reps", desc:"Full hang, pull until chin over bar.", image:"", demo:"https://www.youtube.com/results?search_query=pull+ups+form" },
          { name:"Leg Extension", sets:3, reps:"15 reps", desc:"Machine. Extend legs to full lockout.", image:"", demo:"https://www.youtube.com/results?search_query=leg+extension+machine+form" },
          { name:"EZ Bar Skull Crusher", sets:3, reps:"12 reps", desc:"Lying on bench, lower bar to forehead, extend.", image:"", demo:"https://www.youtube.com/results?search_query=skull+crushers+form" },
          { name:"Farmer's Carry", sets:3, reps:"40m", desc:"Hold heavy dumbbells, walk with tall posture.", image:"", demo:"https://www.youtube.com/results?search_query=farmers+carry+exercise" },
        ],
        Saturday: [
          { name:"Full Body Circuit", sets:3, reps:"5 rounds", desc:"Squat 8 + Push 8 + Row 8 + Press 8. Light-moderate weight.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+circuit+gym" },
          { name:"Cable Woodchop", sets:3, reps:"12 each", desc:"Rotate cable from high to low across body.", image:"", demo:"https://www.youtube.com/results?search_query=cable+woodchop+exercise" },
          { name:"Seated Row Close Grip", sets:3, reps:"12 reps", desc:"Close-grip attachment. Pull to navel.", image:"", demo:"https://www.youtube.com/results?search_query=close+grip+seated+row" },
          { name:"Hip Thrust", sets:3, reps:"15 reps", desc:"Shoulders on bench, bar on hips. Drive hips to ceiling.", image:"", demo:"https://www.youtube.com/results?search_query=barbell+hip+thrust+form" },
          { name:"Shrugs", sets:3, reps:"15 reps", desc:"Heavy dumbbells or barbell. Shrug shoulders straight up.", image:"", demo:"https://www.youtube.com/results?search_query=shrugs+exercise+form" },
          { name:"Ab Wheel Rollout", sets:3, reps:"10 reps", desc:"From knees, roll wheel out to full extension, return.", image:"", demo:"https://www.youtube.com/results?search_query=ab+wheel+rollout+form" },
        ],
      }
    },

    yoga: {
      name: "Yoga",
      emoji: "🧘",
      color: "grad-yoga",
      days: {
        Monday: [
          { name:"Sun Salutation A", sets:3, reps:"5 rounds", desc:"Mountain → Forward Fold → Halfway Lift → Plank → Cobra → Downdog.", image:"", demo:"https://www.youtube.com/results?search_query=sun+salutation+A+yoga" },
          { name:"Warrior I", sets:3, reps:"45 sec each", desc:"Front knee bent 90°, back leg straight, arms reach overhead.", image:"", demo:"https://www.youtube.com/results?search_query=warrior+1+yoga+pose" },
          { name:"Warrior II", sets:3, reps:"45 sec each", desc:"Wide stance, front knee over ankle, arms parallel to floor.", image:"", demo:"https://www.youtube.com/results?search_query=warrior+2+yoga+pose" },
          { name:"Tree Pose", sets:3, reps:"30 sec each", desc:"Balance on one leg, foot on inner thigh. Hands at heart or overhead.", image:"", demo:"https://www.youtube.com/results?search_query=tree+pose+yoga" },
          { name:"Child's Pose", sets:3, reps:"60 sec", desc:"Kneel, extend arms forward, rest forehead on mat.", image:"", demo:"https://www.youtube.com/results?search_query=child's+pose+yoga" },
          { name:"Savasana", sets:1, reps:"3 min", desc:"Complete relaxation on back. Allow body to absorb the practice.", image:"", demo:"https://www.youtube.com/results?search_query=savasana+yoga" },
        ],
        Tuesday: [
          { name:"Cat-Cow", sets:3, reps:"10 rounds", desc:"Alternate arching and rounding spine with breath.", image:"", demo:"https://www.youtube.com/results?search_query=cat+cow+yoga" },
          { name:"Downward Dog", sets:3, reps:"60 sec", desc:"Inverted V shape. Press hands and feet into mat.", image:"", demo:"https://www.youtube.com/results?search_query=downward+dog+yoga" },
          { name:"Pigeon Pose", sets:3, reps:"60 sec each", desc:"Deep hip opener. Front shin parallel to mat, back leg extended.", image:"", demo:"https://www.youtube.com/results?search_query=pigeon+pose+yoga" },
          { name:"Seated Forward Fold", sets:3, reps:"60 sec", desc:"Legs extended, hinge forward from hips.", image:"", demo:"https://www.youtube.com/results?search_query=seated+forward+fold+yoga" },
          { name:"Supine Twist", sets:3, reps:"45 sec each", desc:"Lie on back, knee across body, arms wide.", image:"", demo:"https://www.youtube.com/results?search_query=supine+spinal+twist+yoga" },
          { name:"Legs Up The Wall", sets:1, reps:"3 min", desc:"Passive inversion. Legs vertical against wall.", image:"", demo:"https://www.youtube.com/results?search_query=legs+up+wall+yoga" },
        ],
        Wednesday: [
          { name:"Triangle Pose", sets:3, reps:"45 sec each", desc:"Wide stance, extend over front leg, hand to shin or floor.", image:"", demo:"https://www.youtube.com/results?search_query=triangle+pose+yoga" },
          { name:"Boat Pose", sets:3, reps:"30 sec", desc:"Balance on sit bones, legs and torso form a V.", image:"", demo:"https://www.youtube.com/results?search_query=boat+pose+yoga" },
          { name:"Camel Pose", sets:3, reps:"30 sec", desc:"Kneeling back bend. Hands on heels. Opens chest.", image:"", demo:"https://www.youtube.com/results?search_query=camel+pose+yoga" },
          { name:"Extended Side Angle", sets:3, reps:"45 sec each", desc:"Front arm rests on thigh or floor, back arm stretches overhead.", image:"", demo:"https://www.youtube.com/results?search_query=extended+side+angle+yoga" },
          { name:"Bridge Pose", sets:3, reps:"45 sec", desc:"Lie on back, feet flat, lift hips. Squeeze glutes.", image:"", demo:"https://www.youtube.com/results?search_query=bridge+pose+yoga" },
          { name:"Happy Baby", sets:1, reps:"2 min", desc:"Lie on back, hold outer feet. Rock gently side to side.", image:"", demo:"https://www.youtube.com/results?search_query=happy+baby+pose+yoga" },
        ],
        Thursday: [
          { name:"Chair Pose", sets:3, reps:"45 sec", desc:"Feet together, sit back as if on invisible chair.", image:"", demo:"https://www.youtube.com/results?search_query=chair+pose+yoga" },
          { name:"Eagle Pose", sets:3, reps:"30 sec each", desc:"One leg wrapped around other, arms intertwined.", image:"", demo:"https://www.youtube.com/results?search_query=eagle+pose+yoga" },
          { name:"Half Moon Pose", sets:3, reps:"30 sec each", desc:"Balance on one leg and hand. Other arm and leg extend.", image:"", demo:"https://www.youtube.com/results?search_query=half+moon+pose+yoga" },
          { name:"Wide-Leg Forward Fold", sets:3, reps:"60 sec", desc:"Feet wide, fold forward, head toward floor.", image:"", demo:"https://www.youtube.com/results?search_query=wide+legged+forward+fold+yoga" },
          { name:"Fish Pose", sets:3, reps:"30 sec", desc:"On back, arch thoracic spine, crown of head on mat.", image:"", demo:"https://www.youtube.com/results?search_query=fish+pose+yoga" },
          { name:"Corpse Pose Extended", sets:1, reps:"4 min", desc:"Extended Savasana with body scan meditation.", image:"", demo:"https://www.youtube.com/results?search_query=savasana+body+scan+yoga" },
        ],
        Friday: [
          { name:"Crow Pose Prep", sets:3, reps:"5 attempts", desc:"Squat, place knees on upper arms, lean forward and find balance.", image:"", demo:"https://www.youtube.com/results?search_query=crow+pose+yoga+beginners" },
          { name:"Plank to Chaturanga", sets:3, reps:"10 reps", desc:"High plank, lower with elbows hugging body.", image:"", demo:"https://www.youtube.com/results?search_query=chaturanga+yoga+form" },
          { name:"Cobra Pose", sets:3, reps:"30 sec", desc:"Lie prone, place hands under shoulders. Press up, elbows soft.", image:"", demo:"https://www.youtube.com/results?search_query=cobra+pose+yoga" },
          { name:"Lizard Pose", sets:3, reps:"45 sec each", desc:"Low lunge with front foot outside hand. Deep hip flexor stretch.", image:"", demo:"https://www.youtube.com/results?search_query=lizard+pose+yoga" },
          { name:"Headstand Prep", sets:3, reps:"30 sec", desc:"Forearms on mat, crown on mat, hips lift (dolphin pose).", image:"", demo:"https://www.youtube.com/results?search_query=headstand+prep+yoga" },
          { name:"Meditation Sit", sets:1, reps:"5 min", desc:"Comfortable seated position. Focus on breath.", image:"", demo:"https://www.youtube.com/results?search_query=yoga+meditation+breathing" },
        ],
        Saturday: [
          { name:"Full Flow Practice", sets:1, reps:"20 min", desc:"Freestyle: combine all learned poses.", image:"", demo:"https://www.youtube.com/results?search_query=20+minute+yoga+flow+full+body" },
          { name:"Yin Hip Sequence", sets:1, reps:"5 min", desc:"Hold each hip-opening pose for 1 minute: Dragon, Shoelace, Frog.", image:"", demo:"https://www.youtube.com/results?search_query=yin+yoga+hips" },
          { name:"Shoulder Opener", sets:3, reps:"45 sec each", desc:"Thread-the-needle, shoulder-to-floor stretches.", image:"", demo:"https://www.youtube.com/results?search_query=shoulder+opener+yoga" },
          { name:"Restorative Child's Pose", sets:1, reps:"3 min", desc:"Supported with blanket under torso.", image:"", demo:"https://www.youtube.com/results?search_query=restorative+yoga+childs+pose" },
          { name:"Seated Meditation", sets:1, reps:"10 min", desc:"Eyes closed, breath awareness, body scan.", image:"", demo:"https://www.youtube.com/results?search_query=10+minute+guided+meditation" },
          { name:"Gratitude Journaling", sets:1, reps:"5 min", desc:"Write 3 things you're grateful for and 1 fitness win this week.", image:"", demo:"" },
        ],
      }
    },

    stretching: {
      name: "Stretching",
      emoji: "🤸",
      color: "grad-stretch",
      days: {
        Monday: [
          { name:"Neck Rolls", sets:3, reps:"5 each dir", desc:"Slowly roll head in full circles. Never force the movement.", image:"", demo:"https://www.youtube.com/results?search_query=neck+rolls+stretch" },
          { name:"Chest Opener Stretch", sets:3, reps:"45 sec", desc:"Clasp hands behind back, open chest, lift chin.", image:"", demo:"https://www.youtube.com/results?search_query=chest+opener+stretch" },
          { name:"Hip Flexor Lunge", sets:3, reps:"45 sec each", desc:"Low lunge, front knee 90°. Push hips forward and down.", image:"", demo:"https://www.youtube.com/results?search_query=hip+flexor+lunge+stretch" },
          { name:"Standing Hamstring Stretch", sets:3, reps:"40 sec each", desc:"Foot on ledge, hinge forward from hips.", image:"", demo:"https://www.youtube.com/results?search_query=standing+hamstring+stretch" },
          { name:"Quad Stretch", sets:3, reps:"30 sec each", desc:"Standing, pull foot to glute.", image:"", demo:"https://www.youtube.com/results?search_query=standing+quad+stretch" },
          { name:"Calf Stretch", sets:3, reps:"30 sec each", desc:"Heel on floor, lean forward.", image:"", demo:"https://www.youtube.com/results?search_query=calf+stretch+wall" },
        ],
        Tuesday: [
          { name:"Doorway Chest Stretch", sets:3, reps:"45 sec", desc:"Hands on doorframe, lean forward.", image:"", demo:"https://www.youtube.com/results?search_query=doorway+chest+stretch" },
          { name:"Thoracic Rotation", sets:3, reps:"10 each", desc:"Seated, rotate upper body left and right.", image:"", demo:"https://www.youtube.com/results?search_query=thoracic+rotation+stretch" },
          { name:"Seated Pigeon", sets:3, reps:"60 sec each", desc:"Ankle on opposite knee (figure 4). Lean forward.", image:"", demo:"https://www.youtube.com/results?search_query=seated+pigeon+pose+stretch" },
          { name:"IT Band Stretch", sets:3, reps:"45 sec each", desc:"Cross one leg behind other, lean sideways.", image:"", demo:"https://www.youtube.com/results?search_query=IT+band+stretch" },
          { name:"Wrist and Forearm Stretch", sets:3, reps:"30 sec each", desc:"Extend arm, bend wrist down and up.", image:"", demo:"https://www.youtube.com/results?search_query=wrist+forearm+stretch" },
          { name:"Ankle Circles", sets:3, reps:"10 each dir", desc:"Slow ankle rotations in both directions.", image:"", demo:"https://www.youtube.com/results?search_query=ankle+circles+mobility" },
        ],
        Wednesday: [
          { name:"Butterfly Stretch", sets:3, reps:"60 sec", desc:"Soles of feet together, lean forward gently.", image:"", demo:"https://www.youtube.com/results?search_query=butterfly+stretch" },
          { name:"Figure 4 Glute Stretch", sets:3, reps:"60 sec each", desc:"Lying on back, figure-4 with legs.", image:"", demo:"https://www.youtube.com/results?search_query=figure+4+glute+stretch" },
          { name:"Child's Pose with Reach", sets:3, reps:"45 sec each", desc:"Child's pose, walk hands to each side.", image:"", demo:"https://www.youtube.com/results?search_query=child's+pose+side+stretch" },
          { name:"Standing Side Stretch", sets:3, reps:"30 sec each", desc:"Arm overhead, reach and lean to opposite side.", image:"", demo:"https://www.youtube.com/results?search_query=standing+side+stretch" },
          { name:"Spinal Twist Seated", sets:3, reps:"45 sec each", desc:"Seated, one leg extended. Cross other foot over. Rotate toward bent knee.", image:"", demo:"https://www.youtube.com/results?search_query=seated+spinal+twist" },
          { name:"90-90 Hip Stretch", sets:3, reps:"60 sec each", desc:"Both legs at 90° angles on floor.", image:"", demo:"https://www.youtube.com/results?search_query=90+90+hip+stretch" },
        ],
        Thursday: [
          { name:"Shoulder Cross-Body Stretch", sets:3, reps:"30 sec each", desc:"Pull arm across chest.", image:"", demo:"https://www.youtube.com/results?search_query=cross+body+shoulder+stretch" },
          { name:"Bicep Wall Stretch", sets:3, reps:"30 sec each", desc:"Hand flat on wall at shoulder height, rotate away.", image:"", demo:"https://www.youtube.com/results?search_query=bicep+wall+stretch" },
          { name:"Lying Hamstring Stretch", sets:3, reps:"45 sec each", desc:"On back, loop band/towel around foot, extend leg.", image:"", demo:"https://www.youtube.com/results?search_query=lying+hamstring+stretch+band" },
          { name:"Frog Stretch", sets:3, reps:"60 sec", desc:"On all fours, knees wide, rock back.", image:"", demo:"https://www.youtube.com/results?search_query=frog+stretch" },
          { name:"Upper Trap Stretch", sets:3, reps:"30 sec each", desc:"Tilt head to one side, hold with hand.", image:"", demo:"https://www.youtube.com/results?search_query=upper+trap+stretch" },
          { name:"Thoracic Extension on Foam Roll", sets:3, reps:"60 sec", desc:"Foam roller perpendicular to spine. Extend over roller at different segments.", image:"", demo:"https://www.youtube.com/results?search_query=thoracic+extension+foam+roller" },
        ],
        Friday: [
          { name:"Full Body Stretch Sequence", sets:1, reps:"15 min", desc:"Guided head-to-toe stretch.", image:"", demo:"https://www.youtube.com/results?search_query=full+body+stretch+sequence" },
          { name:"Couch Stretch", sets:3, reps:"60 sec each", desc:"Rear foot elevated, front foot forward. Deepest hip flexor stretch.", image:"", demo:"https://www.youtube.com/results?search_query=couch+stretch+hip+flexor" },
          { name:"Pancake Stretch", sets:3, reps:"60 sec", desc:"Straddle position, fold forward.", image:"", demo:"https://www.youtube.com/results?search_query=pancake+stretch" },
          { name:"Shoulder Capsule Stretch", sets:3, reps:"30 sec each", desc:"Arm across chest in horizontal position.", image:"", demo:"https://www.youtube.com/results?search_query=posterior+shoulder+capsule+stretch" },
          { name:"Active Lunge Stretch", sets:3, reps:"10 each", desc:"Dynamic lunge with rotation.", image:"", demo:"https://www.youtube.com/results?search_query=lunge+with+twist+stretch" },
          { name:"Box Breathing Cooldown", sets:1, reps:"5 min", desc:"Inhale 4 sec, hold 4 sec, exhale 4 sec, hold 4 sec.", image:"", demo:"https://www.youtube.com/results?search_query=box+breathing+technique" },
        ],
        Saturday: [
          { name:"Yin Style Full Body", sets:1, reps:"20 min", desc:"Hold each stretch 2-3 minutes.", image:"", demo:"https://www.youtube.com/results?search_query=yin+yoga+full+body+20+minutes" },
          { name:"PNF Hamstring", sets:3, reps:"3 cycles each", desc:"Stretch, contract 6 sec, stretch further.", image:"", demo:"https://www.youtube.com/results?search_query=PNF+hamstring+stretch" },
          { name:"Hip Circle Mobility", sets:3, reps:"10 each dir", desc:"Wide stance, rotate hips in large circles.", image:"", demo:"https://www.youtube.com/results?search_query=hip+circle+mobility" },
          { name:"Overhead Tricep Stretch", sets:3, reps:"30 sec each", desc:"Arm overhead, elbow bent. Push elbow back with other hand.", image:"", demo:"https://www.youtube.com/results?search_query=overhead+tricep+stretch" },
          { name:"Anterior Tib Stretch", sets:3, reps:"30 sec each", desc:"Kneel, top of foot on floor. Sit back on heels.", image:"", demo:"https://www.youtube.com/results?search_query=anterior+tibialis+stretch" },
          { name:"Total Body Relax", sets:1, reps:"5 min", desc:"Lie still, progressive muscle relaxation.", image:"", demo:"https://www.youtube.com/results?search_query=progressive+muscle+relaxation" },
        ],
      }
    },
  },

  running: {
    plans: {
      "5K":  { color:"#43a05a", emoji:"🏃", weeks:6, desc:"Beginner-friendly. Build from 2km to 5km in 6 weeks.", schedule:[
        // Week 1 - Getting Started
        {week:1,day:1,type:"Easy Run",dist:2,dur:20,desc:"Very easy pace. You should be able to hold a conversation. Just get moving and enjoy it."},
        {week:1,day:2,type:"Run/Walk",dist:2,dur:25,desc:"Run 2 min, walk 1 min. Repeat 6 times. Total 20-25 mins. Focus on breathing."},
        {week:1,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Rest or light cross-training — cycling, swimming or yoga. Let your legs recover."},
        {week:1,day:4,type:"Easy Run",dist:2,dur:20,desc:"Same as Day 1. Easy pace. No pressure. Build the habit."},
        {week:1,day:5,type:"Rest",dist:0,dur:0,desc:"Full rest day. Sleep well, stay hydrated. Recovery is part of training."},
        {week:1,day:6,type:"Long Run",dist:3,dur:30,desc:"Your longest run this week. Slow and steady. Walk if needed."},
        {week:1,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy 30-minute walk. Loosens up muscles. Enjoy the outdoors."},
        // Week 2 - Building Base
        {week:2,day:1,type:"Easy Run",dist:2.5,dur:25,desc:"Slightly longer than last week. Keep it conversational and comfortable."},
        {week:2,day:2,type:"Run/Walk",dist:2.5,dur:28,desc:"Run 3 min, walk 1 min. Repeat 6 times. You're getting stronger!"},
        {week:2,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Light cross-training or full rest. Foam roll your calves and quads."},
        {week:2,day:4,type:"Easy Run",dist:2.5,dur:25,desc:"Easy 2.5km. Focus on landing gently and relaxed arms."},
        {week:2,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. Eat well and get 8 hours sleep tonight."},
        {week:2,day:6,type:"Long Run",dist:3.5,dur:35,desc:"3.5km continuous if possible. Walk breaks are totally fine."},
        {week:2,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Gentle walk to flush out lactic acid. 30 minutes at leisure pace."},
        // Week 3 - Building Confidence
        {week:3,day:1,type:"Easy Run",dist:3,dur:28,desc:"3km easy run. Notice how much more comfortable it feels vs week 1!"},
        {week:3,day:2,type:"Run/Walk Intervals",dist:3,dur:30,desc:"Run 4 min, walk 1 min. Repeat 5 times. Pushing the running blocks longer."},
        {week:3,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Cross-training or rest. Try some bodyweight squats and lunges for leg strength."},
        {week:3,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Try to run the whole thing without walking. You can do it!"},
        {week:3,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Trust the process — your body is adapting."},
        {week:3,day:6,type:"Long Run",dist:4,dur:40,desc:"Your first 4km! Take it slow. This is a big milestone — celebrate it."},
        {week:3,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy recovery walk. Stretch your hip flexors and hamstrings well."},
        // Week 4 - Getting Stronger
        {week:4,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. You should feel this getting more natural now."},
        {week:4,day:2,type:"Intervals",dist:3,dur:30,desc:"6 × 1 min fast, 2 min easy jog. First speed work! Helps build fitness fast."},
        {week:4,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Rest or cross-training. Focus on core exercises — planks and bridges."},
        {week:4,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km recovery run after yesterday's intervals."},
        {week:4,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. You're 4 weeks in — fantastic commitment!"},
        {week:4,day:6,type:"Long Run",dist:4.5,dur:45,desc:"4.5km. Almost at your goal distance! Steady pace throughout."},
        {week:4,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"30-minute walk. Hydrate well today — you earned it."},
        // Week 5 - Peak Training
        {week:5,day:1,type:"Easy Run",dist:3.5,dur:33,desc:"Easy 3.5km. Building your aerobic base for the final push."},
        {week:5,day:2,type:"Intervals",dist:3,dur:30,desc:"8 × 1 min fast, 90 sec easy. More intervals this week — you're getting fit!"},
        {week:5,day:3,type:"Rest/Cross-train",dist:0,dur:30,desc:"Light cross-training or rest. Yoga or stretching is perfect today."},
        {week:5,day:4,type:"Easy Run",dist:3.5,dur:33,desc:"Easy 3.5km. Keep the effort light — save energy for the long run."},
        {week:5,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. Race is one week away. Believe in your training."},
        {week:5,day:6,type:"Long Run",dist:5,dur:50,desc:"YOUR FIRST 5K! Run the full distance. This is your practice race. You've done it!"},
        {week:5,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk. Celebrate — you ran 5K! Race day is next week."},
        // Week 6 - Taper & Race
        {week:6,day:1,type:"Easy Run",dist:3,dur:28,desc:"Short easy run to keep legs fresh. Don't overdo it this week."},
        {week:6,day:2,type:"Run/Walk",dist:2,dur:20,desc:"Very easy 20 mins. Light on the feet. Saving energy for race day."},
        {week:6,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or full rest. Short walk is fine. No hard efforts."},
        {week:6,day:4,type:"Easy Run",dist:2,dur:18,desc:"15-20 min shakeout run. Light and breezy. Just keeping the legs moving."},
        {week:6,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Lay out your race gear. Sleep early. Eat a good dinner."},
        {week:6,day:6,type:"RACE DAY! 🏆",dist:5,dur:0,desc:"THIS IS IT! Start easy, find your rhythm, finish strong. You trained for this. GO!"},
        {week:6,day:7,type:"Recovery Walk",dist:0,dur:30,desc:"Post-race recovery walk. You're a 5K runner now. Well done!"},
      ]},

      "10K": { color:"#1e88e5", emoji:"🏃‍♂️", weeks:8, desc:"For runners who can run 5K. Double the distance in 8 weeks.", schedule:[
        // Week 1 - Base Building
        {week:1,day:1,type:"Easy Run",dist:4,dur:38,desc:"Comfortable 4km base run. Easy conversational pace. Establish your rhythm."},
        {week:1,day:2,type:"Speed Workout",dist:4,dur:40,desc:"6 × 400m at 5K pace with 200m jog recovery. First speed session — exciting!"},
        {week:1,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or strength training. Squats, lunges, hip bridges. Builds injury resistance."},
        {week:1,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy warm-up, 15 min at comfortably hard pace, 10 min cool-down."},
        {week:1,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. Full recovery. Stretch and foam roll."},
        {week:1,day:6,type:"Long Run",dist:6,dur:58,desc:"First long run. Easy steady pace. Run the full 6km without stopping."},
        {week:1,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Very easy 2km recovery jog. Just shake out the legs."},
        // Week 2
        {week:2,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Feel comfortable, not labored. Building aerobic base."},
        {week:2,day:2,type:"Speed Workout",dist:4.5,dur:45,desc:"8 × 400m at 5K pace with 200m jog recovery. One more rep than last week!"},
        {week:2,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest. Focus on single-leg exercises — step-ups, single-leg deadlifts."},
        {week:2,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy. Tempo pace = comfortably hard."},
        {week:2,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Your muscles repair and grow stronger on rest days."},
        {week:2,day:6,type:"Long Run",dist:7,dur:67,desc:"7km long run. Slow is fine. Consistency beats speed at this stage."},
        {week:2,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy 2km shake-out. Gentle pace, focus on relaxed form."},
        // Week 3
        {week:3,day:1,type:"Easy Run",dist:5,dur:47,desc:"5km easy run. You should feel this getting easier each week."},
        {week:3,day:2,type:"Speed Workout",dist:5,dur:50,desc:"10 × 400m at 5K pace. Recovery 200m jog between each. Great workout!"},
        {week:3,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training. Add calf raises and core work today."},
        {week:3,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 25 min tempo, 5 min cool-down. Building your lactate threshold."},
        {week:3,day:5,type:"Rest",dist:0,dur:0,desc:"Full rest. You're halfway through — great work so far!"},
        {week:3,day:6,type:"Long Run",dist:8,dur:76,desc:"8km. A big milestone! Take it very easy. Walk if needed on hills."},
        {week:3,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy recovery jog. Nice and relaxed — no watch watching needed."},
        // Week 4
        {week:4,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Slight cutback week to let your body absorb training."},
        {week:4,day:2,type:"Speed Workout",dist:4,dur:40,desc:"6 × 400m at 5K pace. Cutback on volume — quality over quantity today."},
        {week:4,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or light strength work. Focus on mobility and flexibility today."},
        {week:4,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min tempo, 10 min easy. Shorter tempo — recovery week."},
        {week:4,day:5,type:"Rest",dist:0,dur:0,desc:"Rest day. This is a cutback week — trust the process."},
        {week:4,day:6,type:"Long Run",dist:7,dur:67,desc:"7km — slightly shorter than last week. Cutback long run for recovery."},
        {week:4,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy jog. Feeling fresh after the cutback? Good — that's the plan!"},
        // Week 5 - Building Again
        {week:5,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Back to building after the cutback. Feel that freshness!"},
        {week:5,day:2,type:"Speed Workout",dist:5,dur:50,desc:"5 × 800m at 5K pace with 400m jog recovery. Longer intervals now!"},
        {week:5,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest. Core and glute work is especially valuable now."},
        {week:5,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 30 min tempo, 5 min easy. Strong tempo effort today!"},
        {week:5,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Race day is 3 weeks away. You're in great shape."},
        {week:5,day:6,type:"Long Run",dist:9,dur:86,desc:"9km! You're nearly at race distance. Slow and steady wins here."},
        {week:5,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy 2km shakeout. Legs might be heavy — that's normal."},
        // Week 6 - Peak Week
        {week:6,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Peak training week — keep easy days easy!"},
        {week:6,day:2,type:"Speed Workout",dist:5,dur:52,desc:"6 × 800m at 5K pace. Peak speed session — you're flying!"},
        {week:6,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or light strength. Don't overdo it — peak week demands recovery too."},
        {week:6,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 30 min tempo, 10 min easy. This is your hardest tempo of the plan."},
        {week:6,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Peak week done. Amazing training block. Now we taper."},
        {week:6,day:6,type:"Long Run",dist:10,dur:95,desc:"FIRST 10K! You ran the full race distance. Race day is just 2 weeks away!"},
        {week:6,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Easy jog. You just ran 10K. Let that sink in — incredible work!"},
        // Week 7 - Taper
        {week:7,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper week — reduce volume, keep intensity. Feel the freshness."},
        {week:7,day:2,type:"Speed Workout",dist:3,dur:30,desc:"4 × 400m at race pace. Short and sharp. Keeping the legs sharp."},
        {week:7,day:3,type:"Rest/Strength",dist:0,dur:20,desc:"Light stretching or rest. No heavy lifting during taper week."},
        {week:7,day:4,type:"Tempo Run",dist:4,dur:38,desc:"10 min easy, 15 min tempo, 10 min easy. Shorter taper tempo."},
        {week:7,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Trust your training. The hay is in the barn!"},
        {week:7,day:6,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Last longer run before race week. Keep it very comfortable."},
        {week:7,day:7,type:"Recovery Jog",dist:2,dur:18,desc:"Short easy jog. Almost race day — excitement is building!"},
        // Week 8 - Race Week
        {week:8,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Race week — keep it light. No heroics this week."},
        {week:8,day:2,type:"Strides",dist:2,dur:20,desc:"Easy 2km with 4 × 20-second strides at race pace. Keeps legs sharp."},
        {week:8,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or rest. Short walk. Visualize your race."},
        {week:8,day:4,type:"Easy Run",dist:2,dur:18,desc:"Easy 15-20 min shakeout. Just keeping the legs moving."},
        {week:8,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Lay out your gear. Eat your normal dinner. Sleep early."},
        {week:8,day:6,type:"RACE DAY! 🏆",dist:10,dur:0,desc:"10K RACE DAY! Start conservatively, build through the middle, finish strong. You trained for this!"},
        {week:8,day:7,type:"Recovery Jog",dist:1,dur:10,desc:"Very easy 10-minute jog or walk. Celebrate! You are a 10K runner!"},
      ]},

      "HM":  { color:"#fb8c00", emoji:"🏃‍♀️", weeks:12, desc:"Half Marathon 21.1km. For runners with a solid 10K base.", schedule:[
        // Week 1
        {week:1,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km base run. Establish your Half Marathon training pace — slow and controlled."},
        {week:1,day:2,type:"Speed Intervals",dist:5,dur:50,desc:"8 × 400m at 5K pace with 200m jog recovery. Building speed and fitness."},
        {week:1,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training — squats, deadlifts, lunges. Strong legs = faster running."},
        {week:1,day:4,type:"Tempo Run",dist:6,dur:56,desc:"10 min easy, 25 min at tempo pace (comfortably hard), 10 min easy."},
        {week:1,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy recovery run. Keep it conversational — this is active recovery."},
        {week:1,day:6,type:"Long Run",dist:10,dur:95,desc:"10km long run base. Very easy pace. Walk breaks allowed. Build time on feet."},
        {week:1,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. Stretch and foam roll thoroughly."},
        // Week 2
        {week:2,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Building aerobic base for the long haul."},
        {week:2,day:2,type:"Speed Intervals",dist:6,dur:58,desc:"10 × 400m at 5K pace. More reps than last week — aerobic engine growing."},
        {week:2,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength session. Add single-leg work — step-ups and Bulgarian split squats."},
        {week:2,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 30 min tempo, 10 min easy. Stronger tempo this week."},
        {week:2,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Keep the easy days easy — discipline now pays off on race day."},
        {week:2,day:6,type:"Long Run",dist:12,dur:114,desc:"12km long run. Run to feel, not to time. Eat and drink every 45 minutes."},
        {week:2,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. Refuel well — your body needs nutrition after long runs."},
        // Week 3
        {week:3,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. You're in the building phase now — feel the fitness coming."},
        {week:3,day:2,type:"Speed Intervals",dist:6,dur:60,desc:"6 × 800m at 10K pace with 400m jog recovery. Longer intervals for HM fitness."},
        {week:3,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength work. Core is critical for half marathon — planks, Russian twists."},
        {week:3,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 35 min tempo, 5 min easy. Building lactate threshold."},
        {week:3,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km recovery run. Nice and relaxed."},
        {week:3,day:6,type:"Long Run",dist:14,dur:133,desc:"14km. Big long run! Bring water and a gel. Practice your race nutrition."},
        {week:3,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Eat plenty of carbs and protein. Sleep is crucial for adaptation."},
        // Week 4 - Cutback
        {week:4,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Cutback week — reduce volume, your body thanks you."},
        {week:4,day:2,type:"Speed Intervals",dist:4,dur:40,desc:"6 × 400m at 5K pace. Shorter session — recovery week quality over quantity."},
        {week:4,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Mobility and flexibility focus today."},
        {week:4,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy. Shorter tempo — cutback week."},
        {week:4,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Feeling fresher? Good — that's the point of cutback weeks."},
        {week:4,day:6,type:"Long Run",dist:10,dur:95,desc:"10km cutback long run. Much shorter on purpose. Let the body absorb training."},
        {week:4,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. You're building something special — keep the faith."},
        // Week 5
        {week:5,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Back to building after the cutback. Notice how fresh you feel!"},
        {week:5,day:2,type:"Speed Intervals",dist:7,dur:68,desc:"8 × 800m at 10K pace. This is the key quality session of the week."},
        {week:5,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training. Hip and glute work prevents the most common running injuries."},
        {week:5,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 40 min tempo, 5 min easy. Longest tempo so far — well done!"},
        {week:5,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Stay relaxed — big long run tomorrow."},
        {week:5,day:6,type:"Long Run",dist:16,dur:152,desc:"16km! Well into HM territory. Practice your race strategy — even pacing."},
        {week:5,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. 16km is a serious effort — recover properly. Eat and sleep well."},
        // Week 6
        {week:6,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Halfway through the plan! You've come so far."},
        {week:6,day:2,type:"Speed Intervals",dist:7,dur:70,desc:"10 × 800m at 10K pace. Peak interval session — you are getting very fit."},
        {week:6,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength session. Maintain muscle balance — don't skip strength this late."},
        {week:6,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 40 min tempo, 10 min easy. Strong sustained effort."},
        {week:6,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy recovery run. Light on your feet today."},
        {week:6,day:6,type:"Long Run",dist:18,dur:171,desc:"18km. Your longest run yet! You are doing amazing. Practice gels at km 8 and 14."},
        {week:6,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest or easy walk. 18km demands serious recovery — prioritize sleep tonight."},
        // Week 7 - Second Cutback
        {week:7,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Second cutback week. Embrace the reduced volume."},
        {week:7,day:2,type:"Speed Intervals",dist:4,dur:40,desc:"6 × 400m. Short and sharp. Maintaining speed during cutback."},
        {week:7,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. You've earned some extra recovery this week."},
        {week:7,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min tempo, 10 min easy. Short cutback tempo."},
        {week:7,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Legs should feel springy after the cutback."},
        {week:7,day:6,type:"Long Run",dist:12,dur:114,desc:"12km cutback long run. Comfortable and controlled."},
        {week:7,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Cutback weeks are where fitness is consolidated. Trust the plan."},
        // Week 8 - Peak Block
        {week:8,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Final big block begins. You're nearly there!"},
        {week:8,day:2,type:"Speed Intervals",dist:8,dur:78,desc:"10 × 800m at HM goal pace. Race-specific training — feel your target pace."},
        {week:8,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Strength. Last heavy strength session of the plan — make it count."},
        {week:8,day:4,type:"Tempo Run",dist:9,dur:85,desc:"10 min easy, 45 min at HM goal pace, 5 min easy. Simulating race effort."},
        {week:8,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Stay relaxed — huge long run coming tomorrow."},
        {week:8,day:6,type:"Long Run",dist:19,dur:180,desc:"19km — your peak long run! Stick to your race pace plan. Incredible achievement."},
        {week:8,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. 19km is extraordinary — recover fully. The hard work is done."},
        // Week 9
        {week:9,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Maintaining fitness while gradually reducing volume."},
        {week:9,day:2,type:"Speed Intervals",dist:6,dur:60,desc:"8 × 800m at 10K pace. Keeping sharpness in the legs."},
        {week:9,day:3,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Core and mobility today."},
        {week:9,day:4,type:"Tempo Run",dist:8,dur:76,desc:"10 min easy, 35 min tempo, 10 min easy. Strong but controlled."},
        {week:9,day:5,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. You're in the home stretch of training!"},
        {week:9,day:6,type:"Long Run",dist:16,dur:152,desc:"16km. Reduced from peak but still substantial. Practice race-day nutrition again."},
        {week:9,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Three weeks to race day. Excitement should be building!"},
        // Week 10
        {week:10,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Volume continues to ease as race day approaches."},
        {week:10,day:2,type:"Speed Intervals",dist:5,dur:50,desc:"6 × 800m at HM goal pace. Race-specific pace reinforcement."},
        {week:10,day:3,type:"Rest/Strength",dist:0,dur:20,desc:"Light strength or rest. No heavy lifting this close to race."},
        {week:10,day:4,type:"Tempo Run",dist:7,dur:66,desc:"10 min easy, 30 min at HM pace, 10 min easy. This feels like race pace now!"},
        {week:10,day:5,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper is beginning — enjoy the lighter load."},
        {week:10,day:6,type:"Long Run",dist:14,dur:133,desc:"14km. Last substantial long run. Feel strong and controlled."},
        {week:10,day:7,type:"Recovery",dist:0,dur:30,desc:"Rest. Two weeks out. Your fitness is locked in — nothing left to build now."},
        // Week 11 - Taper
        {week:11,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Taper week — legs should feel fresh and springy."},
        {week:11,day:2,type:"Speed Intervals",dist:4,dur:38,desc:"4 × 800m at race pace. Short and sharp — maintaining race fitness."},
        {week:11,day:3,type:"Rest/Cross-train",dist:0,dur:20,desc:"Very light activity or rest. Short walk. No strenuous activity."},
        {week:11,day:4,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 20 min at HM pace, 10 min easy. Last tempo before race."},
        {week:11,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Race week is next. You have done everything right."},
        {week:11,day:6,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Last medium run. Keep it comfortable and confident."},
        {week:11,day:7,type:"Recovery",dist:0,dur:20,desc:"Easy walk or complete rest. Read your race-day plan tonight."},
        // Week 12 - Race Week
        {week:12,day:1,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km. Race week — just keeping the legs fresh. No effort today."},
        {week:12,day:2,type:"Strides",dist:2,dur:20,desc:"Easy 2km with 4 × 20-sec strides at race pace. Legs feeling sharp and ready."},
        {week:12,day:3,type:"Rest/Cross-train",dist:0,dur:15,desc:"Very light walk or rest. Final preparations — review your race plan."},
        {week:12,day:4,type:"Easy Run",dist:2,dur:18,desc:"10-15 min easy shakeout run. Just get the blood flowing. That's it."},
        {week:12,day:5,type:"Rest",dist:0,dur:0,desc:"Complete rest. Lay out your kit. Eat your normal dinner. Sleep by 10pm."},
        {week:12,day:6,type:"RACE DAY! 🏆",dist:21.1,dur:0,desc:"HALF MARATHON RACE DAY! Respect the distance, run your own race, finish strong. 12 weeks of training brought you here!"},
        {week:12,day:7,type:"Recovery",dist:0,dur:30,desc:"Post-race recovery walk. You ran a half marathon! Phenomenal achievement. Well done!"},
      ]},

      "FM":  { color:"#e53935", emoji:"🏅", weeks:20, desc:"Full Marathon 42.2km. Serious 20-week training programme.", schedule:[
        // Week 1
        {week:1,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Marathon training begins. Keep it very easy — you have 20 weeks ahead."},
        {week:1,day:2,type:"Speed/Hill Training",dist:6,dur:60,desc:"Hill repeats — 8 × 90-sec uphill at hard effort, jog down recovery. Builds strength."},
        {week:1,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km at easy to moderate pace. Building your weekly mileage base."},
        {week:1,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training. Squats, deadlifts, lunges, core. Injury prevention is priority."},
        {week:1,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 30 min at marathon goal pace, 10 min easy. Practice race pace."},
        {week:1,day:6,type:"Long Run",dist:16,dur:148,desc:"16km long run. Very easy pace. Marathon is all about time on feet. Walk if needed."},
        {week:1,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Very easy 3km recovery jog. Loose and relaxed. Just flushing the legs."},
        // Week 2
        {week:2,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Stay at easy pace — the cumulative effect of marathon training builds slowly."},
        {week:2,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"10 × 90-sec hill repeats. One more rep than last week — progressive overload."},
        {week:2,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km moderate run. Building mileage gradually — the 10% rule keeps you injury-free."},
        {week:2,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength work. Single-leg exercises and hip strengthening — critical for marathoners."},
        {week:2,day:5,type:"Tempo Run",dist:9,dur:85,desc:"10 min easy, 35 min at marathon pace, 10 min easy. Strengthening your aerobic engine."},
        {week:2,day:6,type:"Long Run",dist:18,dur:167,desc:"18km long run. Practice eating a gel at 45 and 90 minutes. Train your gut now."},
        {week:2,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy recovery jog. Focus on relaxed breathing and light footfall."},
        // Week 3
        {week:3,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Three weeks in — consistency is building your aerobic base."},
        {week:3,day:2,type:"Speed/Hill Training",dist:7,dur:70,desc:"8 × 2-min hill repeats at 5K effort. Longer hill reps build more power."},
        {week:3,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km medium effort. Double digits — your body is adapting well."},
        {week:3,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength session. Core endurance — extended planks and anti-rotation exercises."},
        {week:3,day:5,type:"Tempo Run",dist:10,dur:95,desc:"10 min easy, 40 min at marathon pace, 5 min easy. Getting comfortable at race pace."},
        {week:3,day:6,type:"Long Run",dist:20,dur:185,desc:"20km! A major milestone. Very easy pace. Two gels during the run. Feel proud!"},
        {week:3,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km shakeout after the long run. Very gentle effort."},
        // Week 4 - Cutback
        {week:4,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Cutback week — volume drops to let your body absorb the training."},
        {week:4,day:2,type:"Speed/Hill Training",dist:5,dur:50,desc:"6 × 90-sec hill repeats. Reduced volume for recovery week."},
        {week:4,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy. Cutback week medium run — keep it comfortable."},
        {week:4,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Focus on mobility and stretching today."},
        {week:4,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 25 min at marathon pace, 10 min easy. Shorter cutback tempo."},
        {week:4,day:6,type:"Long Run",dist:14,dur:130,desc:"14km cutback long run. Shorter on purpose — recovery and adaptation."},
        {week:4,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Notice how much fresher you feel on a cutback week!"},
        // Week 5
        {week:5,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Back to building after the cutback. Feel that fitness!"},
        {week:5,day:2,type:"Speed/Hill Training",dist:8,dur:78,desc:"10 × 2-min hill repeats. Peak hill session — building serious leg strength."},
        {week:5,day:3,type:"Medium Run",dist:11,dur:105,desc:"11km moderate run. Mileage is stacking up — great fitness building."},
        {week:5,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training. Don't skip this — strength reduces injury risk significantly."},
        {week:5,day:5,type:"Tempo Run",dist:11,dur:104,desc:"10 min easy, 45 min marathon pace, 5 min easy. Long sustained effort."},
        {week:5,day:6,type:"Long Run",dist:22,dur:204,desc:"22km. Excellent long run. Three gels — practice your full race nutrition strategy."},
        {week:5,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy recovery run. Your legs are adapting to big mileage — well done."},
        // Week 6
        {week:6,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Six weeks in — your aerobic base is significantly stronger now."},
        {week:6,day:2,type:"Speed/Hill Training",dist:8,dur:80,desc:"Marathon-specific intervals — 4 × 2km at 10K pace with 2-min jog recovery."},
        {week:6,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km moderate run. You're covering serious weekly mileage now."},
        {week:6,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength session. Emphasize posterior chain — hamstrings and glutes."},
        {week:6,day:5,type:"Tempo Run",dist:11,dur:104,desc:"10 min easy, 45 min at marathon pace, 10 min easy. Strong sustained effort."},
        {week:6,day:6,type:"Long Run",dist:24,dur:222,desc:"24km. You're deep in marathon training territory. Four gels — fuel consistently."},
        {week:6,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km. Your body is becoming a marathon machine — keep recovering well."},
        // Week 7
        {week:7,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Building toward peak training weeks ahead."},
        {week:7,day:2,type:"Speed/Hill Training",dist:9,dur:88,desc:"5 × 2km at 10K pace. Speed work at higher mileage — true marathon fitness."},
        {week:7,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km. Holding this distance helps build the aerobic platform for race day."},
        {week:7,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training. Mental strength counts too — you're halfway to race day!"},
        {week:7,day:5,type:"Tempo Run",dist:12,dur:114,desc:"10 min easy, 50 min at marathon pace, 5 min easy. Race-pace confidence building."},
        {week:7,day:6,type:"Long Run",dist:25,dur:231,desc:"25km. Every step makes race day feel more achievable. Incredible work!"},
        {week:7,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy recovery. Nutrition and sleep tonight are as important as the running."},
        // Week 8 - Cutback
        {week:8,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Second cutback week — down week to absorb the big training block."},
        {week:8,day:2,type:"Speed/Hill Training",dist:6,dur:60,desc:"6 × 90-sec hills. Reduced volume but maintaining quality."},
        {week:8,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km easy to moderate. Cutback week — your body consolidates fitness during rest."},
        {week:8,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength or rest. Extra mobility work — hips, ankles, thoracic spine."},
        {week:8,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 30 min at marathon pace, 10 min easy. Cutback tempo."},
        {week:8,day:6,type:"Long Run",dist:18,dur:167,desc:"18km cutback long run. Much more comfortable than last few weeks — enjoy it!"},
        {week:8,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Cutback weeks are where champions are made — adapt and absorb."},
        // Week 9
        {week:9,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Fresh from the cutback — build back up now!"},
        {week:9,day:2,type:"Speed/Hill Training",dist:9,dur:90,desc:"6 × 2km at 10K pace. Building peak fitness — these sessions are key."},
        {week:9,day:3,type:"Medium Run",dist:13,dur:124,desc:"13km moderate. Highest medium run yet — fitness is at a new level."},
        {week:9,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength session. Last chance for heavy strength before peak weeks."},
        {week:9,day:5,type:"Tempo Run",dist:13,dur:123,desc:"10 min easy, 55 min marathon pace, 5 min easy. Strongest tempo yet!"},
        {week:9,day:6,type:"Long Run",dist:27,dur:250,desc:"27km. You are a long-distance runner. Practice full race nutrition — gel every 45 min."},
        {week:9,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. 27km long run deserves a proper recovery. Sleep 9 hours tonight."},
        // Week 10
        {week:10,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Week 10 — you are deep in peak training and thriving."},
        {week:10,day:2,type:"Speed/Hill Training",dist:10,dur:98,desc:"Marathon race-pace intervals — 3 × 5km at goal marathon pace. Race simulation!"},
        {week:10,day:3,type:"Medium Run",dist:13,dur:124,desc:"13km moderate run. Maintaining peak mileage."},
        {week:10,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength or rest. Mental rehearsal — visualize crossing that finish line."},
        {week:10,day:5,type:"Tempo Run",dist:13,dur:123,desc:"10 min easy, 55 min at marathon goal pace, 5 min easy. Peak tempo confidence."},
        {week:10,day:6,type:"Long Run",dist:29,dur:268,desc:"29km. Peak long run territory! This is it — the hardest run of the plan. You did it!"},
        {week:10,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. 29km is extraordinary. Recover fully — eat, sleep, elevate legs."},
        // Week 11
        {week:11,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Maintaining fitness as we approach the final build phase."},
        {week:11,day:2,type:"Speed/Hill Training",dist:9,dur:90,desc:"6 × 2km at 10K pace. Keeping the legs sharp."},
        {week:11,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km. Volume begins to ease very slightly as race day nears."},
        {week:11,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength training. Keep up the routine — it prevents late-plan injuries."},
        {week:11,day:5,type:"Tempo Run",dist:12,dur:114,desc:"10 min easy, 50 min marathon pace, 5 min easy. Race pace feeling natural now?"},
        {week:11,day:6,type:"Long Run",dist:30,dur:278,desc:"30km — your longest run EVER! You have covered three-quarters of the marathon. Remarkable!"},
        {week:11,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. 30km run done. Rest, eat well and feel phenomenally proud."},
        // Week 12 - Cutback
        {week:12,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Third cutback — you have earned this easier week."},
        {week:12,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"8 × 90-sec hills. Maintaining leg turnover during cutback."},
        {week:12,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km easy to moderate. Cutback week — absorb those 30km legs."},
        {week:12,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Rest or very light strength. Mental training — read race reports, visualize success."},
        {week:12,day:5,type:"Tempo Run",dist:9,dur:85,desc:"10 min easy, 35 min marathon pace, 10 min easy. Short cutback tempo."},
        {week:12,day:6,type:"Long Run",dist:20,dur:185,desc:"20km cutback long run. Feel how much more comfortable this is after 30km runs!"},
        {week:12,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km. Eight weeks to race day. Your fitness is extraordinary — trust it."},
        // Week 13
        {week:13,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Back to building for the final peak phase."},
        {week:13,day:2,type:"Speed/Hill Training",dist:10,dur:98,desc:"4 × 5km at marathon goal pace. Peak race-specific training!"},
        {week:13,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km moderate run. Consistency has brought you to this fitness level."},
        {week:13,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Strength session. Maintain the routine — you are injury-free because of this work."},
        {week:13,day:5,type:"Tempo Run",dist:13,dur:123,desc:"10 min easy, 55 min at goal marathon pace, 5 min easy. Feeling race-ready!"},
        {week:13,day:6,type:"Long Run",dist:32,dur:296,desc:"32km. Your true peak long run. Eight months of running brought you here. YOU LEGEND!"},
        {week:13,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. After 32km — the marathon is truly within reach now. Amazing."},
        // Week 14
        {week:14,day:1,type:"Easy Run",dist:8,dur:76,desc:"Easy 8km. Week 14 — seven weeks to race day. Beginning gradual volume reduction."},
        {week:14,day:2,type:"Speed/Hill Training",dist:9,dur:88,desc:"6 × 2km at 10K pace. Speed work at peak fitness — feeling strong!"},
        {week:14,day:3,type:"Medium Run",dist:12,dur:114,desc:"12km. Volume holding steady before the taper begins."},
        {week:14,day:4,type:"Rest/Strength",dist:0,dur:30,desc:"Light strength. Reduce intensity — entering pre-taper phase."},
        {week:14,day:5,type:"Tempo Run",dist:11,dur:104,desc:"10 min easy, 45 min marathon pace, 10 min easy. Confidence is well-founded!"},
        {week:14,day:6,type:"Long Run",dist:28,dur:259,desc:"28km. Last very long run. Feel how strong and experienced you are compared to week 1."},
        {week:14,day:7,type:"Recovery Run",dist:5,dur:47,desc:"Easy 5km. The hardest training is behind you. From here we maintain and taper."},
        // Week 15
        {week:15,day:1,type:"Easy Run",dist:7,dur:66,desc:"Easy 7km. Taper begins! Volume reduces — enjoy the lighter load."},
        {week:15,day:2,type:"Speed/Hill Training",dist:8,dur:78,desc:"5 × 2km at 10K pace. Maintaining sharpness as volume drops."},
        {week:15,day:3,type:"Medium Run",dist:10,dur:95,desc:"10km. Volume coming down — legs should start to feel bouncy soon."},
        {week:15,day:4,type:"Rest/Strength",dist:0,dur:20,desc:"Light strength only. No heavy loading — protect those legs for race day."},
        {week:15,day:5,type:"Tempo Run",dist:10,dur:95,desc:"10 min easy, 40 min at marathon pace, 10 min easy. Last substantial tempo."},
        {week:15,day:6,type:"Long Run",dist:22,dur:204,desc:"22km. Reduced from peak — but still a solid long run. Easy pace throughout."},
        {week:15,day:7,type:"Recovery Run",dist:4,dur:37,desc:"Easy 4km. Five weeks to race day. Your fitness is locked in. Trust it completely."},
        // Week 16
        {week:16,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Taper is well underway. Feeling a bit restless? That's normal and good."},
        {week:16,day:2,type:"Speed/Hill Training",dist:7,dur:68,desc:"4 × 2km at marathon pace. Race-specific and confidence-building."},
        {week:16,day:3,type:"Medium Run",dist:9,dur:86,desc:"9km moderate. Mileage continuing to reduce nicely."},
        {week:16,day:4,type:"Rest/Strength",dist:0,dur:20,desc:"Very light strength or rest. No new exercises — just maintenance."},
        {week:16,day:5,type:"Tempo Run",dist:8,dur:75,desc:"10 min easy, 30 min marathon pace, 10 min easy. Last quality tempo session."},
        {week:16,day:6,type:"Long Run",dist:18,dur:167,desc:"18km taper long run. Feels much easier after 32km runs — enjoy that feeling!"},
        {week:16,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Four weeks out. Race prep is now the focus."},
        // Week 17
        {week:17,day:1,type:"Easy Run",dist:6,dur:56,desc:"Easy 6km. Deep in taper now. Legs may feel heavy — completely normal."},
        {week:17,day:2,type:"Speed/Hill Training",dist:5,dur:50,desc:"6 × 800m at 10K pace. Short sharp session to keep legs feeling fast."},
        {week:17,day:3,type:"Medium Run",dist:8,dur:76,desc:"8km easy to moderate. Mileage continues to reduce."},
        {week:17,day:4,type:"Rest/Strength",dist:0,dur:15,desc:"Very light activity only. Finalize race logistics — hotel, travel, bib collection."},
        {week:17,day:5,type:"Tempo Run",dist:6,dur:57,desc:"10 min easy, 20 min marathon pace, 10 min easy. Light tune-up session."},
        {week:17,day:6,type:"Long Run",dist:14,dur:130,desc:"14km easy. Last double-digit run before race week."},
        {week:17,day:7,type:"Recovery Run",dist:3,dur:28,desc:"Easy 3km. Three weeks out. You are ready. Believe in all you have done."},
        // Week 18
        {week:18,day:1,type:"Easy Run",dist:5,dur:47,desc:"Easy 5km. Race week minus two. Keep it very easy — no fitness to gain now."},
        {week:18,day:2,type:"Speed/Hill Training",dist:4,dur:40,desc:"4 × 800m at 10K pace. Short and sharp. Just keeping the spark alive."},
        {week:18,day:3,type:"Medium Run",dist:6,dur:56,desc:"6km easy. Mileage significantly reduced. Trust the process!"},
        {week:18,day:4,type:"Rest/Strength",dist:0,dur:15,desc:"Rest or very short walk. Review race nutrition plan and pack your bag."},
        {week:18,day:5,type:"Tempo Run",dist:5,dur:47,desc:"10 min easy, 15 min marathon pace, 10 min easy. Last quality run before race week."},
        {week:18,day:6,type:"Long Run",dist:10,dur:95,desc:"10km easy. Last long-ish run. Feel how fresh and ready your legs are!"},
        {week:18,day:7,type:"Recovery Run",dist:2,dur:18,desc:"Easy 2km. Two weeks to marathon. Your fitness is at its peak."},
        // Week 19 - Pre-Race Week
        {week:19,day:1,type:"Easy Run",dist:4,dur:38,desc:"Easy 4km. Pre-race week. No hard efforts at all this week."},
        {week:19,day:2,type:"Strides",dist:3,dur:28,desc:"Easy 3km with 4 × 20-sec strides at race pace. Last speed work!"},
        {week:19,day:3,type:"Rest/Cross-train",dist:0,dur:15,desc:"Very easy walk or rest. Sort all race logistics today — nothing left to chance."},
        {week:19,day:4,type:"Easy Run",dist:3,dur:28,desc:"Easy 3km shakeout. Light and loose. Legs feel amazing, right?"},
        {week:19,day:5,type:"Rest",dist:0,dur:0,desc:"Rest. Travel to race if needed. Carb-load your meals. Sleep well."},
        {week:19,day:6,type:"Easy Run",dist:2,dur:18,desc:"10-15 min easy shakeout. Just to settle race-day nerves. That's all."},
        {week:19,day:7,type:"Rest",dist:0,dur:0,desc:"Complete rest. Race tomorrow! Lay out every item of kit. Eat your normal dinner. Sleep by 9:30pm."},
        // Week 20 - Race Week
        {week:20,day:1,type:"RACE DAY! 🏆",dist:42.2,dur:0,desc:"MARATHON RACE DAY! Start slow, stay patient in the first half, run your own race. 20 weeks of training brought you to this moment. YOU ARE A MARATHONER!"},
        {week:20,day:2,type:"Recovery Walk",dist:0,dur:30,desc:"Very gentle walk only. Ice bath or cold shower if possible. Legs up on the wall."},
        {week:20,day:3,type:"Rest",dist:0,dur:0,desc:"Complete rest. Eat whatever you want. You earned every bite. Reflect on your incredible journey."},
        {week:20,day:4,type:"Rest",dist:0,dur:0,desc:"Rest. Soreness peaks around day 3 after a marathon — totally normal. Rest completely."},
        {week:20,day:5,type:"Recovery Walk",dist:0,dur:30,desc:"Easy walk if legs allow. Very gentle. Your body is healing from an extraordinary effort."},
        {week:20,day:6,type:"Easy Walk/Jog",dist:2,dur:20,desc:"Very easy 20-min walk or jog only if legs feel good. No pressure at all."},
        {week:20,day:7,type:"Recovery",dist:0,dur:30,desc:"Easy walk and stretching. You completed a marathon. Share your story — you inspire others!"},
      ]},
    }
  },

  hydration: {
    // One plan per module — scientifically tailored to activity type
    default: {
      title: "Daily Hydration Plan",
      targets: { training: 3.0, rest: 2.5 },
      schedule: [
        { time:"7:00 AM",        amount:500, label:"Wake-up glass" },
        { time:"9:00 AM",        amount:400, label:"Mid-morning" },
        { time:"12:00 PM",       amount:500, label:"Before lunch" },
        { time:"3:00 PM",        amount:400, label:"Afternoon" },
        { time:"Pre-Workout",    amount:400, label:"30 min before" },
        { time:"During Workout", amount:500, label:"Sip every 15 min" },
        { time:"Post-Workout",   amount:500, label:"Within 30 min" },
        { time:"8:00 PM",        amount:300, label:"Evening" },
      ],
      tips: [
        "Urine colour should be pale yellow — dark means you need more water.",
        "Add a pinch of Himalayan pink salt on heavy training days to replace electrolytes.",
        "Drink 200–300ml extra per 30 min in hot or humid weather.",
      ]
    },

    cardio: {
      title: "Home Cardio Hydration Plan",
      targets: { training: 3.5, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (7 AM)",     amount:500, label:"Start metabolism, flush overnight waste" },
        { time:"Pre-Workout (30 min)", amount:400, label:"Hydrate before intense cardio" },
        { time:"During Cardio",      amount:600, label:"150ml every 15 min — cardio causes heavy sweat" },
        { time:"Post-Workout (30 min)", amount:500, label:"Replace sweat losses immediately" },
        { time:"Mid-Morning",        amount:400, label:"Sustained hydration between sessions" },
        { time:"Before Lunch",       amount:300, label:"Aids digestion and nutrient absorption" },
        { time:"Afternoon (3 PM)",   amount:400, label:"Prevents afternoon energy dip" },
        { time:"Evening (7 PM)",     amount:300, label:"Light — avoid excess before sleep" },
      ],
      tips: [
        "Cardio causes 0.5–1.5L sweat/hour — drink before you feel thirsty.",
        "Add coconut water or electrolyte tabs after sessions longer than 45 minutes.",
        "Cold water (15°C) absorbs 30% faster than room temperature during exercise.",
        "Weigh yourself before and after — drink 1.5L per kg lost during session.",
        "Avoid sugary sports drinks for sessions under 60 min — plain water is sufficient.",
      ]
    },

    gym: {
      title: "Gym Workout Hydration Plan",
      targets: { training: 4.0, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (7 AM)",      amount:500, label:"Rehydrate after 7–8 hrs without water" },
        { time:"Pre-Workout (60 min)", amount:500, label:"Top up glycogen and joints for lifting" },
        { time:"Pre-Workout (15 min)", amount:250, label:"Final top-up before first set" },
        { time:"During Lifting",      amount:750, label:"200ml between every 2–3 sets" },
        { time:"Post-Workout (30 min)", amount:600, label:"Critical — begin recovery immediately" },
        { time:"With Protein Meal",   amount:400, label:"Aids protein synthesis and digestion" },
        { time:"Afternoon",           amount:500, label:"Joints and muscle repair require hydration" },
        { time:"Evening",             amount:400, label:"Casein protein digestion needs extra water" },
      ],
      tips: [
        "Heavy lifting causes micro-tears — muscles repair faster when fully hydrated.",
        "Dehydration of just 2% body weight reduces strength by up to 10%.",
        "Creatine users need an extra 500ml daily — creatine draws water into muscles.",
        "Sip water between sets, not during reps — avoid bloating mid-lift.",
        "Post-workout: aim for 150% of fluid lost (e.g. lost 500ml → drink 750ml).",
        "Joint health: cartilage is 80% water — consistent hydration prevents knee/shoulder pain.",
      ]
    },

    yoga: {
      title: "Yoga Practice Hydration Plan",
      targets: { training: 2.5, rest: 2.0 },
      schedule: [
        { time:"Wake-Up (6:30 AM)",   amount:500, label:"Warm water with lemon — cleanses and alkalises" },
        { time:"30 Min Before Yoga",  amount:200, label:"Small sip only — avoid heavy stomach during poses" },
        { time:"During Practice",     amount:200, label:"Tiny sips only if very thirsty — don't interrupt flow" },
        { time:"Post-Practice",       amount:400, label:"Rehydrate mindfully after deep stretches" },
        { time:"Mid-Morning",         amount:400, label:"Room temperature water preferred in yoga lifestyle" },
        { time:"Before Lunch",        amount:300, label:"30 min before meals for optimal digestion" },
        { time:"Afternoon",           amount:350, label:"Herbal teas count — tulsi, ginger, chamomile" },
        { time:"Evening",             amount:250, label:"Light — calming the body before rest" },
      ],
      tips: [
        "Yoga tradition prefers room-temperature or warm water — cold water can disrupt digestive fire (agni).",
        "Avoid drinking large amounts 30 min before or during practice — it compresses the core.",
        "Coconut water is the ideal post-yoga drink — natural electrolytes and calming properties.",
        "Hot yoga (Bikram) requires 1L extra — you lose significantly more through sweat.",
        "Herbal teas (tulsi, ginger, peppermint) count toward daily intake and support digestion.",
        "Eating water-rich foods (cucumber, watermelon, oranges) aligns with yogic diet principles.",
      ]
    },

    stretching: {
      title: "Stretching & Recovery Hydration Plan",
      targets: { training: 2.5, rest: 2.0 },
      schedule: [
        { time:"Wake-Up",             amount:500, label:"Warm water — hydrates overnight-stiff muscles" },
        { time:"Before Stretching",   amount:300, label:"Warm muscles stretch better when hydrated" },
        { time:"During Stretching",   amount:200, label:"Small sips — stretching is low intensity" },
        { time:"Post-Stretching",     amount:300, label:"Flush released toxins from fascia" },
        { time:"Mid-Morning",         amount:400, label:"Collagen synthesis requires hydration" },
        { time:"Lunch Time",          amount:400, label:"Support joint lubrication throughout day" },
        { time:"Afternoon",           amount:300, label:"Consistent low-level hydration is key" },
        { time:"Evening",             amount:200, label:"Light — this is a recovery/rest day" },
      ],
      tips: [
        "Fascia (connective tissue) is 70% water — dehydration makes it stiff and less elastic.",
        "Warm water before stretching loosens muscle fibres faster than cold water.",
        "Collagen (joint and muscle repair) synthesis requires adequate vitamin C and hydration.",
        "Bone broth counts toward intake and provides collagen directly.",
        "Avoid alcohol on stretching/rest days — it dehydrates and slows muscle repair by 24hrs.",
        "Magnesium-rich water (or supplement) on rest days reduces muscle soreness significantly.",
      ]
    },

    running: {
      title: "Running & Walking Hydration Plan",
      targets: { training: 4.5, rest: 2.5 },
      schedule: [
        { time:"Wake-Up (6 AM)",       amount:500, label:"Start the day hydrated before early runs" },
        { time:"2 Hours Before Run",   amount:500, label:"Pre-load hydration — kidneys process excess" },
        { time:"15 Min Before Run",    amount:200, label:"Final top-up without bloating" },
        { time:"During Run (<45 min)", amount:400, label:"150–200ml every 20 min — small frequent sips" },
        { time:"During Run (>45 min)", amount:700, label:"Sports drink or water + salt every 20–30 min" },
        { time:"Post-Run (30 min)",    amount:600, label:"Most critical window — begin recovery immediately" },
        { time:"Post-Run (2 hrs)",     amount:500, label:"Continue sipping — 1.5L per kg lost" },
        { time:"Evening",              amount:400, label:"Support overnight muscle and joint recovery" },
      ],
      tips: [
        "Running loses 500ml–1.5L per hour depending on heat, humidity and pace.",
        "The thirst signal lags 20 min behind actual need — drink on a schedule, not when thirsty.",
        "For runs over 60 min, add electrolytes (sodium, potassium) — water alone causes hyponatremia.",
        "Hot weather running: pre-cool with 500ml ice-cold water 10 min before — reduces core temp.",
        "Weigh before and after every long run. Drink 1.5L for every 1kg lost.",
        "Marathon training: increase daily intake by 1L on days with runs over 16km.",
        "Signs of dehydration while running: dark urine, headache, cramping, nausea, confusion — stop immediately.",
      ]
    },
  },

    diet: {
    modules: {
      cardio:     { title:"Cardio Day Diet Plan",   meals:[
        { time:"Pre-Workout",  name:"Energy Boost",     items:"Banana + black coffee or green tea", cal:150, notes:"30-45 min before session" },
        { time:"Post-Workout", name:"Recovery Meal",    items:"2 boiled eggs + 1 slice whole wheat toast", cal:220, notes:"Within 30 min after" },
        { time:"Breakfast",    name:"Carb-Forward Meal",items:"Oats porridge with fruit and nuts", cal:380, notes:"Replenish glycogen" },
        { time:"Lunch",        name:"Balanced Meal",    items:"Brown rice + grilled chicken 150g + vegetables", cal:560, notes:"Protein + complex carbs" },
        { time:"Snack",        name:"Afternoon Fuel",   items:"Greek yogurt + handful of almonds", cal:220, notes:"Sustained energy" },
        { time:"Dinner",       name:"Light Recovery",   items:"Lentil soup + 2 chapati + salad", cal:480, notes:"Early, light dinner" },
      ]},
      gym:        { title:"Gym Day Diet Plan",      meals:[
        { time:"Pre-Workout",  name:"Power Fuel",        items:"Banana + 2 boiled eggs + optional coffee", cal:280, notes:"60 min before lifting" },
        { time:"Intra-Workout",name:"Hydration",         items:"Water + optional BCAA drink", cal:50, notes:"Sip during session" },
        { time:"Post-Workout", name:"Anabolic Window",   items:"Whey protein shake or 200g Greek yogurt + fruit", cal:280, notes:"Within 30 min — critical!" },
        { time:"Lunch",        name:"Muscle Building",   items:"Brown rice 200g + grilled chicken 180g + vegetables", cal:620, notes:"2-3 hrs post-workout" },
        { time:"Snack",        name:"Protein Boost",     items:"Cottage cheese or paneer 100g + fruit", cal:200, notes:"Afternoon" },
        { time:"Dinner",       name:"Casein Meal",       items:"Dal + 2 chapati + salad + glass of milk", cal:520, notes:"Slow-digesting protein overnight" },
      ]},
      yoga:       { title:"Yoga Day Diet Plan",     meals:[
        { time:"Pre-Yoga",  name:"Light Energy",       items:"Small banana or 4-5 dates + herbal tea", cal:120, notes:"30-60 min before. Avoid heavy food." },
        { time:"Post-Yoga", name:"Nourishment",        items:"Smoothie: banana + spinach + almond milk + honey", cal:240, notes:"Replenish mindfully" },
        { time:"Breakfast", name:"Sattvic Breakfast",  items:"Poha or upma + coconut chutney + herbal tea", cal:360, notes:"Light, digestible" },
        { time:"Lunch",     name:"Balanced Thali",     items:"Dal + rice + sabzi + curd + salad", cal:580, notes:"Largest meal of day" },
        { time:"Snack",     name:"Light Snack",        items:"Fresh fruit + handful walnuts", cal:180, notes:"Afternoon, light" },
        { time:"Dinner",    name:"Early Light Dinner", items:"Khichdi or vegetable soup + bread", cal:420, notes:"By 7pm ideally" },
      ]},
      stretching: { title:"Rest/Stretch Day Diet Plan", meals:[
        { time:"Morning",  name:"Anti-Inflammatory",items:"Turmeric milk or golden latte + fruit", cal:200, notes:"Anti-inflammatory start" },
        { time:"Breakfast",name:"Protein + Fibre",   items:"2 eggs any style + whole grain toast + avocado", cal:420, notes:"Sustained energy" },
        { time:"Lunch",    name:"Omega-Rich Meal",   items:"Grilled fish or tofu + quinoa + roasted vegetables", cal:540, notes:"Recovery nutrition" },
        { time:"Snack",    name:"Collagen Boost",    items:"Bone broth or gelatin-rich foods", cal:120, notes:"Supports joint health" },
        { time:"Dinner",   name:"Recovery Dinner",   items:"Chicken/lentil soup + whole grain bread", cal:460, notes:"Easy to digest" },
      ]},
      running: { title:"Running Day Diet Plan", meals:[
        { time:"Pre-Run (2-3 hrs)", name:"Main Pre-Run Meal", items:"Oats with banana + honey OR 2 slices toast + peanut butter + banana", cal:380, notes:"Easy to digest carbs — avoid fibre and fat close to run" },
        { time:"Pre-Run (30 min)", name:"Quick Energy Top-Up", items:"1 banana OR 4–5 dates OR half energy bar", cal:120, notes:"Quick-release glucose — nothing heavy" },
        { time:"During Run (>60 min)", name:"Intra-Run Fuel", items:"Energy gel OR banana chunk OR 3–4 dates every 45 min", cal:100, notes:"Per serving — only needed for runs over 60 min" },
        { time:"Post-Run (30 min)", name:"Recovery Window", items:"Chocolate milk OR whey shake + banana OR Greek yogurt + mango", cal:320, notes:"CRITICAL: 3:1 carb:protein ratio — this window is gold" },
        { time:"Post-Run Meal (1-2 hrs)", name:"Full Recovery Meal", items:"White rice + grilled chicken/fish + roasted vegetables", cal:620, notes:"White rice preferred post-run — faster glycogen replenishment than brown" },
        { time:"Evening Snack", name:"Overnight Recovery", items:"Cottage cheese (paneer) OR casein protein + warm milk", cal:220, notes:"Slow-digesting protein repairs muscles during sleep" },
      ]},
    }
  }
};

window.DEFAULT_USERS = [
  { id:"u_admin", name:"Admin User",  email:"admin@fitflow.com", password:"admin123", tempPassword:"", isFirstLogin:false, role:"ADMIN", status:"ACTIVE", createdDate:"2025-01-01" },
];
